In [93]:
# Step 1: Importar las librerías necesarias
import sys
!{sys.executable} -m pip install pymysql
import pandas as pd

Requirement already satisfied: pymysql in c:\users\dell\anaconda3\lib\site-packages (0.9.3)

In [94]:
import pymysql
from sqlalchemy import create_engine

In [95]:
import sqlite3
import numpy as np

In [96]:
# Step 2: Conectarse a la base de datos y hacer un query de cada una de las 7 tablas que la conforman
with sqlite3.connect("database.sqlite") as con:
    countries = pd.read_sql("SELECT * from Country", con)
    matches = pd.read_sql("SELECT * from Match", con)
    leagues = pd.read_sql("SELECT * from League", con)
    teams = pd.read_sql("SELECT * from Team", con)
    teams_stats = pd.read_sql("SELECT * from Team_Attributes", con)
    players = pd.read_sql("SELECT * from Player", con)

    player_stats = pd.read_sql("SELECT * from Player_Attributes", con)

In [97]:
# Step 3: Imprimir cada una de las 7 tablas, así como sus columnas. 
countries

       id         name
0       1      Belgium
1    1729      England
2    4769       France
3    7809      Germany
4   10257        Italy
5   13274  Netherlands
6   15722       Poland
7   17642     Portugal
8   19694     Scotland
9   21518        Spain
10  24558  Switzerland

In [14]:
countries.columns

Index(['id', 'name'], dtype='object')

In [24]:
matches.head(5)

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67

In [16]:
matches.columns

Index(['id', 'country_id', 'league_id', 'season', 'stage', 'date',
       'match_api_id', 'home_team_api_id', 'away_team_api_id',
       'home_team_goal',
       ...
       'SJA', 'VCH', 'VCD', 'VCA', 'GBH', 'GBD', 'GBA', 'BSH', 'BSD', 'BSA'],
      dtype='object', length=115)

In [8]:
leagues.head(20)

       id  country_id                      name
0       1           1    Belgium Jupiler League
1    1729        1729    England Premier League
2    4769        4769            France Ligue 1
3    7809        7809     Germany 1. Bundesliga
4   10257       10257             Italy Serie A
5   13274       13274    Netherlands Eredivisie
6   15722       15722        Poland Ekstraklasa
7   17642       17642  Portugal Liga ZON Sagres
8   19694       19694   Scotland Premier League
9   21518       21518           Spain LIGA BBVA
10  24558       24558  Switzerland Super League

In [17]:
leagues.columns

Index(['id', 'country_id', 'name'], dtype='object')

In [9]:
teams.head(50)

,id,team_api_id,team_fifa_api_id,team_long_name,team_short_name
0,1,9987,673.0,KRC Genk,GEN
1,2,9993,675.0,Beerschot AC,BAC
2,3,10000,15005.0,SV Zulte-Waregem,ZUL
3,4,9994,2007.0,Sporting Lokeren,LOK
4,5,9984,1750.0,KSV Cercle Brugge,CEB
5,6,8635,229.0,RSC Anderlecht,AND
6,7,9991,674.0,KAA Gent,GEN
7,8,9998,1747.0,RAEC Mons,MON
8,9,7947,NaN,FCV Dender EH,DEN
9,10,9985,232.0,Standard de Liège,STL
10,11,8203,110724.0,KV Mechelen,MEC
11,12,8342,231.0,Club Brugge KV,CLB
12,13,9999,546.0,KSV Roeselare,ROS
13,14,8571,100081.0,KV Kortrijk,KOR
14,15,4049,NaN,Tubize,TUB
15,16,9996,111560.0,Royal Excel Mouscron,MOU
16,17,10001,681.0,KVC Westerlo,WES
17,18,9986,670.0,Sporting Charleroi,CHA
18,614,9997,680.0,Sint-Truidense VV,STT
19,1034,9989,239.0,Lierse SK,LIE
20,1042,6351,2013.0,KAS Eupen,EUP
21,1513,1773,100087.0,Oud-Heverlee Leuven,O-H
22,2004,8475,110913.0,Waasland-Beveren,WAA
23,2476,8573,682.0,KV Oostende,OOS
24,2510,274581,111560.0,Royal Excel Mouscron,MOP
25,3457,10260,11.0,Manchester United,MUN
26,3458,10261,13.0,Newcastle United,NEW
27,3459,9825,1.0,Arsenal,ARS
28,3460,8659,109.0,West Bromwich Albion,WBA
29,3461,8472,106.0,Sunderland,SUN
30,3462,8650,9.0,Liverpool,LIV
31,3463,8654,19.0,West Ham United,WHU
32,3464,8528,1917.0,Wigan Athletic,WIG
33,3465,10252,2.0,Aston Villa,AVL
34,3466,8456,10.0,Manchester City,MCI
35,3467,8668,7.0,Everton,EVE
36,3468,8655,3.0,Blackburn Rovers,BLB
37,3469,8549,12.0,Middlesbrough,MID
38,3470,8586,18.0,Tottenham Hotspur,TOT
39,3471,8559,4.0,Bolton Wanderers,BOL
40,3472,10194,1806.0,Stoke City,STK
41,3473,8667,1952.0,Hull City,HUL
42,3474,9879,144.0,Fulham,FUL
43,3475,8455,5.0,Chelsea,CHE
44,3476,8462,1790.0,Portsmouth,POR
45,4218,8658,88.0,Birmingham City,BIR
46,4225,8602,110.0,Wolverhampton Wanderers,WOL
47,4234,8191,1796.0,Burnley,BUR
48,4996,8483,1926.0,Blackpool,BLA
49,5744,10003,1960.0,Swansea City,SWA

In [18]:
teams.columns

Index(['id', 'team_api_id', 'team_fifa_api_id', 'team_long_name',
       'team_short_name'],
      dtype='object')

In [10]:
teams_stats.head(50)

,id,team_fifa_api_id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
0,1,434,9930,2010-02-22 00:00:00,60,Balanced,NaN,Little,50,Mixed,...,55,Normal,Organised,50,Medium,55,Press,45,Normal,Cover
1,2,434,9930,2014-09-19 00:00:00,52,Balanced,48.0,Normal,56,Mixed,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
2,3,434,9930,2015-09-10 00:00:00,47,Balanced,41.0,Normal,54,Mixed,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
3,4,77,8485,2010-02-22 00:00:00,70,Fast,NaN,Little,70,Long,...,70,Lots,Organised,60,Medium,70,Double,70,Wide,Cover
4,5,77,8485,2011-02-22 00:00:00,47,Balanced,NaN,Little,52,Mixed,...,52,Normal,Organised,47,Medium,47,Press,52,Normal,Cover
5,6,77,8485,2012-02-22 00:00:00,58,Balanced,NaN,Little,62,Mixed,...,55,Normal,Organised,40,Medium,40,Press,60,Normal,Cover
6,7,77,8485,2013-09-20 00:00:00,62,Balanced,NaN,Little,45,Mixed,...,55,Normal,Organised,42,Medium,42,Press,60,Normal,Cover
7,8,77,8485,2014-09-19 00:00:00,58,Balanced,64.0,Normal,62,Mixed,...,57,Normal,Organised,41,Medium,42,Press,60,Normal,Cover
8,9,77,8485,2015-09-10 00:00:00,59,Balanced,64.0,Normal,53,Mixed,...,63,Normal,Free Form,49,Medium,45,Press,63,Normal,Cover
9,10,614,8576,2010-02-22 00:00:00,60,Balanced,NaN,Little,40,Mixed,...,55,Normal,Organised,30,Deep,70,Double,30,Narrow,Offside Trap
10,11,614,8576,2011-02-22 00:00:00,65,Balanced,NaN,Little,45,Mixed,...,50,Normal,Organised,45,Medium,45,Press,50,Normal,Cover
11,12,614,8576,2012-02-22 00:00:00,59,Balanced,NaN,Little,52,Mixed,...,52,Normal,Organised,38,Medium,47,Press,53,Normal,Cover
12,13,614,8576,2013-09-20 00:00:00,59,Balanced,NaN,Little,52,Mixed,...,52,Normal,Organised,38,Medium,47,Press,53,Normal,Cover
13,14,614,8576,2014-09-19 00:00:00,59,Balanced,57.0,Normal,52,Mixed,...,52,Normal,Organised,38,Medium,47,Press,53,Normal,Cover
14,15,614,8576,2015-09-10 00:00:00,59,Balanced,57.0,Normal,52,Mixed,...,52,Normal,Organised,38,Medium,47,Press,53,Normal,Cover
15,16,47,8564,2010-02-22 00:00:00,45,Balanced,NaN,Little,30,Short,...,70,Lots,Free Form,30,Deep,35,Press,60,Normal,Offside Trap
16,17,47,8564,2011-02-22 00:00:00,65,Balanced,NaN,Little,50,Mixed,...,50,Normal,Free Form,50,Medium,50,Press,50,Normal,Offside Trap
17,18,47,8564,2012-02-22 00:00:00,45,Balanced,NaN,Little,50,Mixed,...,50,Normal,Free Form,45,Medium,45,Press,50,Normal,Cover
18,19,47,8564,2013-09-20 00:00:00,48,Balanced,NaN,Little,54,Mixed,...,64,Normal,Free Form,48,Medium,49,Press,53,Normal,Cover
19,20,47,8564,2014-09-19 00:00:00,48,Balanced,70.0,Lots,52,Mixed,...,75,Lots,Organised,58,Medium,57,Press,49,Normal,Cover
20,21,47,8564,2015-09-10 00:00:00,48,Balanced,70.0,Lots,52,Mixed,...,69,Lots,Organised,58,Medium,57,Press,49,Normal,Cover
21,22,1901,10215,2010-02-22 00:00:00,30,Slow,NaN,Little,30,Short,...,55,Normal,Organised,30,Deep,30,Contain,30,Narrow,Offside Trap
22,23,1901,10215,2011-02-22 00:00:00,30,Slow,NaN,Little,50,Mixed,...,55,Normal,Organised,30,Deep,45,Press,65,Normal,Cover
23,24,1901,10215,2012-02-22 00:00:00,45,Balanced,NaN,Little,44,Mixed,...,60,Normal,Organised,52,Medium,38,Press,61,Normal,Cover
24,25,1901,10215,2013-09-20 00:00:00,45,Balanced,NaN,Little,44,Mixed,...,60,Normal,Organised,52,Medium,38,Press,61,Normal,Cover
25,26,1901,10215,2014-09-19 00:00:00,52,Balanced,53.0,Normal,44,Mixed,...,60,Normal,Organised,39,Medium,38,Press,61,Normal,Cover
26,27,1901,10215,2015-09-10 00:00:00,53,Balanced,53.0,Normal,44,Mixed,...,60,Normal,Organised,39,Medium,38,Press,61,Normal,Cover
27,28,650,10217,2010-02-22 00:00:00,30,Slow,NaN,Little,35,Mixed,...,65,Normal,Organised,30,Deep,30,Contain,30,Narrow,Cover
28,29,650,10217,2011-02-22 00:00:00,53,Balanced,NaN,Little,53,Mixed,...,66,Normal,Organised,46,Medium,62,Press,65,Normal,Cover
29,30,650,10217,2012-02-22 00:00:00,38,Balanced,NaN,Little,44,Mixed,...,44,Normal,Organised,50,Medium,58,Press,62,Normal,Cover
30,31,650,10217,2013-09-20 00:00:00,38,Balanced,NaN,Little,47,Mixed,...,44,Normal,Organised,50,Medium,58,Press,52,Normal,Cover
31,32,650,10217,2014-09-19 00:00:00,58,Balanced,47.0,Normal,55,Mixed,...,44,Normal,Organised,57,Medium,50,Press,52,Normal,Cover
32,33,650,10217,2015-09-10 00:00:00,56,Balanced,40.0,Normal,66,Mixed,...,38,Normal,Organised,40,Medium,50,Press,52,Normal,Cover
33,34,245,8593,2010-02-22 00:00:00,30,Slow,NaN,Little,30,Short,...,70,Lots,Organised,30,Deep,30,Contain,30,Narrow,Cover
34,35,245,8593,2011-02-22 00:00:00,40,Balanced,NaN,Little,38,Mixed,...,67,Lots,Organised,65,Medium,57,Press,63,Normal,Cover
35,36,245,8593,2012-02-22 00:00:00,31,Slow,NaN,Little,33,Short,...,46,Normal,Free Form,68,High,65,Press,60,Normal,Cover
36,37,245,8593,2013-09-20 00:00:00,35,Balanced,NaN,Little,33,Short,...,46,Normal,Free Form,68,High,65,Press,50,Normal,Cover
37,38,245,8593,2014-09-19 00:00:00,40,Balanced,40.0,Normal,30,Short,...,39,Normal,Free Form,64,Medium,53,Press,64,Normal,Cover
38,39,245,8593,2015-09-10 00:00:00,35,Balanced,43.0,Normal,39,Mixed,...,30,Little,Free Form,64,Medium,53,Press,59,Normal,Cover
39,40,1861,9865,2010-02-22 00:00:00,65,Balanced,NaN,Little,45,Mixed,...,70,Lots,Organised,70,High,65,Press,30,Narrow,Cover
40,41,1861,9865,2011-02-22 00:00:00,55,Balanced,NaN,Little,53,Mixed,...,69,Lots,Organised,58,Medium,68,Double,67,Wide,Cover
41,42,1861,9865,2012-02-22 00:00:00,42,Balanced,NaN,Little,70,Long,...,40,Normal,Organised,37,Medium,53,Press,45,Normal,Cover
42,43,1861,9865,2013-09-20 00:00:00,46,Balanced,NaN,Little,65,Mixed,...,40,Normal,Organised,37,Medium,53,Press,45,Normal,Cover
43,44,1861,9865,2014-09-19 00:00:00,46,Balanced,41.0,Normal,65,Mixed,...,40,Normal,Organised,37,Medium,53,Press,45,Normal,Cover
44,45,1861,9865,2015-09-10 00:00:00,46,Balanced,41.0,Normal,65,Mixed,...,40,Normal,Organised,37,Medium,53,Press,45,Normal,Cover
45,46,229,8635,2010-02-22 00:00:00,50,Balanced,NaN,Little,35,Mixed,...,60,Normal,Organised,70,High,50,Press,70,Wide,Cover
46,47,229,8635,2011-02-22 00:00:00,50,Balanced,NaN,Little,52,Mixed,...,60,Normal,Organised,70,High,50,Press,70,Wide,Offside Trap
47,48,229,8635,2012-02-22 00:00:00,52,Balanced,NaN,Little,41,Mixed,...,47,Normal,Organised,45,Medium,43,Press,52,Normal,Cover
48,49,229,8635,2013-09-20 00:00:00,52,Balanced,NaN,Little,41,Mixed,...,47,Normal,Organised,60,Medium,43,Press,65,Normal,Cover
49,50,229,8635,2014-09-19 00:00:00,52,Balanced,46.0,Normal,51,Mixed,...,47,Normal,Organised,60,Medium,50,Press,65,Normal,Cover

In [19]:
teams_stats.columns

Index(['id', 'team_fifa_api_id', 'team_api_id', 'date', 'buildUpPlaySpeed',
       'buildUpPlaySpeedClass', 'buildUpPlayDribbling',
       'buildUpPlayDribblingClass', 'buildUpPlayPassing',
       'buildUpPlayPassingClass', 'buildUpPlayPositioningClass',
       'chanceCreationPassing', 'chanceCreationPassingClass',
       'chanceCreationCrossing', 'chanceCreationCrossingClass',
       'chanceCreationShooting', 'chanceCreationShootingClass',
       'chanceCreationPositioningClass', 'defencePressure',
       'defencePressureClass', 'defenceAggression', 'defenceAggressionClass',
       'defenceTeamWidth', 'defenceTeamWidthClass',
       'defenceDefenderLineClass'],
      dtype='object')

In [11]:
players.head(20)

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,1,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,2,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146
2,3,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163
3,4,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198
4,5,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154
5,6,27316,Aaron Hunt,158138,1986-09-04 00:00:00,182.88,161
6,7,564793,Aaron Kuhl,221280,1996-01-30 00:00:00,172.72,146
7,8,30895,Aaron Lennon,152747,1987-04-16 00:00:00,165.10,139
8,9,528212,Aaron Lennox,206592,1993-02-19 00:00:00,190.50,181
9,10,101042,Aaron Meijers,188621,1987-10-28 00:00:00,175.26,170
10,11,23889,Aaron Mokoena,47189,1980-11-25 00:00:00,182.88,181
11,12,231592,Aaron Mooy,194958,1990-09-15 00:00:00,175.26,150
12,13,163222,Aaron Muirhead,213568,1990-08-30 00:00:00,187.96,168
13,14,40719,Aaron Niguez,183853,1989-04-26 00:00:00,170.18,143
14,15,75489,Aaron Ramsey,186561,1990-12-26 00:00:00,177.80,154
15,16,597948,Aaron Splaine,226014,1996-10-13 00:00:00,172.72,163
16,17,161644,Aaron Taylor-Sinclair,213569,1991-04-08 00:00:00,182.88,176
17,18,23499,Aaron Wilbraham,2335,1979-10-21 00:00:00,190.50,159
18,19,120919,Aatif Chahechouhe,187939,1986-07-02 00:00:00,175.26,150
19,20,46447,Abasse Ba,156626,1976-07-12 00:00:00,187.96,185

In [20]:
players.columns

Index(['id', 'player_api_id', 'player_name', 'player_fifa_api_id', 'birthday',
       'height', 'weight'],
      dtype='object')

In [12]:
player_stats.head(20)

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
5,6,189615,155782,2016-04-21 00:00:00,74.0,76.0,left,high,medium,80.0,...,66.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
6,7,189615,155782,2016-04-07 00:00:00,74.0,76.0,left,high,medium,80.0,...,66.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
7,8,189615,155782,2016-01-07 00:00:00,73.0,75.0,left,high,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
8,9,189615,155782,2015-12-24 00:00:00,73.0,75.0,left,high,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
9,10,189615,155782,2015-12-17 00:00:00,73.0,75.0,left,high,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
10,11,189615,155782,2015-10-16 00:00:00,73.0,77.0,left,high,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
11,12,189615,155782,2015-09-25 00:00:00,74.0,78.0,left,high,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
12,13,189615,155782,2015-09-21 00:00:00,73.0,77.0,left,medium,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
13,14,189615,155782,2015-01-09 00:00:00,71.0,75.0,left,medium,medium,78.0,...,64.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
14,15,189615,155782,2014-12-05 00:00:00,71.0,77.0,left,medium,medium,78.0,...,64.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
15,16,189615,155782,2014-11-07 00:00:00,71.0,77.0,left,medium,medium,78.0,...,64.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
16,17,189615,155782,2014-09-18 00:00:00,70.0,77.0,left,medium,medium,77.0,...,64.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
17,18,189615,155782,2014-05-02 00:00:00,70.0,79.0,left,medium,medium,77.0,...,64.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
18,19,189615,155782,2014-04-04 00:00:00,70.0,79.0,left,medium,medium,77.0,...,64.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
19,20,189615,155782,2014-03-14 00:00:00,70.0,79.0,left,medium,medium,77.0,...,61.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0

In [22]:
player_stats.columns

Index(['id', 'player_fifa_api_id', 'player_api_id', 'date', 'overall_rating',
       'potential', 'preferred_foot', 'attacking_work_rate',
       'defensive_work_rate', 'crossing', 'finishing', 'heading_accuracy',
       'short_passing', 'volleys', 'dribbling', 'curve', 'free_kick_accuracy',
       'long_passing', 'ball_control', 'acceleration', 'sprint_speed',
       'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina',
       'strength', 'long_shots', 'aggression', 'interceptions', 'positioning',
       'vision', 'penalties', 'marking', 'standing_tackle', 'sliding_tackle',
       'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning',
       'gk_reflexes'],
      dtype='object')

In [98]:
# Step 4: Check missing values in every table
# Posteriormente, en aquellas tablas que tengan valores nulos, llamar a dichos valores.
countries_null_cols = countries.isnull().sum()
countries_null_cols

id      0
name    0
dtype: int64

In [99]:
matches_null_cols = matches.isnull().sum()
matches_null_cols

id                      0
country_id              0
league_id               0
season                  0
stage                   0
date                    0
match_api_id            0
home_team_api_id        0
away_team_api_id        0
home_team_goal          0
away_team_goal          0
home_player_X1       1821
home_player_X2       1821
home_player_X3       1832
home_player_X4       1832
home_player_X5       1832
home_player_X6       1832
home_player_X7       1832
home_player_X8       1832
home_player_X9       1832
home_player_X10      1832
home_player_X11      1832
away_player_X1       1832
away_player_X2       1832
away_player_X3       1832
away_player_X4       1832
away_player_X5       1832
away_player_X6       1832
away_player_X7       1832
away_player_X8       1832
                    ...
B365H                3387
B365D                3387
B365A                3387
BWH                  3404
BWD                  3404
BWA                  3404
IWH                  3459
IWD                  3459
IWA                  3459
LBH                  3423
LBD                  3423
LBA                  3423
PSH                 14811
PSD                 14811
PSA                 14811
WHH                  3408
WHD                  3408
WHA                  3408
SJH                  8882
SJD                  8882
SJA                  8882
VCH                  3411
VCD                  3411
VCA                  3411
GBH                 11817
GBD                 11817
GBA                 11817
BSH                 11818
BSD                 11818
BSA                 11818
Length: 115, dtype: int64

In [100]:
matches_null_cols[matches_null_cols > 0]

home_player_X1      1821
home_player_X2      1821
home_player_X3      1832
home_player_X4      1832
home_player_X5      1832
home_player_X6      1832
home_player_X7      1832
home_player_X8      1832
home_player_X9      1832
home_player_X10     1832
home_player_X11     1832
away_player_X1      1832
away_player_X2      1832
away_player_X3      1832
away_player_X4      1832
away_player_X5      1832
away_player_X6      1832
away_player_X7      1832
away_player_X8      1832
away_player_X9      1833
away_player_X10     1833
away_player_X11     1839
home_player_Y1      1821
home_player_Y2      1821
home_player_Y3      1832
home_player_Y4      1832
home_player_Y5      1832
home_player_Y6      1832
home_player_Y7      1832
home_player_Y8      1832
                   ...
B365H               3387
B365D               3387
B365A               3387
BWH                 3404
BWD                 3404
BWA                 3404
IWH                 3459
IWD                 3459
IWA                 3459
LBH                 3423
LBD                 3423
LBA                 3423
PSH                14811
PSD                14811
PSA                14811
WHH                 3408
WHD                 3408
WHA                 3408
SJH                 8882
SJD                 8882
SJA                 8882
VCH                 3411
VCD                 3411
VCA                 3411
GBH                11817
GBD                11817
GBA                11817
BSH                11818
BSD                11818
BSA                11818
Length: 104, dtype: int64

In [101]:
leagues_null_cols = leagues.isnull().sum()
leagues_null_cols

id            0
country_id    0
name          0
dtype: int64

In [102]:
teams_null_cols = teams.isnull().sum()
teams_null_cols

id                   0
team_api_id          0
team_fifa_api_id    11
team_long_name       0
team_short_name      0
dtype: int64

In [103]:
teams_null_cols[teams_null_cols > 0]

team_fifa_api_id    11
dtype: int64

In [104]:
teams_stats_null_cols = teams_stats.isnull().sum()
teams_stats_null_cols

id                                  0
team_fifa_api_id                    0
team_api_id                         0
date                                0
buildUpPlaySpeed                    0
buildUpPlaySpeedClass               0
buildUpPlayDribbling              969
buildUpPlayDribblingClass           0
buildUpPlayPassing                  0
buildUpPlayPassingClass             0
buildUpPlayPositioningClass         0
chanceCreationPassing               0
chanceCreationPassingClass          0
chanceCreationCrossing              0
chanceCreationCrossingClass         0
chanceCreationShooting              0
chanceCreationShootingClass         0
chanceCreationPositioningClass      0
defencePressure                     0
defencePressureClass                0
defenceAggression                   0
defenceAggressionClass              0
defenceTeamWidth                    0
defenceTeamWidthClass               0
defenceDefenderLineClass            0
dtype: int64

In [105]:
teams_stats_null_cols[teams_stats_null_cols > 0]

buildUpPlayDribbling    969
dtype: int64

In [106]:
players_null_cols = players.isnull().sum()
players_null_cols

id                    0
player_api_id         0
player_name           0
player_fifa_api_id    0
birthday              0
height                0
weight                0
dtype: int64

In [107]:
player_stats_null_cols = player_stats.isnull().sum()
player_stats_null_cols

id                        0
player_fifa_api_id        0
player_api_id             0
date                      0
overall_rating          836
potential               836
preferred_foot          836
attacking_work_rate    3230
defensive_work_rate     836
crossing                836
finishing               836
heading_accuracy        836
short_passing           836
volleys                2713
dribbling               836
curve                  2713
free_kick_accuracy      836
long_passing            836
ball_control            836
acceleration            836
sprint_speed            836
agility                2713
reactions               836
balance                2713
shot_power              836
jumping                2713
stamina                 836
strength                836
long_shots              836
aggression              836
interceptions           836
positioning             836
vision                 2713
penalties               836
marking                 836
standing_tackle         836
sliding_tackle         2713
gk_diving               836
gk_handling             836
gk_kicking              836
gk_positioning          836
gk_reflexes             836
dtype: int64

In [108]:
player_stats_null_cols[player_stats_null_cols > 0]

overall_rating          836
potential               836
preferred_foot          836
attacking_work_rate    3230
defensive_work_rate     836
crossing                836
finishing               836
heading_accuracy        836
short_passing           836
volleys                2713
dribbling               836
curve                  2713
free_kick_accuracy      836
long_passing            836
ball_control            836
acceleration            836
sprint_speed            836
agility                2713
reactions               836
balance                2713
shot_power              836
jumping                2713
stamina                 836
strength                836
long_shots              836
aggression              836
interceptions           836
positioning             836
vision                 2713
penalties               836
marking                 836
standing_tackle         836
sliding_tackle         2713
gk_diving               836
gk_handling             836
gk_kicking              836
gk_positioning          836
gk_reflexes             836
dtype: int64

In [ ]:
# Step 5: Análisis sobre los valores nulos en ambas tablas elegidas para limpieza y manipulación:
# player_stats y match

# Matches y Player_stats son las tablas que tienen valores nulos
#(team_stats y teams tienen solo un atributo con valores nulos,
#mientras que leagues, countries y players no tienen valores nulos)

In [109]:
player_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183978 entries, 0 to 183977
Data columns (total 42 columns):
id                     183978 non-null int64
player_fifa_api_id     183978 non-null int64
player_api_id          183978 non-null int64
date                   183978 non-null object
overall_rating         183142 non-null float64
potential              183142 non-null float64
preferred_foot         183142 non-null object
attacking_work_rate    180748 non-null object
defensive_work_rate    183142 non-null object
crossing               183142 non-null float64
finishing              183142 non-null float64
heading_accuracy       183142 non-null float64
short_passing          183142 non-null float64
volleys                181265 non-null float64
dribbling              183142 non-null float64
curve                  181265 non-null float64
free_kick_accuracy     183142 non-null float64
long_passing           183142 non-null float64
ball_control           183142 non-null float64
acceleration           183142 non-null float64
sprint_speed           183142 non-null float64
agility                181265 non-null float64
reactions              183142 non-null float64
balance                181265 non-null float64
shot_power             183142 non-null float64
jumping                181265 non-null float64
stamina                183142 non-null float64
strength               183142 non-null float64
long_shots             183142 non-null float64
aggression             183142 non-null float64
interceptions          183142 non-null float64
positioning            183142 non-null float64
vision                 181265 non-null float64
penalties              183142 non-null float64
marking                183142 non-null float64
standing_tackle        183142 non-null float64
sliding_tackle         181265 non-null float64
gk_diving              183142 non-null float64
gk_handling            183142 non-null float64
gk_kicking             183142 non-null float64
gk_positioning         183142 non-null float64
gk_reflexes            183142 non-null float64
dtypes: float64(35), int64(3), object(4)
memory usage: 59.0+ MB

In [110]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25979 entries, 0 to 25978
Columns: 115 entries, id to BSA
dtypes: float64(96), int64(9), object(10)
memory usage: 22.8+ MB

In [111]:
# ¿Sobre cuántos jugadores se está calculando un overall rating?

overall_rating_count = player_stats['overall_rating']
print("el número de jugadores sobre los cuáles se está analizando su overall rating es: ", overall_rating_count.value_counts().sum())

el número de jugadores sobre los cuáles se está analizando su overall rating es:  183142

In [ ]:
# Análisis respecto a la tabla player_stats

# No considero que valga la pena deshacernos de todos los atributos que tienen valores 
# nulos en la tabla player_stats, pues son relativamente pocos valores nulos 
# comparados con el total (836/183142).
# sería un error eliminar columnas que parecen muy interesantes para un análisis posterior
# solo por el hecho de presentar algunos valores nulos como overall_rating. 
# Claramente, las columnas con valores nulos en player_stats están relacionadas, 
#pues coinciden con el número de valores nulos que presentan (837)

# Por otro lado, sí considero que valdría la pena eliminar las columnas con más de 837 valores nulos.


player_stats_drop_cols = list(player_stats_null_cols[player_stats_null_cols > 10000].index)
player_stats = player_stats.drop(player_stats_drop_cols, axis=1)

In [92]:
# Reemplazar los valores nulos que están relacionados por ceros en la tabla player_stats

player_stats[['overall_rating', 'potential', 'preferred_foot', 'defensive_work_rate', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'dribbling', 'free_kick_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'reactions', 'shot_power', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'penalties', 'marking', 'standing_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes']] = player_stats[['overall_rating', 'potential', 'preferred_foot', 'defensive_work_rate', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'dribbling', 'free_kick_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'reactions', 'shot_power', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'penalties', 'marking', 'standing_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes']].fillna(0)

KeyError: "['overall_rating', 'defensive_work_rate', 'preferred_foot'] not in index"

In [53]:
# Step 6: Remover las columnas con poca varianza en player_stats

player_stats_low_variance = []

for col in player_stats._get_numeric_data():
    minimum = min(player_stats[col])
    ninety_perc = np.percentile(player_stats[col], 90)
    if ninety_perc == minimum:
        player_stats_low_variance.append(col)
#print(player_stats_low_variance)

player_stats = player_stats.drop(player_stats_low_variance, axis=1)

C:\Users\Dell\Anaconda3\lib\site-packages\numpy\lib\function_base.py:3826: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)

In [57]:
# Step 7: Manipulación de Texto tabla player_stats
player_stats.head(5)

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,49.0,medium,right,medium,71.0,67.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,49.0,medium,right,medium,71.0,67.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,49.0,medium,right,medium,66.0,62.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,48.0,medium,right,medium,65.0,61.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,48.0,medium,right,medium,65.0,61.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0

In [58]:
# Step 8: Renombrar columnas en player_stats

player_stats = player_stats.rename(columns={'overall_rating':'Calificación General', 'preferred_foot':'Pie', 'attacking_work_rate': 'Calificación en Ataque', 'defensive_work_rate': 'Calificación en Defensa'})

In [67]:
cal_def_count = player_stats['Calificación en Ataque']
cal_def_count.value_counts()

medium    125070
high       42823
low         8569
None        3639
norm         348
y            106
le           104
stoc          89
Name: Calificación en Ataque, dtype: int64

In [87]:
# Step 9: Filtering Records tabla player_stats

# Queremos obtener un dataframe de los jugadores con un potencial alto, cuya calificación en ataque sea de categoría alta
# que sean zurdos y cuya calificación en defensa sea mayor a 70.

player_stats_filtered = player_stats[(player_stats['potential']=='high') & 
                (player_stats['Calificación en Ataque']=='high') & 
                (player_stats['Pie']=='left') & (player_stats['Calificación en Defensa']>= 70.0)]

player_stats_filtered.head()

# Nota: podríamos ser más específicos con esta tabla filtrada y remover los outliers, pero no lo consideré
# necesario porque justamente al analizar los datos de los jugadores, quienes más nos interesan son precisamente los 
# outliers (i.e, los más destacados)

,id,player_fifa_api_id,player_api_id,date,Calificación General,potential,Pie,Calificación en Ataque,Calificación en Defensa,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
1277,1278,206161,293235,2016-04-21 00:00:00,73.0,high,left,high,78.0,73.0,...,59.0,48.0,69.0,73.0,73.0,10.0,11.0,6.0,13.0,13.0
1278,1279,206161,293235,2016-02-18 00:00:00,73.0,high,left,high,78.0,73.0,...,59.0,48.0,69.0,73.0,73.0,10.0,11.0,6.0,13.0,13.0
1279,1280,206161,293235,2016-02-11 00:00:00,73.0,high,left,high,76.0,71.0,...,59.0,48.0,69.0,73.0,73.0,10.0,11.0,6.0,13.0,13.0
1280,1281,206161,293235,2016-01-14 00:00:00,73.0,high,left,high,76.0,71.0,...,59.0,48.0,69.0,73.0,73.0,10.0,11.0,6.0,13.0,13.0
1281,1282,206161,293235,2015-11-12 00:00:00,73.0,high,left,high,78.0,71.0,...,59.0,48.0,69.0,73.0,73.0,10.0,11.0,6.0,13.0,13.0

In [83]:
# Step 10: Binning Numeric Variables tabla player_stats

# Podemos notar que en la tabla player_stats no hay consistencia entre la 'Calificación en Ataque'
# y la 'Calificación en Defensa', ya que la primera presenta datos de tipo categórico y la segunda de 
# tipo numérico. 

# Por ello, vamos a crear variables de tipo categórico para la 'Calificación en Defensa'. 

# El 'corte' para definir dichas categorías, lo vamos a definir utilizando un criterio de percentiles. 
# Menor a percentil 50 = low, entre p50 y p80 = medium, mayor a p80 = high. 

fifty_perc = int(np.percentile(player_stats['Calificación en Defensa'], 50))
sevfive_perc = int(np.percentile(player_stats['Calificación en Defensa'], 80))

print(fifty_perc)
print(sevfive_perc)

cutoffs = [0,74,79,100]

cal_def_labels = ['low', 'medium', 'high']
categorical_cal_def = pd.cut(player_stats['Calificación en Defensa'],cutoffs, labels=cal_def_labels)
categorical_cal_def.head(20)

74
79

0        low
1        low
2        low
3        low
4        low
5     medium
6     medium
7     medium
8     medium
9     medium
10    medium
11    medium
12    medium
13    medium
14    medium
15    medium
16    medium
17    medium
18    medium
19    medium
Name: Calificación en Defensa, dtype: category
Categories (3, object): [low < medium < high]

In [85]:
# Step 11: One-Hot Encoding Categorical Variables

# Asimismo, podemos crear un dataframe de variables dummy con el atributo 'Calificación en Ataque' para la tabla player_stats:

cal_ataque = pd.get_dummies(player_stats['Calificación en Ataque'])
cal_ataque.head(20)

    None  high  le  low  medium  norm  stoc  y
0      0     0   0    0       1     0     0  0
1      0     0   0    0       1     0     0  0
2      0     0   0    0       1     0     0  0
3      0     0   0    0       1     0     0  0
4      0     0   0    0       1     0     0  0
5      0     1   0    0       0     0     0  0
6      0     1   0    0       0     0     0  0
7      0     1   0    0       0     0     0  0
8      0     1   0    0       0     0     0  0
9      0     1   0    0       0     0     0  0
10     0     1   0    0       0     0     0  0
11     0     1   0    0       0     0     0  0
12     0     0   0    0       1     0     0  0
13     0     0   0    0       1     0     0  0
14     0     0   0    0       1     0     0  0
15     0     0   0    0       1     0     0  0
16     0     0   0    0       1     0     0  0
17     0     0   0    0       1     0     0  0
18     0     0   0    0       1     0     0  0
19     0     0   0    0       1     0     0  0

In [113]:
# Estadñistica Descriptiva 

player_stats.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
id,183978.0,91989.500000,53110.018250,1.0,45995.25,91989.5,137983.75,183978.0
player_fifa_api_id,183978.0,165671.524291,53851.094769,2.0,155798.00,183488.0,199848.00,234141.0
player_api_id,183978.0,135900.617324,136927.840510,2625.0,34763.00,77741.0,191080.00,750584.0
overall_rating,183142.0,68.600015,7.041139,33.0,64.00,69.0,73.00,94.0
potential,183142.0,73.460353,6.592271,39.0,69.00,74.0,78.00,97.0
crossing,183142.0,55.086883,17.242135,1.0,45.00,59.0,68.00,95.0
finishing,183142.0,49.921078,19.038705,1.0,34.00,53.0,65.00,97.0
heading_accuracy,183142.0,57.266023,16.488905,1.0,49.00,60.0,68.00,98.0
short_passing,183142.0,62.429672,14.194068,3.0,57.00,65.0,72.00,97.0
volleys,181265.0,49.468436,18.256618,1.0,35.00,52.0,64.00,93.0
dribbling,183142.0,59.175154,17.744688,1.0,52.00,64.0,72.00,97.0
curve,181265.0,52.965675,18.255788,2.0,41.00,56.0,67.00,94.0
free_kick_accuracy,183142.0,49.380950,17.831746,1.0,36.00,50.0,63.00,97.0
long_passing,183142.0,57.069880,14.394464,3.0,49.00,59.0,67.00,97.0
ball_control,183142.0,63.388879,15.196671,5.0,58.00,67.0,73.00,97.0
acceleration,183142.0,67.659357,12.983326,10.0,61.00,69.0,77.00,97.0
sprint_speed,183142.0,68.051244,12.569721,12.0,62.00,69.0,77.00,97.0
agility,181265.0,65.970910,12.954585,11.0,58.00,68.0,75.00,96.0
reactions,183142.0,66.103706,9.155408,17.0,61.00,67.0,72.00,96.0
balance,181265.0,65.189496,13.063188,12.0,58.00,67.0,74.00,96.0
shot_power,183142.0,61.808427,16.135143,2.0,54.00,65.0,73.00,97.0
jumping,181265.0,66.969045,11.006734,14.0,60.00,68.0,74.00,96.0
stamina,183142.0,67.038544,13.165262,10.0,61.00,69.0,76.00,96.0
strength,183142.0,67.424529,12.072280,10.0,60.00,69.0,76.00,96.0
long_shots,183142.0,53.339431,18.367025,1.0,41.00,58.0,67.00,96.0
aggression,183142.0,60.948046,16.089521,6.0,51.00,64.0,73.00,97.0
interceptions,183142.0,52.009271,19.450133,1.0,34.00,57.0,68.00,96.0
positioning,183142.0,55.786504,18.448292,2.0,45.00,60.0,69.00,96.0
vision,181265.0,57.873550,15.144086,1.0,49.00,60.0,69.00,97.0
penalties,183142.0,55.003986,15.546519,2.0,45.00,57.0,67.00,96.0
marking,183142.0,46.772242,21.227667,1.0,25.00,50.0,66.00,96.0
standing_tackle,183142.0,50.351257,21.483706,1.0,29.00,56.0,69.00,95.0
sliding_tackle,181265.0,48.001462,21.598778,2.0,25.00,53.0,67.00,95.0
gk_diving,183142.0,14.704393,16.865467,1.0,7.00,10.0,13.00,94.0
gk_handling,183142.0,16.063612,15.867382,1.0,8.00,11.0,15.00,93.0
gk_kicking,183142.0,20.998362,21.452980,1.0,8.00,12.0,15.00,97.0
gk_positioning,183142.0,16.132154,16.099175,1.0,8.00,11.0,15.00,96.0
gk_reflexes,183142.0,16.441439,17.198155,1.0,8.00,11.0,15.00,96.0

In [44]:
# Análisis respecto a la tabla matches (llevaremos a cabo una serie de pasos similares a los llevados a cabo con la tabla player_stats) 

# podemos observar que los valores nulos se pueden asignar en dos grandes grupos: 
# 1) aquellos referentes a la posición del jugadore dentro del campo (home_away_x1, home_player_x2... etc)
# 2) aquellos referentes a los momios del partido que analizan las distintas casas de apuestas... 

# he decidido eliminar todas las columnas referentes al primer grupo. 

matches_drop_cols = list(matches_null_cols[matches_null_cols < 2000].index)
matches = matches.drop(matches_drop_cols, axis=1)

In [52]:
# Reemplazar los valores nulos que están relacionados por ceros en la tabla matches
matches[['B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'SJH', 'SJD', 'SJA', 'VCH', 'VCD', 'VCA', 'GBH', 'GBD', 'GBA', 'BSH', 'BSD', 'BSA']] = matches[['B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'SJH', 'SJD', 'SJA', 'VCH', 'VCD', 'VCA', 'GBH', 'GBD', 'GBA', 'BSH', 'BSD', 'BSA']].fillna(0)

In [54]:
# Remover las columnas con poca varianza en matches

matches_low_variance = []

for col in matches._get_numeric_data():
    minimum = min(matches[col])
    ninety_perc = np.percentile(matches[col], 90)
    if ninety_perc == minimum:
        matches_low_variance.append(col)
#print(matches_low_variance)

matches = matches.drop(matches_low_variance, axis=1)

In [59]:
# Manipulación de Texto tabla matches
matches.head(5)

,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,None,None,None,None,None,None,None,None,1.73,3.40,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,None,None,None,None,None,None,None,None,1.95,3.20,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,None,None,None,None,None,None,None,None,2.38,3.30,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,None,None,None,None,None,None,None,None,1.44,3.75,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,None,None,None,None,None,None,None,None,5.00,3.50,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67

In [61]:
# Renombrar columnas en matches
# Vamos a poner bien los nombres completos de las casas de apuestas que aparecen en la tabla matches:

matches = matches.rename(columns={'B365H' : 'Bet365 home win odds', 'B365D' : 'Bet365 draw odds', 'B365A' : 'Bet365 away win odds', 'BSH' : 'Blue Square home win odds', 'BSD' : 'Blue Square draw odds', 'BSA' : 'Blue Square away win odds', 'BWD' : 'Bet&Win draw odds', 
'BWA' : 'Bet&Win away win odds', 'GBH' : 'Gamebookers home win odds', 'GBD' : 'Gamebookers draw odds', 'GBA' : 'Gamebookers away win odds', 'IWH' : 'Interwetten home win odds', 'IWD' : 'Interwetten draw odd'})

In [88]:
# Step 12: Export Data to CVS files. 
player_stats.to_csv('player_stats.csv', index=False)
matches.to_csv('matches.csv', index=False)

In [ ]:
# Aditional Improves to be made: 

# Merge match_data and league_data in order to replace league_id with league name.
# Merge match_data and team_data in order to replace team_id with team name.

# Create new Tables (goal_sum = sum of goal scored in each match, goal_diff = difference between goals scored by the two team)