In [1]:
import pandas as pd

In [4]:
batting = pd.read_csv("batting.csv")
batting.head()

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,abercda01,1871,1,TRO,NaN,1,4,0,0,0,...,0.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,0.0
1,addybo01,1871,1,RC1,NaN,25,118,30,32,6,...,13.0,8.0,1.0,4,0.0,NaN,NaN,NaN,NaN,0.0
2,allisar01,1871,1,CL1,NaN,29,137,28,40,4,...,19.0,3.0,1.0,2,5.0,NaN,NaN,NaN,NaN,1.0
3,allisdo01,1871,1,WS3,NaN,27,133,28,44,10,...,27.0,1.0,1.0,0,2.0,NaN,NaN,NaN,NaN,0.0
4,ansonca01,1871,1,RC1,NaN,25,120,29,39,11,...,16.0,6.0,2.0,2,1.0,NaN,NaN,NaN,NaN,0.0

In [13]:
batting

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,abercda01,1871,1,TRO,0,1,4,0,0,0,...,0.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,0.0
1,addybo01,1871,1,RC1,0,25,118,30,32,6,...,13.0,8.0,1.0,4,0.0,NaN,NaN,NaN,NaN,0.0
2,allisar01,1871,1,CL1,0,29,137,28,40,4,...,19.0,3.0,1.0,2,5.0,NaN,NaN,NaN,NaN,1.0
3,allisdo01,1871,1,WS3,0,27,133,28,44,10,...,27.0,1.0,1.0,0,2.0,NaN,NaN,NaN,NaN,0.0
4,ansonca01,1871,1,RC1,0,25,120,29,39,11,...,16.0,6.0,2.0,2,1.0,NaN,NaN,NaN,NaN,0.0
5,armstbo01,1871,1,FW1,0,12,49,9,11,2,...,5.0,0.0,1.0,0,1.0,NaN,NaN,NaN,NaN,0.0
6,barkeal01,1871,1,RC1,0,1,4,0,1,0,...,2.0,0.0,0.0,1,0.0,NaN,NaN,NaN,NaN,0.0
7,barnero01,1871,1,BS1,0,31,157,66,63,10,...,34.0,11.0,6.0,13,1.0,NaN,NaN,NaN,NaN,1.0
8,barrebi01,1871,1,FW1,0,1,5,1,1,1,...,1.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,0.0
9,barrofr01,1871,1,BS1,0,18,86,13,13,2,...,11.0,1.0,0.0,0,0.0,NaN,NaN,NaN,NaN,0.0
10,bassjo01,1871,1,CL1,0,22,89,18,27,1,...,18.0,0.0,1.0,3,4.0,NaN,NaN,NaN,NaN,0.0
11,battijo01,1871,1,CL1,0,1,3,0,0,0,...,0.0,0.0,0.0,1,0.0,NaN,NaN,NaN,NaN,0.0
12,bealsto01,1871,1,WS3,0,10,36,6,7,0,...,1.0,2.0,0.0,2,0.0,NaN,NaN,NaN,NaN,2.0
13,beaveed01,1871,1,TRO,0,3,15,7,6,0,...,5.0,2.0,0.0,0,0.0,NaN,NaN,NaN,NaN,0.0
14,bechtge01,1871,1,PH1,0,20,94,24,33,9,...,21.0,4.0,0.0,2,2.0,NaN,NaN,NaN,NaN,1.0
15,bellast01,1871,1,TRO,0,29,128,26,32,3,...,23.0,4.0,4.0,9,2.0,NaN,NaN,NaN,NaN,2.0
16,berkena01,1871,1,PH1,0,1,4,0,0,0,...,0.0,0.0,0.0,0,3.0,NaN,NaN,NaN,NaN,0.0
17,berryto01,1871,1,PH1,0,1,4,0,1,0,...,0.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,0.0
18,berthha01,1871,1,WS3,0,17,73,17,17,1,...,8.0,3.0,1.0,4,2.0,NaN,NaN,NaN,NaN,0.0
19,biermch01,1871,1,FW1,0,1,2,0,0,0,...,0.0,0.0,0.0,1,0.0,NaN,NaN,NaN,NaN,0.0
20,birdge01,1871,1,RC1,0,25,106,19,28,2,...,13.0,1.0,0.0,3,2.0,NaN,NaN,NaN,NaN,3.0
21,birdsda01,1871,1,BS1,0,29,152,51,46,3,...,24.0,6.0,0.0,4,4.0,NaN,NaN,NaN,NaN,1.0
22,brainas01,1871,1,WS3,0,30,134,24,30,4,...,21.0,4.0,0.0,7,2.0,NaN,NaN,NaN,NaN,1.0
23,brannmi01,1871,1,CH1,0,3,14,2,1,0,...,0.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,0.0
24,burrohe01,1871,1,WS3,0,12,63,11,15,2,...,14.0,0.0,0.0,1,1.0,NaN,NaN,NaN,NaN,0.0
25,careyto01,1871,1,FW1,0,19,87,16,20,2,...,10.0,5.0,0.0,2,1.0,NaN,NaN,NaN,NaN,0.0
26,carleji01,1871,1,CL1,0,29,127,31,32,8,...,18.0,2.0,1.0,8,3.0,NaN,NaN,NaN,NaN,3.0
27,conefr01,1871,1,BS1,0,19,77,17,20,3,...,16.0,12.0,1.0,8,2.0,NaN,NaN,NaN,NaN,1.0
28,connone01,1871,1,TRO,0,7,33,6,7,0,...,2.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,0.0
29,cravebi01,1871,1,TRO,0,27,118,26,38,8,...,26.0,6.0,3.0,3,0.0,NaN,NaN,NaN,NaN,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105831,wittgni01,2018,1,MIA,NL,32,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105832,wolteto01,2018,1,COL,NL,74,182,19,31,4,...,27.0,2.0,0.0,26,33.0,2.0,6.0,0.0,2.0,6.0
105833,wongko01,2018,1,SLN,NL,127,353,41,88,18,...,38.0,6.0,5.0,31,60.0,3.0,14.0,6.0,3.0,6.0
105834,woodal02,2018,1,LAN,NL,33,44,1,2,0,...,0.0,1.0,0.0,0,25.0,0.0,0.0,6.0,0.0,0.0
105835,woodbl01,2018,1,LAA,AL,13,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105836,woodhu01,2018,1,TBA,AL,31,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105837,woodrbr01,2018,1,MIL,NL,19,8,2,2,0,...,1.0,0.0,0.0,1,1.0,0.0,0.0,1.0,0.0,1.0
105838,workmbr01,2018,1,BOS,AL,43,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105839,wrighda03,2018,1,NYN,NL,2,2,0,0,0,...,0.0,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0
105840,wrighky01,2018,1,ATL,NL,4,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105841,wrighmi01,2018,1,BAL,AL,48,1,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105842,wrighst01,2018,1,BOS,AL,20,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105843,wynnsau01,2018,1,BAL,AL,42,110,16,28,2,...,11.0,0.0,0.0,5,25.0,0.0,0.0,3.0,0.0,7.0
105844,yacabji01,2018,1,BAL,AL,12,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105845,yarbrry01,2018,1,TBA,AL,38,3,0,0,0,...,0.0,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0
105846,yateski01,2018,1,SDN,NL,65,2,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105847,yelicch01,2018,1,MIL,NL,147,574,118,187,34,...,110.0,22.0,4.0,68,135.0,2.0,7.0,0.0,2.0,14.0
105848,youngch04,2018,1,LAA,AL,56,113,17,19,2,...,13.0,2.0,0.0,11,37.0,0.0,2.0,1.0,1.0,1.0
105849,younger03,2018,1,LAA,AL,41,109,12,22,4,...,8.0,5.0,1.0,6,28.0,0.0,1.0,0.0,1.0,4.0
105850,zagunma01,2018,1,CHN,NL,5,5,0,2,1,...,1.0,0.0,0.0,1,1.0,0.0,0.0,0.0,0.0,0.0
105851,zagurmi01,2018,1,MIL,NL,2,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105852,zamorda01,2018,1,NYN,NL,16,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105853,zastrro01,2018,1,CHN,NL,6,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105854,zieglbr01,2018,1,MIA,NL,53,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105855,zieglbr01,2018,2,ARI,NL,29,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105856,zimmebr01,2018,1,CLE,AL,34,106,14,24,5,...,9.0,4.0,1.0,7,44.0,0.0,1.0,0.0,0.0,1.0
105857,zimmejo02,2018,1,DET,AL,25,2,0,0,0,...,0.0,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0
105858,zimmery01,2018,1,WAS,NL,85,288,33,76,21,...,51.0,1.0,1.0,30,55.0,1.0,3.0,0.0,2.0,10.0
105859,zobribe01,2018,1,CHN,NL,139,455,67,139,28,...,58.0,3.0,4.0,55,60.0,1.0,2.0,1.0,7.0,8.0
105860,zuninmi01,2018,1,SEA,AL,113,373,37,75,18,...,44.0,0.0,0.0,24,150.0,0.0,6.0,0.0,2.0,7.0

In [12]:
#cambie el NaN por 0 para poder distinguir numericamente que datos eran antes de la formcion de las ligas y poder eliminar esa informaciÃ³n
batting[["lgID"]] = batting[["lgID"]].fillna(0)

In [20]:
indices_s_liga = []
for x, y in enumerate(batting["lgID"]):
    if y == 0:
        indices_s_liga.append(x)
indices_s_liga

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737]

In [17]:
antes_de_ligas = batting["lgID"] == 0
antes_de_ligas

0          True
1          True
2          True
3          True
4          True
5          True
6          True
7          True
8          True
9          True
10         True
11         True
12         True
13         True
14         True
15         True
16         True
17         True
18         True
19         True
20         True
21         True
22         True
23         True
24         True
25         True
26         True
27         True
28         True
29         True
          ...
105831    False
105832    False
105833    False
105834    False
105835    False
105836    False
105837    False
105838    False
105839    False
105840    False
105841    False
105842    False
105843    False
105844    False
105845    False
105846    False
105847    False
105848    False
105849    False
105850    False
105851    False
105852    False
105853    False
105854    False
105855    False
105856    False
105857    False
105858    False
105859    False
105860    False
Name: lgID, Length: 105861, dtype: bool

In [21]:
#eliminamos las filas que fueran antes de 1876 que fue el primer aÃ±o de la mlb
batting.drop(indices_s_liga, axis=0)

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
738,addybo01,1876,1,CHN,NL,32,142,36,40,4,...,16.0,NaN,NaN,5,0.0,NaN,NaN,NaN,NaN,NaN
739,allisar01,1876,1,LS1,NL,31,130,9,27,2,...,10.0,NaN,NaN,2,6.0,NaN,NaN,NaN,NaN,NaN
740,allisdo01,1876,1,HAR,NL,44,163,19,43,4,...,15.0,NaN,NaN,3,9.0,NaN,NaN,NaN,NaN,NaN
741,andrufr01,1876,1,CHN,NL,8,36,6,11,3,...,2.0,NaN,NaN,0,5.0,NaN,NaN,NaN,NaN,NaN
742,ansonca01,1876,1,CHN,NL,66,309,63,110,9,...,59.0,NaN,NaN,12,8.0,NaN,NaN,NaN,NaN,NaN
743,barnero01,1876,1,CHN,NL,66,322,126,138,21,...,59.0,NaN,NaN,20,8.0,NaN,NaN,NaN,NaN,NaN
744,battijo01,1876,1,SL3,NL,64,283,34,85,11,...,46.0,NaN,NaN,6,6.0,NaN,NaN,NaN,NaN,NaN
745,bechtge01,1876,1,LS1,NL,14,55,2,10,1,...,2.0,NaN,NaN,0,1.0,NaN,NaN,NaN,NaN,NaN
746,bechtge01,1876,2,NY3,NL,2,10,2,3,0,...,0.0,NaN,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN
747,berghjo01,1876,1,PHN,NL,1,4,0,0,0,...,0.0,NaN,NaN,0,2.0,NaN,NaN,NaN,NaN,NaN
748,bielaos01,1876,1,CHN,NL,32,139,24,29,3,...,10.0,NaN,NaN,2,3.0,NaN,NaN,NaN,NaN,NaN
749,blongjo01,1876,1,SL3,NL,62,264,30,62,7,...,30.0,NaN,NaN,2,9.0,NaN,NaN,NaN,NaN,NaN
750,bondto01,1876,1,HAR,NL,45,182,18,50,8,...,21.0,NaN,NaN,0,4.0,NaN,NaN,NaN,NaN,NaN
751,bootham01,1876,1,CN1,NL,63,272,31,71,3,...,14.0,NaN,NaN,9,11.0,NaN,NaN,NaN,NaN,NaN
752,boothed01,1876,1,NY3,NL,57,228,17,49,2,...,7.0,NaN,NaN,2,4.0,NaN,NaN,NaN,NaN,NaN
753,bordejo01,1876,1,BSN,NL,32,121,19,25,3,...,7.0,NaN,NaN,3,3.0,NaN,NaN,NaN,NaN,NaN
754,bradlfo01,1876,1,BSN,NL,22,82,12,19,2,...,8.0,NaN,NaN,2,3.0,NaN,NaN,NaN,NaN,NaN
755,bradlge01,1876,1,SL3,NL,64,265,29,66,7,...,28.0,NaN,NaN,3,12.0,NaN,NaN,NaN,NaN,NaN
756,brownle01,1876,1,BSN,NL,45,195,23,41,6,...,21.0,NaN,NaN,3,22.0,NaN,NaN,NaN,NaN,NaN
757,burdoja01,1876,1,HAR,NL,69,309,66,80,9,...,23.0,NaN,NaN,13,16.0,NaN,NaN,NaN,NaN,NaN
758,bushodo01,1876,1,PHN,NL,5,21,4,1,0,...,1.0,NaN,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN
759,carbijo01,1876,1,LS1,NL,7,25,3,4,0,...,1.0,NaN,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN
760,careyto01,1876,1,HAR,NL,68,289,51,78,7,...,26.0,NaN,NaN,3,4.0,NaN,NaN,NaN,NaN,NaN
761,cassijo01,1876,1,HAR,NL,12,47,6,13,2,...,8.0,NaN,NaN,1,0.0,NaN,NaN,NaN,NaN,NaN
762,chapmja01,1876,1,LS1,NL,17,67,4,16,1,...,5.0,NaN,NaN,1,3.0,NaN,NaN,NaN,NaN,NaN
763,clackbo01,1876,1,CN1,NL,32,118,10,19,0,...,5.0,NaN,NaN,5,12.0,NaN,NaN,NaN,NaN,NaN
764,clappjo01,1876,1,SL3,NL,64,298,60,91,4,...,29.0,NaN,NaN,8,2.0,NaN,NaN,NaN,NaN,NaN
765,clintji01,1876,1,LS1,NL,16,65,8,22,2,...,0.0,NaN,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN
766,collida01,1876,1,LS1,NL,7,28,3,4,1,...,9.0,NaN,NaN,0,2.0,NaN,NaN,NaN,NaN,NaN
767,coonwi01,1876,1,PHN,NL,54,220,30,50,5,...,22.0,NaN,NaN,2,4.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105831,wittgni01,2018,1,MIA,NL,32,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105832,wolteto01,2018,1,COL,NL,74,182,19,31,4,...,27.0,2.0,0.0,26,33.0,2.0,6.0,0.0,2.0,6.0
105833,wongko01,2018,1,SLN,NL,127,353,41,88,18,...,38.0,6.0,5.0,31,60.0,3.0,14.0,6.0,3.0,6.0
105834,woodal02,2018,1,LAN,NL,33,44,1,2,0,...,0.0,1.0,0.0,0,25.0,0.0,0.0,6.0,0.0,0.0
105835,woodbl01,2018,1,LAA,AL,13,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105836,woodhu01,2018,1,TBA,AL,31,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105837,woodrbr01,2018,1,MIL,NL,19,8,2,2,0,...,1.0,0.0,0.0,1,1.0,0.0,0.0,1.0,0.0,1.0
105838,workmbr01,2018,1,BOS,AL,43,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105839,wrighda03,2018,1,NYN,NL,2,2,0,0,0,...,0.0,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0
105840,wrighky01,2018,1,ATL,NL,4,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105841,wrighmi01,2018,1,BAL,AL,48,1,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105842,wrighst01,2018,1,BOS,AL,20,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105843,wynnsau01,2018,1,BAL,AL,42,110,16,28,2,...,11.0,0.0,0.0,5,25.0,0.0,0.0,3.0,0.0,7.0
105844,yacabji01,2018,1,BAL,AL,12,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105845,yarbrry01,2018,1,TBA,AL,38,3,0,0,0,...,0.0,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0
105846,yateski01,2018,1,SDN,NL,65,2,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105847,yelicch01,2018,1,MIL,NL,147,574,118,187,34,...,110.0,22.0,4.0,68,135.0,2.0,7.0,0.0,2.0,14.0
105848,youngch04,2018,1,LAA,AL,56,113,17,19,2,...,13.0,2.0,0.0,11,37.0,0.0,2.0,1.0,1.0,1.0
105849,younger03,2018,1,LAA,AL,41,109,12,22,4,...,8.0,5.0,1.0,6,28.0,0.0,1.0,0.0,1.0,4.0
105850,zagunma01,2018,1,CHN,NL,5,5,0,2,1,...,1.0,0.0,0.0,1,1.0,0.0,0.0,0.0,0.0,0.0
105851,zagurmi01,2018,1,MIL,NL,2,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105852,zamorda01,2018,1,NYN,NL,16,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105853,zastrro01,2018,1,CHN,NL,6,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105854,zieglbr01,2018,1,MIA,NL,53,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105855,zieglbr01,2018,2,ARI,NL,29,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105856,zimmebr01,2018,1,CLE,AL,34,106,14,24,5,...,9.0,4.0,1.0,7,44.0,0.0,1.0,0.0,0.0,1.0
105857,zimmejo02,2018,1,DET,AL,25,2,0,0,0,...,0.0,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0
105858,zimmery01,2018,1,WAS,NL,85,288,33,76,21,...,51.0,1.0,1.0,30,55.0,1.0,3.0,0.0,2.0,10.0
105859,zobribe01,2018,1,CHN,NL,139,455,67,139,28,...,58.0,3.0,4.0,55,60.0,1.0,2.0,1.0,7.0,8.0
105860,zuninmi01,2018,1,SEA,AL,113,373,37,75,18,...,44.0,0.0,0.0,24,150.0,0.0,6.0,0.0,2.0,7.0

In [22]:
#importamos el otro archivo donde vienen los nombres y mas informaciÃ³n por jugador
people = pd.read_csv("People.csv")
people.head()

,playerID,birthYear,birthMonth,birthDay,birthCountry,birthState,birthCity,deathYear,deathMonth,deathDay,...,nameLast,nameGiven,weight,height,bats,throws,debut,finalGame,retroID,bbrefID
0,aardsda01,1981.0,12.0,27.0,USA,CO,Denver,NaN,NaN,NaN,...,Aardsma,David Allan,215.0,75.0,R,R,2004-04-06,2015-08-23,aardd001,aardsda01
1,aaronha01,1934.0,2.0,5.0,USA,AL,Mobile,NaN,NaN,NaN,...,Aaron,Henry Louis,180.0,72.0,R,R,1954-04-13,1976-10-03,aaroh101,aaronha01
2,aaronto01,1939.0,8.0,5.0,USA,AL,Mobile,1984.0,8.0,16.0,...,Aaron,Tommie Lee,190.0,75.0,R,R,1962-04-10,1971-09-26,aarot101,aaronto01
3,aasedo01,1954.0,9.0,8.0,USA,CA,Orange,NaN,NaN,NaN,...,Aase,Donald William,190.0,75.0,R,R,1977-07-26,1990-10-03,aased001,aasedo01
4,abadan01,1972.0,8.0,25.0,USA,FL,Palm Beach,NaN,NaN,NaN,...,Abad,Fausto Andres,184.0,73.0,L,L,2001-09-10,2006-04-13,abada001,abadan01

In [24]:
people.columns

Index(['playerID', 'birthYear', 'birthMonth', 'birthDay', 'birthCountry',
       'birthState', 'birthCity', 'deathYear', 'deathMonth', 'deathDay',
       'deathCountry', 'deathState', 'deathCity', 'nameFirst', 'nameLast',
       'nameGiven', 'weight', 'height', 'bats', 'throws', 'debut', 'finalGame',
       'retroID', 'bbrefID'],
      dtype='object')

In [57]:
names = people[["playerID", "nameFirst", "nameLast", "bats", "debut", "finalGame"]]

In [58]:
names.head()

    playerID nameFirst nameLast bats       debut   finalGame
0  aardsda01     David  Aardsma    R  2004-04-06  2015-08-23
1  aaronha01      Hank    Aaron    R  1954-04-13  1976-10-03
2  aaronto01    Tommie    Aaron    R  1962-04-10  1971-09-26
3   aasedo01       Don     Aase    R  1977-07-26  1990-10-03
4   abadan01      Andy     Abad    L  2001-09-10  2006-04-13

In [59]:
#unimos names y batting apra que aparezca el nombre de cada jugador y no solo su id
#ademas de agregarle las columnas de debut, finalGame y bat para distinguir de si bateaba con la izquierda o derecha
allbatting = pd.merge(names, batting, on='playerID')
allbatting.head(10)

,playerID,nameFirst,nameLast,bats,debut,finalGame,yearID,stint,teamID,lgID,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2004,1,SFN,NL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2006,1,CHN,NL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0
2,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2007,1,CHA,AL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2008,1,BOS,AL,...,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
4,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2009,1,SEA,AL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
5,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2010,1,SEA,AL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
6,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2012,1,NYA,AL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
7,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2013,1,NYN,NL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
8,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2015,1,ATL,NL,...,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
9,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1954,1,ML1,NL,...,69.0,2.0,2.0,28,39.0,NaN,3.0,6.0,4.0,13.0

In [60]:
allbatting.columns

Index(['playerID', 'nameFirst', 'nameLast', 'bats', 'debut', 'finalGame',
       'yearID', 'stint', 'teamID', 'lgID', 'G', 'AB', 'R', 'H', '2B', '3B',
       'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'IBB', 'HBP', 'SH', 'SF', 'GIDP'],
      dtype='object')

In [61]:
#ejemplo para ver la "tarjeta" del jugdor
allbatting.iloc[9]

playerID      aaronha01
nameFirst          Hank
nameLast          Aaron
bats                  R
debut        1954-04-13
finalGame    1976-10-03
yearID             1954
stint                 1
teamID              ML1
lgID                 NL
G                   122
AB                  468
R                    58
H                   131
2B                   27
3B                    6
HR                   13
RBI                  69
SB                    2
CS                    2
BB                   28
SO                   39
IBB                 NaN
HBP                   3
SH                    6
SF                    4
GIDP                 13
Name: 9, dtype: object

In [62]:
#vemos que columnas tienen Null values
leage = allbatting.isnull().sum()

In [63]:
leage

playerID         0
nameFirst       38
nameLast         0
bats          1926
debut            9
finalGame        9
yearID           0
stint            0
teamID           0
lgID             0
G                0
AB               0
R                0
H                0
2B               0
3B               0
HR               0
RBI            756
SB            2368
CS           23541
BB               0
SO            2100
IBB          36651
HBP           2817
SH            6069
SF           36104
GIDP         25441
dtype: int64

In [87]:
#remplacamos Nan por 0 en los valores de debut y final game que no tengan debut ni final game porque no nos traen informacion nueva o relevante
allbatting[["debut", "finalGame"]] = allbatting[["debut", "finalGame"]].fillna(0)

In [ ]:
#hice lo mismo con las columas de valores numericos
allbatting[["RBI", "SB", "CS", "SO", "IBB", "HBP", "SH", "SF", "GIDP"]] = allbatting[["RBI", "SB", "CS", "SO", "IBB", "HBP", "SH", "SF", "GIDP"]].fillna(0)

In [88]:
#volvemos a checar que columnas tienen null
leage1 = allbatting.isnull().sum()
leage1

playerID        0
nameFirst      38
nameLast        0
bats         1926
debut           0
finalGame       0
yearID          0
stint           0
teamID          0
lgID            0
G               0
AB              0
R               0
H               0
2B              0
3B              0
HR              0
RBI             0
SB              0
CS              0
BB              0
SO              0
IBB             0
HBP             0
SH              0
SF              0
GIDP            0
dtype: int64

In [73]:
#primero pense en rellenar los valores faltantes en la columna de bats con una estimacion tomando en cuenta 
#el porcentaje de bateadores derechos, izquierdos y ambidiestros del total, por eso hice esos pasos 
#sacamos una lista de cuantos bateadores lo hacian con la derecha y cuantos con la izquierda y cuantos con ambas
list_bats = list(allbatting["bats"])
batsl = []
batsb = []
batsr = []
batnan = []
for x, y in enumerate(list_bats):
        if y == "R":
            batsr.append(y)
        elif y == "L":
            batsl.append(y)
        elif y == "B":
            batsb.append(y)
        else:
            batnan.append(x)

In [74]:
#sacamos el total de bateadores de cada mano y comprobamos que la lista de valores nulos en la columna bats es 1926 igual que en la 
print(len(batsl))
print(len(batsr))
print(len(batsb))
print(len(batnan))

29379
66788
7768
1926

In [104]:
#sacamos la proporcion
total_bats = len(batsl) + len(batsr) + len(batsb) 
total_bats
propbr = len(batsr) / total_bats
propbl = len(batsl) / total_bats
propbb = len(batsb) / total_bats
print(propbb, propbl, propbr)
#con esto veriamos cuantos de los bateadores faltantes serian zurdos, cuantos derechos y cuantos ambos
batearianl = round(len(batnan) * propbl)
batearianr = round(len(batnan) * propbr)
batearianb = round(len(batnan) * propbb)
print(batearianb, batearianl, batearianr)
#pero al final no os meti porque estaria alterando la informaciÃ³n

0.0747390195795449 0.28266705152258625 0.6425939288978688
144 544 1238

In [89]:
#sacamos la lista de los indices que en debut tienen 0
list_deb = list(allbatting["debut"])
debnan = []

for x, y in enumerate(list_deb):
        if y == 0:
            debnan.append(x)

debnan

[20580, 34047, 45547, 62465, 62477, 89537, 91702, 92789, 105550]

In [141]:
#eliminamos las entradas de los nombres que no tienen debut ni juego final
allbatting2 = allbatting.drop(debnan, axis=0)

In [102]:
#importamos numpy para remplazar los valores nan por un guiÃ³n y asÃ­ no alterarlos datos de bats y de nameFirst
#tambien remplaze los nombres vacios en nameFirst por un guion para no dejar valores vacios 
import numpy as np
allbatting1 = allbatting.replace(np.nan, '-', regex=True)

In [161]:
#ninguna columna tiene null values
leage1 = allbatting.isnull().sum()
leage1

playerID     0
nameFirst    0
nameLast     0
bats         0
debut        0
finalGame    0
yearID       0
stint        0
teamID       0
lgID         0
G            0
AB           0
R            0
H            0
2B           0
3B           0
HR           0
RBI          0
SB           0
CS           0
BB           0
SO           0
IBB          0
HBP          0
SH           0
SF           0
GIDP         0
avgYear      0
dtype: int64

In [105]:

allbatting = allbatting1
allbatting

,playerID,nameFirst,nameLast,bats,debut,finalGame,yearID,stint,teamID,lgID,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2004,1,SFN,NL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2006,1,CHN,NL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0
2,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2007,1,CHA,AL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2008,1,BOS,AL,...,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
4,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2009,1,SEA,AL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
5,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2010,1,SEA,AL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
6,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2012,1,NYA,AL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
7,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2013,1,NYN,NL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
8,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2015,1,ATL,NL,...,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
9,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1954,1,ML1,NL,...,69.0,2.0,2.0,28,39.0,0.0,3.0,6.0,4.0,13.0
10,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1955,1,ML1,NL,...,106.0,3.0,1.0,49,61.0,5.0,3.0,7.0,4.0,20.0
11,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1956,1,ML1,NL,...,92.0,2.0,4.0,37,54.0,6.0,2.0,5.0,7.0,21.0
12,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1957,1,ML1,NL,...,132.0,1.0,1.0,57,58.0,15.0,0.0,0.0,3.0,13.0
13,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1958,1,ML1,NL,...,95.0,4.0,1.0,59,49.0,16.0,1.0,0.0,3.0,21.0
14,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1959,1,ML1,NL,...,123.0,8.0,0.0,51,54.0,17.0,4.0,0.0,9.0,19.0
15,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1960,1,ML1,NL,...,126.0,16.0,7.0,60,63.0,13.0,2.0,0.0,12.0,8.0
16,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1961,1,ML1,NL,...,120.0,21.0,9.0,56,64.0,20.0,2.0,1.0,9.0,16.0
17,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1962,1,ML1,NL,...,128.0,15.0,7.0,66,73.0,14.0,3.0,0.0,6.0,14.0
18,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1963,1,ML1,NL,...,130.0,31.0,5.0,78,94.0,18.0,0.0,0.0,5.0,11.0
19,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1964,1,ML1,NL,...,95.0,22.0,4.0,62,46.0,9.0,0.0,0.0,2.0,22.0
20,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1965,1,ML1,NL,...,89.0,24.0,4.0,60,81.0,10.0,1.0,0.0,8.0,15.0
21,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1966,1,ATL,NL,...,127.0,21.0,3.0,76,96.0,15.0,1.0,0.0,8.0,14.0
22,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1967,1,ATL,NL,...,109.0,17.0,6.0,63,97.0,19.0,0.0,0.0,6.0,11.0
23,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1968,1,ATL,NL,...,86.0,28.0,5.0,64,62.0,23.0,1.0,0.0,5.0,21.0
24,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1969,1,ATL,NL,...,97.0,9.0,10.0,87,47.0,19.0,2.0,0.0,3.0,14.0
25,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1970,1,ATL,NL,...,118.0,9.0,0.0,74,63.0,15.0,2.0,0.0,6.0,13.0
26,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1971,1,ATL,NL,...,118.0,1.0,1.0,71,58.0,21.0,2.0,0.0,5.0,9.0
27,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1972,1,ATL,NL,...,77.0,4.0,0.0,92,55.0,15.0,1.0,0.0,2.0,17.0
28,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1973,1,ATL,NL,...,96.0,1.0,1.0,68,51.0,13.0,1.0,0.0,4.0,7.0
29,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1974,1,ATL,NL,...,69.0,1.0,0.0,39,29.0,6.0,0.0,1.0,2.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105831,zupcibo01,Bob,Zupcic,R,1991-09-07,1994-08-04,1994,2,CHA,AL,...,8.0,0.0,0.0,4,16.0,0.0,0.0,4.0,1.0,2.0
105832,zupofr01,Frank,Zupo,L,1957-07-01,1961-05-09,1957,1,BAL,AL,...,0.0,0.0,0.0,1,4.0,0.0,0.0,0.0,0.0,0.0
105833,zupofr01,Frank,Zupo,L,1957-07-01,1961-05-09,1958,1,BAL,AL,...,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
105834,zupofr01,Frank,Zupo,L,1957-07-01,1961-05-09,1961,1,BAL,AL,...,0.0,0.0,0.0,1,1.0,0.0,0.0,0.0,0.0,0.0
105835,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1982,1,ATL,NL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105836,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1983,1,ATL,NL,...,0.0,0.0,0.0,2,1.0,0.0,1.0,0.0,0.0,0.0
105837,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1984,1,ATL,NL,...,1.0,0.0,0.0,2,3.0,0.0,0.0,0.0,0.0,0.0
105838,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1985,1,ATL,NL,...,4.0,2.0,0.0,16,14.0,1.0,0.0,4.0,0.0,3.0
105839,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1986,1,NYA,AL,...,2.0,0.0,0.0,5,4.0,0.0,0.0,4.0,0.0,1.0
105840,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1987,1,NYA,AL,...,0.0,0.0,0.0,0,4.0,0.0,0.0,2.0,0.0,1.0
105841,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1988,1,CLE,AL,...,7.0,0.0,0.0,8,13.0,0.0,0.0,8.0,0.0,3.0
105842,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1989,1,CLE,AL,...,6.0,0.0,0.0,1,11.0,0.0,1.0,0.0,0.0,0.0
105843,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1991,1,KCA,AL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105844,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1951,1,CLE,AL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105845,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1952,1,CLE,AL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105846,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1954,1,CIN,NL,...,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
105847,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1954,2,DET,AL,...,3.0,0.0,1.0,1,14.0,0.0,0.0,9.0,0.0,2.0
105848,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1955,1,DET,AL,...,0.0,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0
105849,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1955,2,BAL,AL,...,0.0,0.0,0.0,1,5.0,0.0,0.0,1.0,0.0,1.0
105850,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1956,1,BAL,AL,...,2.0,0.0,0.0,1,7.0,0.0,0.0,4.0,0.0,0.0
105851,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1957,1,BAL,AL,...,0.0,0.0,0.0,3,8.0,0.0,0.0,2.0,0.0,0.0
105852,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1958,1,BAL,AL,...,2.0,0.0,0.0,1,2.0,0.0,0.0,0.0,0.0,0.0
105853,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1959,1,BAL,AL,...,0.0,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0
105854,zwilldu01,Dutch,Zwilling,L,1910-08-14,1916-07-12,1910,1,CHA,AL,...,5.0,1.0,0.0,11,16.0,0.0,1.0,1.0,0.0,0.0
105855,zwilldu01,Dutch,Zwilling,L,1910-08-14,1916-07-12,1914,1,CHF,FL,...,95.0,21.0,0.0,46,68.0,0.0,1.0,10.0,0.0,0.0
105856,zwilldu01,Dutch,Zwilling,L,1910-08-14,1916-07-12,1915,1,CHF,FL,...,94.0,24.0,0.0,67,65.0,0.0,2.0,18.0,0.0,0.0
105857,zwilldu01,Dutch,Zwilling,L,1910-08-14,1916-07-12,1916,1,CHN,NL,...,8.0,0.0,0.0,4,6.0,0.0,0.0,2.0,0.0,0.0
105858,zychto01,Tony,Zych,R,2015-09-04,2017-08-19,2015,1,SEA,AL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105859,zychto01,Tony,Zych,R,2015-09-04,2017-08-19,2016,1,SEA,AL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105860,zychto01,Tony,Zych,R,2015-09-04,2017-08-19,2017,1,SEA,AL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [107]:
#imprimimos cada tipo de dato por columna para ver que podemos modificar para conveniencia
print(allbatting.columns)
for xol in allbatting:
    print(type(allbatting[xol][0]))

Index(['playerID', 'nameFirst', 'nameLast', 'bats', 'debut', 'finalGame',
       'yearID', 'stint', 'teamID', 'lgID', 'G', 'AB', 'R', 'H', '2B', '3B',
       'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'IBB', 'HBP', 'SH', 'SF', 'GIDP'],
      dtype='object')
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>

In [112]:
#cambiamos debut y finalGame que tienen str por date 
allbatting['debut']= pd.to_datetime(allbatting['debut'])

In [113]:
allbatting['finalGame']= pd.to_datetime(allbatting['finalGame'])

In [114]:
#checamos que si se hayan cambiado
print(allbatting.columns)
for xol in allbatting:
    print(type(allbatting[xol][0]))

Index(['playerID', 'nameFirst', 'nameLast', 'bats', 'debut', 'finalGame',
       'yearID', 'stint', 'teamID', 'lgID', 'G', 'AB', 'R', 'H', '2B', '3B',
       'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'IBB', 'HBP', 'SH', 'SF', 'GIDP'],
      dtype='object')
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>

In [139]:
#la columna de AB (At Bat) es la cantidad de veces que estuvieron en la caja de bateo cada aÃ±o
#si AB = 0 entonces significa que no salieron a batear ni una vez por lo que su info no nos sirve para estadisticas de bateo
#asi que sacamos una lista con los indices de las filas que AB =0 
list_ab = list(allbatting["AB"])
abnan = []

for x, y in enumerate(list_ab):
        if y == 0:
            abnan.append(x)

abnan

[0,
 2,
 4,
 5,
 6,
 7,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 51,
 56,
 58,
 59,
 60,
 62,
 63,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 129,
 132,
 134,
 135,
 136,
 137,
 138,
 139,
 142,
 143,
 144,
 147,
 164,
 179,
 185,
 237,
 244,
 246,
 247,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 263,
 264,
 265,
 266,
 267,
 278,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 294,
 295,
 296,
 297,
 314,
 315,
 321,
 324,
 325,
 326,
 333,
 334,
 335,
 336,
 359,
 365,
 366,
 368,
 369,
 370,
 400,
 425,
 445,
 470,
 471,
 472,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 510,
 519,
 520,
 521,
 527,
 528,
 546,
 548,
 549,
 570,
 571,
 579,
 587,
 588,
 589,
 591,
 592,
 593,
 612,
 614,
 615,
 618,
 624,
 625,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 672,
 673,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 712,
 717,
 730,
 764,
 767,
 768,
 769,
 774,
 775,
 776,
 788,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 818,
 819,
 820,
 823,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 833,
 834,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 853,
 864,
 865,
 866,
 868,
 869,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 901,
 904,
 905,
 907,
 921,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 941,
 942,
 943,
 944,
 945,
 946,
 949,
 950,
 951,
 960,
 961,
 962,
 969,
 974,
 1008,
 1009,
 1025,
 1026,
 1028,
 1030,
 1031,
 1075,
 1076,
 1077,
 1105,
 1119,
 1120,
 1121,
 1122,
 1123,
 1124,
 1125,
 1194,
 1216,
 1217,
 1218,
 1219,
 1220,
 1235,
 1236,
 1237,
 1238,
 1239,
 1240,
 1287,
 1322,
 1323,
 1324,
 1325,
 1326,
 1327,
 1328,
 1331,
 1332,
 1333,
 1334,
 1367,
 1368,
 1370,
 1371,
 1372,
 1540,
 1541,
 1542,
 1583,
 1586,
 1589,
 1605,
 1606,
 1609,
 1610,
 1611,
 1612,
 1613,
 1620,
 1626,
 1627,
 1631,
 1632,
 1634,
 1635,
 1636,
 1637,
 1638,
 1639,
 1640,
 1641,
 1669,
 1670,
 1678,
 1679,
 1680,
 1681,
 1682,
 1683,
 1684,
 1685,
 1688,
 1738,
 1770,
 1771,
 1772,
 1773,
 1796,
 1818,
 1824,
 1825,
 1826,
 1828,
 1829,
 1856,
 1857,
 1858,
 1859,
 1860,
 1867,
 1869,
 1877,
 1879,
 1880,
 1885,
 1894,
 1895,
 1902,
 1921,
 1966,
 1967,
 1968,
 1969,
 1982,
 2001,
 2002,
 2008,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2022,
 2028,
 2032,
 2036,
 2037,
 2038,
 2039,
 2040,
 2041,
 2042,
 2070,
 2071,
 2073,
 2074,
 2075,
 2077,
 2103,
 2114,
 2118,
 2119,
 2145,
 2147,
 2176,
 2177,
 2205,
 2206,
 2208,
 2209,
 2210,
 2211,
 2212,
 2216,
 2275,
 2281,
 2321,
 2326,
 2327,
 2328,
 2329,
 2330,
 2331,
 2332,
 2333,
 2334,
 2335,
 2336,
 2337,
 2338,
 2340,
 2342,
 2347,
 2348,
 2356,
 2358,
 2365,
 2367,
 2391,
 2393,
 2394,
 2395,
 2396,
 2398,
 2399,
 2400,
 2401,
 2402,
 2403,
 2411,
 2412,
 2413,
 2415,
 2416,
 2426,
 2429,
 2465,
 2533,
 2577,
 2579,
 2581,
 2582,
 2583,
 2584,
 2585,
 2586,
 2587,
 2588,
 2589,
 2590,
 2591,
 2606,
 2608,
 2609,
 2610,
 2619,
 2620,
 2621,
 2622,
 2623,
 2624,
 2630,
 2631,
 2632,
 2633,
 2635,
 2639,
 2647,
 2658,
 2660,
 2666,
 2681,
 2682,
 2683,
 2684,
 2685,
 2686,
 2687,
 2688,
 2689,
 2697,
 2713,
 2714,
 2716,
 2717,
 2724,
 2773,
 2777,
 2782,
 2785,
 2837,
 2838,
 2839,
 2840,
 2841,
 2842,
 2843,
 2845,
 2860,
 2879,
 2880,
 2882,
 2883,
 2884,
 2885,
 2886,
 2887,
 2891,
 2892,
 2893,
 2894,
 2895,
 2896,
 2897,
 2904,
 2920,
 2922,
 2946,
 2965,
 2966,
 2967,
 2968,
 2969,
 2970,
 2971,
 2972,
 2973,
 2974,
 2975,
 2976,
 2977,
 2978,
 2994,
 2995,
 2997,
 3014,
 3015,
 3038,
 3039,
 3055,
 3059,
 3060,
 3061,
 3064,
 3065,
 3074,
 3146,
 3147,
 3148,
 3150,
 3153,
 3165,
 3170,
 3171,
 3175,
 3176,
 3177,
 3179,
 3180,
 3181,
 3182,
 3183,
 3184,
 3185,
 3186,
 3187,
 3200,
 3201,
 3202,
 3203,
 3204,
 3206,
 3210,
 3212,
 3213,
 3214,
 3215,
 3216,
 3217,
 3218,
 3235,
 3237,
 3240,
 3241,
 3260,
 3262,
 3264,
 3287,
 3288,
 3289,
 3300,
 3301,
 3325,
 3326,
 3327,
 3328,
 3329,
 3330,
 3333,
 3338,
 3345,
 3359,
 3361,
 3362,
 3364,
 3383,
 3386,
 3387,
 3388,
 3389,
 3390,
 3392,
 3404,
 3405,
 3409,
 3452,
 3453,
 3454,
 3456,
 3457,
 3463,
 3464,
 3469,
 3470,
 3471,
 3472,
 3473,
 3474,
 3475,
 3476,
 3477,
 3509,
 3510,
 3511,
 3514,
 3515,
 3516,
 3544,
 3545,
 3546,
 3574,
 3575,
 3576,
 3577,
 3578,
 3579,
 3580,
 3581,
 3582,
 3584,
 3587,
 3642,
 3643,
 3651,
 3652,
 3653,
 3654,
 3655,
 3657,
 3661,
 3662,
 3663,
 3673,
 3774,
 3808,
 3809,
 3819,
 3820,
 3821,
 3822,
 3823,
 3826,
 3828,
 3830,
 3845,
 3876,
 3879,
 3884,
 3887,
 3889,
 3890,
 3898,
 3901,
 3902,
 3934,
 3935,
 3936,
 3938,
 3939,
 3940,
 3949,
 3951,
 3955,
 3956,
 3957,
 3958,
 3959,
 3961,
 3962,
 3963,
 3965,
 3966,
 3967,
 3968,
 3969,
 3970,
 3971,
 3972,
 3977,
 3981,
 3982,
 4002,
 4003,
 4025,
 4034,
 4056,
 4057,
 4058,
 4066,
 4067,
 4068,
 4069,
 4070,
 4071,
 4073,
 4074,
 4075,
 4110,
 4113,
 4115,
 4116,
 4117,
 4122,
 4123,
 4125,
 4126,
 4148,
 4149,
 4150,
 4151,
 4152,
 4154,
 4155,
 4156,
 4157,
 4158,
 4159,
 4160,
 4161,
 4175,
 4191,
 4193,
 4210,
 4211,
 4212,
 4234,
 4239,
 4240,
 4253,
 4254,
 4255,
 4258,
 4264,
 4265,
 4266,
 4268,
 4285,
 4286,
 4288,
 4289,
 4290,
 4304,
 4305,
 4306,
 4324,
 4335,
 4336,
 4337,
 4338,
 4339,
 4340,
 4341,
 4342,
 4346,
 4352,
 4354,
 4355,
 4356,
 4366,
 4368,
 4369,
 4370,
 4371,
 4372,
 4373,
 4411,
 4412,
 4429,
 4430,
 4431,
 4442,
 4443,
 4444,
 4445,
 4462,
 4467,
 4468,
 4469,
 4470,
 4471,
 4483,
 4484,
 4495,
 4496,
 4506,
 4507,
 4508,
 4509,
 4528,
 4547,
 4548,
 4550,
 4551,
 4552,
 4553,
 4554,
 4555,
 4564,
 4567,
 4570,
 4577,
 4579,
 4580,
 4607,
 4611,
 4614,
 4615,
 4616,
 4661,
 4674,
 4675,
 4676,
 4677,
 4678,
 4679,
 4680,
 4683,
 4684,
 4685,
 4686,
 4695,
 4696,
 4704,
 4710,
 4711,
 4712,
 4733,
 4750,
 4776,
 4808,
 4809,
 4821,
 4822,
 4823,
 4827,
 4845,
 4846,
 4847,
 4848,
 4849,
 4850,
 4865,
 4867,
 4868,
 4908,
 4909,
 4910,
 4911,
 4912,
 4914,
 4915,
 4916,
 4926,
 4936,
 4937,
 4956,
 4988,
 4989,
 4999,
 5002,
 5005,
 5008,
 5024,
 5058,
 5088,
 5089,
 5090,
 5091,
 5092,
 5093,
 5094,
 5095,
 5096,
 5103,
 5113,
 5114,
 5115,
 5127,
 5144,
 5145,
 5146,
 5147,
 5174,
 5189,
 5190,
 5191,
 5192,
 5195,
 5197,
 5199,
 5200,
 5201,
 5202,
 5203,
 5208,
 5209,
 5252,
 5267,
 5268,
 5269,
 5300,
 5301,
 5321,
 5346,
 5355,
 5356,
 5357,
 5365,
 5366,
 5367,
 5368,
 5369,
 5370,
 5371,
 5372,
 5377,
 5381,
 5384,
 5396,
 5397,
 5402,
 5403,
 5404,
 5412,
 5413,
 5414,
 5415,
 5416,
 5417,
 5419,
 5421,
 5422,
 5423,
 5424,
 5425,
 5426,
 5427,
 5428,
 5429,
 5454,
 5456,
 5457,
 5465,
 5469,
 5478,
 5491,
 5492,
 5493,
 5494,
 5495,
 ...]

In [142]:
#eliminamos esas filas para poder sacar el promedio de bateo y que no nos marque 0
allbatting2 = allbatting.drop(abnan, axis=0)
allbatting2

,playerID,nameFirst,nameLast,bats,debut,finalGame,yearID,stint,teamID,lgID,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
1,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2006,1,CHN,NL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0
3,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2008,1,BOS,AL,...,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
8,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2015,1,ATL,NL,...,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
9,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1954,1,ML1,NL,...,69.0,2.0,2.0,28,39.0,0.0,3.0,6.0,4.0,13.0
10,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1955,1,ML1,NL,...,106.0,3.0,1.0,49,61.0,5.0,3.0,7.0,4.0,20.0
11,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1956,1,ML1,NL,...,92.0,2.0,4.0,37,54.0,6.0,2.0,5.0,7.0,21.0
12,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1957,1,ML1,NL,...,132.0,1.0,1.0,57,58.0,15.0,0.0,0.0,3.0,13.0
13,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1958,1,ML1,NL,...,95.0,4.0,1.0,59,49.0,16.0,1.0,0.0,3.0,21.0
14,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1959,1,ML1,NL,...,123.0,8.0,0.0,51,54.0,17.0,4.0,0.0,9.0,19.0
15,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1960,1,ML1,NL,...,126.0,16.0,7.0,60,63.0,13.0,2.0,0.0,12.0,8.0
16,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1961,1,ML1,NL,...,120.0,21.0,9.0,56,64.0,20.0,2.0,1.0,9.0,16.0
17,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1962,1,ML1,NL,...,128.0,15.0,7.0,66,73.0,14.0,3.0,0.0,6.0,14.0
18,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1963,1,ML1,NL,...,130.0,31.0,5.0,78,94.0,18.0,0.0,0.0,5.0,11.0
19,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1964,1,ML1,NL,...,95.0,22.0,4.0,62,46.0,9.0,0.0,0.0,2.0,22.0
20,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1965,1,ML1,NL,...,89.0,24.0,4.0,60,81.0,10.0,1.0,0.0,8.0,15.0
21,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1966,1,ATL,NL,...,127.0,21.0,3.0,76,96.0,15.0,1.0,0.0,8.0,14.0
22,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1967,1,ATL,NL,...,109.0,17.0,6.0,63,97.0,19.0,0.0,0.0,6.0,11.0
23,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1968,1,ATL,NL,...,86.0,28.0,5.0,64,62.0,23.0,1.0,0.0,5.0,21.0
24,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1969,1,ATL,NL,...,97.0,9.0,10.0,87,47.0,19.0,2.0,0.0,3.0,14.0
25,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1970,1,ATL,NL,...,118.0,9.0,0.0,74,63.0,15.0,2.0,0.0,6.0,13.0
26,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1971,1,ATL,NL,...,118.0,1.0,1.0,71,58.0,21.0,2.0,0.0,5.0,9.0
27,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1972,1,ATL,NL,...,77.0,4.0,0.0,92,55.0,15.0,1.0,0.0,2.0,17.0
28,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1973,1,ATL,NL,...,96.0,1.0,1.0,68,51.0,13.0,1.0,0.0,4.0,7.0
29,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1974,1,ATL,NL,...,69.0,1.0,0.0,39,29.0,6.0,0.0,1.0,2.0,6.0
30,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1975,1,ML4,AL,...,60.0,0.0,1.0,70,51.0,3.0,1.0,1.0,6.0,15.0
31,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1976,1,ML4,AL,...,35.0,0.0,1.0,35,38.0,1.0,0.0,0.0,2.0,8.0
32,aaronto01,Tommie,Aaron,R,1962-04-10,1971-09-26,1962,1,ML1,NL,...,38.0,6.0,0.0,41,58.0,0.0,0.0,4.0,3.0,10.0
33,aaronto01,Tommie,Aaron,R,1962-04-10,1971-09-26,1963,1,ML1,NL,...,15.0,0.0,3.0,11,27.0,1.0,0.0,3.0,2.0,7.0
34,aaronto01,Tommie,Aaron,R,1962-04-10,1971-09-26,1965,1,ML1,NL,...,1.0,0.0,0.0,1,2.0,0.0,0.0,0.0,0.0,1.0
35,aaronto01,Tommie,Aaron,R,1962-04-10,1971-09-26,1968,1,ATL,NL,...,25.0,3.0,4.0,21,37.0,1.0,0.0,2.0,1.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105824,zuninmi01,Mike,Zunino,R,2013-06-12,2018-09-29,2016,1,SEA,AL,...,31.0,0.0,0.0,21,65.0,0.0,6.0,0.0,1.0,0.0
105825,zuninmi01,Mike,Zunino,R,2013-06-12,2018-09-29,2017,1,SEA,AL,...,64.0,1.0,0.0,39,160.0,0.0,8.0,0.0,1.0,8.0
105826,zuninmi01,Mike,Zunino,R,2013-06-12,2018-09-29,2018,1,SEA,AL,...,44.0,0.0,0.0,24,150.0,0.0,6.0,0.0,2.0,7.0
105827,zupcibo01,Bob,Zupcic,R,1991-09-07,1994-08-04,1991,1,BOS,AL,...,3.0,0.0,0.0,1,6.0,0.0,0.0,1.0,0.0,0.0
105828,zupcibo01,Bob,Zupcic,R,1991-09-07,1994-08-04,1992,1,BOS,AL,...,43.0,2.0,2.0,25,60.0,1.0,4.0,7.0,4.0,6.0
105829,zupcibo01,Bob,Zupcic,R,1991-09-07,1994-08-04,1993,1,BOS,AL,...,26.0,5.0,2.0,27,54.0,2.0,2.0,8.0,3.0,7.0
105830,zupcibo01,Bob,Zupcic,R,1991-09-07,1994-08-04,1994,1,BOS,AL,...,0.0,0.0,1.0,0,1.0,0.0,0.0,0.0,0.0,0.0
105831,zupcibo01,Bob,Zupcic,R,1991-09-07,1994-08-04,1994,2,CHA,AL,...,8.0,0.0,0.0,4,16.0,0.0,0.0,4.0,1.0,2.0
105832,zupofr01,Frank,Zupo,L,1957-07-01,1961-05-09,1957,1,BAL,AL,...,0.0,0.0,0.0,1,4.0,0.0,0.0,0.0,0.0,0.0
105833,zupofr01,Frank,Zupo,L,1957-07-01,1961-05-09,1958,1,BAL,AL,...,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
105834,zupofr01,Frank,Zupo,L,1957-07-01,1961-05-09,1961,1,BAL,AL,...,0.0,0.0,0.0,1,1.0,0.0,0.0,0.0,0.0,0.0
105835,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1982,1,ATL,NL,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
105836,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1983,1,ATL,NL,...,0.0,0.0,0.0,2,1.0,0.0,1.0,0.0,0.0,0.0
105837,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1984,1,ATL,NL,...,1.0,0.0,0.0,2,3.0,0.0,0.0,0.0,0.0,0.0
105838,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1985,1,ATL,NL,...,4.0,2.0,0.0,16,14.0,1.0,0.0,4.0,0.0,3.0
105839,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1986,1,NYA,AL,...,2.0,0.0,0.0,5,4.0,0.0,0.0,4.0,0.0,1.0
105840,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1987,1,NYA,AL,...,0.0,0.0,0.0,0,4.0,0.0,0.0,2.0,0.0,1.0
105841,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1988,1,CLE,AL,...,7.0,0.0,0.0,8,13.0,0.0,0.0,8.0,0.0,3.0
105842,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1989,1,CLE,AL,...,6.0,0.0,0.0,1,11.0,0.0,1.0,0.0,0.0,0.0
105846,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1954,1,CIN,NL,...,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
105847,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1954,2,DET,AL,...,3.0,0.0,1.0,1,14.0,0.0,0.0,9.0,0.0,2.0
105848,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1955,1,DET,AL,...,0.0,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0
105849,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1955,2,BAL,AL,...,0.0,0.0,0.0,1,5.0,0.0,0.0,1.0,0.0,1.0
105850,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1956,1,BAL,AL,...,2.0,0.0,0.0,1,7.0,0.0,0.0,4.0,0.0,0.0
105851,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1957,1,BAL,AL,...,0.0,0.0,0.0,3,8.0,0.0,0.0,2.0,0.0,0.0
105852,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1958,1,BAL,AL,...,2.0,0.0,0.0,1,2.0,0.0,0.0,0.0,0.0,0.0
105854,zwilldu01,Dutch,Zwilling,L,1910-08-14,1916-07-12,1910,1,CHA,AL,...,5.0,1.0,0.0,11,16.0,0.0,1.0,1.0,0.0,0.0
105855,zwilldu01,Dutch,Zwilling,L,1910-08-14,1916-07-12,1914,1,CHF,FL,...,95.0,21.0,0.0,46,68.0,0.0,1.0,10.0,0.0,0.0
105856,zwilldu01,Dutch,Zwilling,L,1910-08-14,1916-07-12,1915,1,CHF,FL,...,94.0,24.0,0.0,67,65.0,0.0,2.0,18.0,0.0,0.0
105857,zwilldu01,Dutch,Zwilling,L,1910-08-14,1916-07-12,1916,1,CHN,NL,...,8.0,0.0,0.0,4,6.0,0.0,0.0,2.0,0.0,0.0

In [144]:
#cambiamos la variable a allbatting otra vez
allbatting = allbatting2

In [151]:
#sacamos el promedio de bateo
batting_avg = allbatting["H"] / allbatting["AB"]
batting_avg.columns = ["BA"]

In [158]:
#checamos que la len del promedio de bateo sea igual que el total de datos en nuestro dataframe principal
len(batting_avg)

89521

In [159]:
len(allbatting)

89521

In [160]:
#agregamsos el promedio de bateo como una columna al final
allbatting['avgYear'] = batting_avg
allbatting

,playerID,nameFirst,nameLast,bats,debut,finalGame,yearID,stint,teamID,lgID,...,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,avgYear
1,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2006,1,CHN,NL,...,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.000000
3,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2008,1,BOS,AL,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.000000
8,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2015,1,ATL,NL,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.000000
9,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1954,1,ML1,NL,...,2.0,2.0,28,39.0,0.0,3.0,6.0,4.0,13.0,0.279915
10,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1955,1,ML1,NL,...,3.0,1.0,49,61.0,5.0,3.0,7.0,4.0,20.0,0.313953
11,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1956,1,ML1,NL,...,2.0,4.0,37,54.0,6.0,2.0,5.0,7.0,21.0,0.328407
12,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1957,1,ML1,NL,...,1.0,1.0,57,58.0,15.0,0.0,0.0,3.0,13.0,0.321951
13,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1958,1,ML1,NL,...,4.0,1.0,59,49.0,16.0,1.0,0.0,3.0,21.0,0.326123
14,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1959,1,ML1,NL,...,8.0,0.0,51,54.0,17.0,4.0,0.0,9.0,19.0,0.354531
15,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1960,1,ML1,NL,...,16.0,7.0,60,63.0,13.0,2.0,0.0,12.0,8.0,0.291525
16,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1961,1,ML1,NL,...,21.0,9.0,56,64.0,20.0,2.0,1.0,9.0,16.0,0.326700
17,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1962,1,ML1,NL,...,15.0,7.0,66,73.0,14.0,3.0,0.0,6.0,14.0,0.322635
18,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1963,1,ML1,NL,...,31.0,5.0,78,94.0,18.0,0.0,0.0,5.0,11.0,0.318542
19,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1964,1,ML1,NL,...,22.0,4.0,62,46.0,9.0,0.0,0.0,2.0,22.0,0.328070
20,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1965,1,ML1,NL,...,24.0,4.0,60,81.0,10.0,1.0,0.0,8.0,15.0,0.317544
21,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1966,1,ATL,NL,...,21.0,3.0,76,96.0,15.0,1.0,0.0,8.0,14.0,0.278607
22,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1967,1,ATL,NL,...,17.0,6.0,63,97.0,19.0,0.0,0.0,6.0,11.0,0.306667
23,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1968,1,ATL,NL,...,28.0,5.0,64,62.0,23.0,1.0,0.0,5.0,21.0,0.287129
24,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1969,1,ATL,NL,...,9.0,10.0,87,47.0,19.0,2.0,0.0,3.0,14.0,0.299817
25,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1970,1,ATL,NL,...,9.0,0.0,74,63.0,15.0,2.0,0.0,6.0,13.0,0.298450
26,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1971,1,ATL,NL,...,1.0,1.0,71,58.0,21.0,2.0,0.0,5.0,9.0,0.327273
27,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1972,1,ATL,NL,...,4.0,0.0,92,55.0,15.0,1.0,0.0,2.0,17.0,0.265033
28,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1973,1,ATL,NL,...,1.0,1.0,68,51.0,13.0,1.0,0.0,4.0,7.0,0.301020
29,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1974,1,ATL,NL,...,1.0,0.0,39,29.0,6.0,0.0,1.0,2.0,6.0,0.267647
30,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1975,1,ML4,AL,...,0.0,1.0,70,51.0,3.0,1.0,1.0,6.0,15.0,0.234409
31,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1976,1,ML4,AL,...,0.0,1.0,35,38.0,1.0,0.0,0.0,2.0,8.0,0.228782
32,aaronto01,Tommie,Aaron,R,1962-04-10,1971-09-26,1962,1,ML1,NL,...,6.0,0.0,41,58.0,0.0,0.0,4.0,3.0,10.0,0.230539
33,aaronto01,Tommie,Aaron,R,1962-04-10,1971-09-26,1963,1,ML1,NL,...,0.0,3.0,11,27.0,1.0,0.0,3.0,2.0,7.0,0.200000
34,aaronto01,Tommie,Aaron,R,1962-04-10,1971-09-26,1965,1,ML1,NL,...,0.0,0.0,1,2.0,0.0,0.0,0.0,0.0,1.0,0.187500
35,aaronto01,Tommie,Aaron,R,1962-04-10,1971-09-26,1968,1,ATL,NL,...,3.0,4.0,21,37.0,1.0,0.0,2.0,1.0,9.0,0.243816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105824,zuninmi01,Mike,Zunino,R,2013-06-12,2018-09-29,2016,1,SEA,AL,...,0.0,0.0,21,65.0,0.0,6.0,0.0,1.0,0.0,0.207317
105825,zuninmi01,Mike,Zunino,R,2013-06-12,2018-09-29,2017,1,SEA,AL,...,1.0,0.0,39,160.0,0.0,8.0,0.0,1.0,8.0,0.250646
105826,zuninmi01,Mike,Zunino,R,2013-06-12,2018-09-29,2018,1,SEA,AL,...,0.0,0.0,24,150.0,0.0,6.0,0.0,2.0,7.0,0.201072
105827,zupcibo01,Bob,Zupcic,R,1991-09-07,1994-08-04,1991,1,BOS,AL,...,0.0,0.0,1,6.0,0.0,0.0,1.0,0.0,0.0,0.160000
105828,zupcibo01,Bob,Zupcic,R,1991-09-07,1994-08-04,1992,1,BOS,AL,...,2.0,2.0,25,60.0,1.0,4.0,7.0,4.0,6.0,0.275510
105829,zupcibo01,Bob,Zupcic,R,1991-09-07,1994-08-04,1993,1,BOS,AL,...,5.0,2.0,27,54.0,2.0,2.0,8.0,3.0,7.0,0.241259
105830,zupcibo01,Bob,Zupcic,R,1991-09-07,1994-08-04,1994,1,BOS,AL,...,0.0,1.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.000000
105831,zupcibo01,Bob,Zupcic,R,1991-09-07,1994-08-04,1994,2,CHA,AL,...,0.0,0.0,4,16.0,0.0,0.0,4.0,1.0,2.0,0.204545
105832,zupofr01,Frank,Zupo,L,1957-07-01,1961-05-09,1957,1,BAL,AL,...,0.0,0.0,1,4.0,0.0,0.0,0.0,0.0,0.0,0.083333
105833,zupofr01,Frank,Zupo,L,1957-07-01,1961-05-09,1958,1,BAL,AL,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.000000
105834,zupofr01,Frank,Zupo,L,1957-07-01,1961-05-09,1961,1,BAL,AL,...,0.0,0.0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.500000
105835,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1982,1,ATL,NL,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
105836,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1983,1,ATL,NL,...,0.0,0.0,2,1.0,0.0,1.0,0.0,0.0,0.0,0.000000
105837,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1984,1,ATL,NL,...,0.0,0.0,2,3.0,0.0,0.0,0.0,0.0,0.0,0.200000
105838,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1985,1,ATL,NL,...,2.0,0.0,16,14.0,1.0,0.0,4.0,0.0,3.0,0.252632
105839,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1986,1,NYA,AL,...,0.0,0.0,5,4.0,0.0,0.0,4.0,0.0,1.0,0.083333
105840,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1987,1,NYA,AL,...,0.0,0.0,0,4.0,0.0,0.0,2.0,0.0,1.0,0.176471
105841,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1988,1,CLE,AL,...,0.0,0.0,8,13.0,0.0,0.0,8.0,0.0,3.0,0.230769
105842,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1989,1,CLE,AL,...,0.0,0.0,1,11.0,0.0,1.0,0.0,0.0,0.0,0.275862
105846,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1954,1,CIN,NL,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.500000
105847,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1954,2,DET,AL,...,0.0,1.0,1,14.0,0.0,0.0,9.0,0.0,2.0,0.125000
105848,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1955,1,DET,AL,...,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0,0.000000
105849,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1955,2,BAL,AL,...,0.0,0.0,1,5.0,0.0,0.0,1.0,0.0,1.0,0.217391
105850,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1956,1,BAL,AL,...,0.0,0.0,1,7.0,0.0,0.0,4.0,0.0,0.0,0.117647
105851,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1957,1,BAL,AL,...,0.0,0.0,3,8.0,0.0,0.0,2.0,0.0,0.0,0.130435
105852,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1958,1,BAL,AL,...,0.0,0.0,1,2.0,0.0,0.0,0.0,0.0,0.0,0.222222
105854,zwilldu01,Dutch,Zwilling,L,1910-08-14,1916-07-12,1910,1,CHA,AL,...,1.0,0.0,11,16.0,0.0,1.0,1.0,0.0,0.0,0.183908
105855,zwilldu01,Dutch,Zwilling,L,1910-08-14,1916-07-12,1914,1,CHF,FL,...,21.0,0.0,46,68.0,0.0,1.0,10.0,0.0,0.0,0.312500
105856,zwilldu01,Dutch,Zwilling,L,1910-08-14,1916-07-12,1915,1,CHF,FL,...,24.0,0.0,67,65.0,0.0,2.0,18.0,0.0,0.0,0.286496
105857,zwilldu01,Dutch,Zwilling,L,1910-08-14,1916-07-12,1916,1,CHN,NL,...,0.0,0.0,4,6.0,0.0,0.0,2.0,0.0,0.0,0.113208

In [162]:
allbatting.columns

Index(['playerID', 'nameFirst', 'nameLast', 'bats', 'debut', 'finalGame',
       'yearID', 'stint', 'teamID', 'lgID', 'G', 'AB', 'R', 'H', '2B', '3B',
       'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'IBB', 'HBP', 'SH', 'SF', 'GIDP',
       'avgYear'],
      dtype='object')

In [165]:
#cambiamos los nombres de las columnas
col_names = ["PlayerID", "FirstName", "Lastname", "Bats: left, right, both", "Date of debut", "Date of final game",
             "Year", "Stint", "Team", "Leage", "Games", "At Bat", "Runs", "Hits", "Doubles", "Triples", "HomeRuns",
             "Runs Batted In", "Stolen Bases", "Cought Stealing", "Walks", "Strikes Out", "Intencional Walks", 
             "Hits By Pitch", "Sacrifice HIts", "Sacrifice Fly", "Ground into Double Play", "Average Batting"
            ]
allbatting.columns = col_names

In [166]:
allbatting

,PlayerID,FirstName,Lastname,"Bats: left, right, both",Date of debut,Date of final game,Year,Stint,Team,Leage,...,Stolen Bases,Cought Stealing,Walks,Strikes Out,Intencional Walks,Hits By Pitch,Sacrifice HIts,Sacrifice Fly,Ground into Double Play,Average Batting
1,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2006,1,CHN,NL,...,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.000000
3,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2008,1,BOS,AL,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.000000
8,aardsda01,David,Aardsma,R,2004-04-06,2015-08-23,2015,1,ATL,NL,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.000000
9,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1954,1,ML1,NL,...,2.0,2.0,28,39.0,0.0,3.0,6.0,4.0,13.0,0.279915
10,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1955,1,ML1,NL,...,3.0,1.0,49,61.0,5.0,3.0,7.0,4.0,20.0,0.313953
11,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1956,1,ML1,NL,...,2.0,4.0,37,54.0,6.0,2.0,5.0,7.0,21.0,0.328407
12,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1957,1,ML1,NL,...,1.0,1.0,57,58.0,15.0,0.0,0.0,3.0,13.0,0.321951
13,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1958,1,ML1,NL,...,4.0,1.0,59,49.0,16.0,1.0,0.0,3.0,21.0,0.326123
14,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1959,1,ML1,NL,...,8.0,0.0,51,54.0,17.0,4.0,0.0,9.0,19.0,0.354531
15,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1960,1,ML1,NL,...,16.0,7.0,60,63.0,13.0,2.0,0.0,12.0,8.0,0.291525
16,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1961,1,ML1,NL,...,21.0,9.0,56,64.0,20.0,2.0,1.0,9.0,16.0,0.326700
17,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1962,1,ML1,NL,...,15.0,7.0,66,73.0,14.0,3.0,0.0,6.0,14.0,0.322635
18,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1963,1,ML1,NL,...,31.0,5.0,78,94.0,18.0,0.0,0.0,5.0,11.0,0.318542
19,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1964,1,ML1,NL,...,22.0,4.0,62,46.0,9.0,0.0,0.0,2.0,22.0,0.328070
20,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1965,1,ML1,NL,...,24.0,4.0,60,81.0,10.0,1.0,0.0,8.0,15.0,0.317544
21,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1966,1,ATL,NL,...,21.0,3.0,76,96.0,15.0,1.0,0.0,8.0,14.0,0.278607
22,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1967,1,ATL,NL,...,17.0,6.0,63,97.0,19.0,0.0,0.0,6.0,11.0,0.306667
23,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1968,1,ATL,NL,...,28.0,5.0,64,62.0,23.0,1.0,0.0,5.0,21.0,0.287129
24,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1969,1,ATL,NL,...,9.0,10.0,87,47.0,19.0,2.0,0.0,3.0,14.0,0.299817
25,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1970,1,ATL,NL,...,9.0,0.0,74,63.0,15.0,2.0,0.0,6.0,13.0,0.298450
26,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1971,1,ATL,NL,...,1.0,1.0,71,58.0,21.0,2.0,0.0,5.0,9.0,0.327273
27,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1972,1,ATL,NL,...,4.0,0.0,92,55.0,15.0,1.0,0.0,2.0,17.0,0.265033
28,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1973,1,ATL,NL,...,1.0,1.0,68,51.0,13.0,1.0,0.0,4.0,7.0,0.301020
29,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1974,1,ATL,NL,...,1.0,0.0,39,29.0,6.0,0.0,1.0,2.0,6.0,0.267647
30,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1975,1,ML4,AL,...,0.0,1.0,70,51.0,3.0,1.0,1.0,6.0,15.0,0.234409
31,aaronha01,Hank,Aaron,R,1954-04-13,1976-10-03,1976,1,ML4,AL,...,0.0,1.0,35,38.0,1.0,0.0,0.0,2.0,8.0,0.228782
32,aaronto01,Tommie,Aaron,R,1962-04-10,1971-09-26,1962,1,ML1,NL,...,6.0,0.0,41,58.0,0.0,0.0,4.0,3.0,10.0,0.230539
33,aaronto01,Tommie,Aaron,R,1962-04-10,1971-09-26,1963,1,ML1,NL,...,0.0,3.0,11,27.0,1.0,0.0,3.0,2.0,7.0,0.200000
34,aaronto01,Tommie,Aaron,R,1962-04-10,1971-09-26,1965,1,ML1,NL,...,0.0,0.0,1,2.0,0.0,0.0,0.0,0.0,1.0,0.187500
35,aaronto01,Tommie,Aaron,R,1962-04-10,1971-09-26,1968,1,ATL,NL,...,3.0,4.0,21,37.0,1.0,0.0,2.0,1.0,9.0,0.243816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105824,zuninmi01,Mike,Zunino,R,2013-06-12,2018-09-29,2016,1,SEA,AL,...,0.0,0.0,21,65.0,0.0,6.0,0.0,1.0,0.0,0.207317
105825,zuninmi01,Mike,Zunino,R,2013-06-12,2018-09-29,2017,1,SEA,AL,...,1.0,0.0,39,160.0,0.0,8.0,0.0,1.0,8.0,0.250646
105826,zuninmi01,Mike,Zunino,R,2013-06-12,2018-09-29,2018,1,SEA,AL,...,0.0,0.0,24,150.0,0.0,6.0,0.0,2.0,7.0,0.201072
105827,zupcibo01,Bob,Zupcic,R,1991-09-07,1994-08-04,1991,1,BOS,AL,...,0.0,0.0,1,6.0,0.0,0.0,1.0,0.0,0.0,0.160000
105828,zupcibo01,Bob,Zupcic,R,1991-09-07,1994-08-04,1992,1,BOS,AL,...,2.0,2.0,25,60.0,1.0,4.0,7.0,4.0,6.0,0.275510
105829,zupcibo01,Bob,Zupcic,R,1991-09-07,1994-08-04,1993,1,BOS,AL,...,5.0,2.0,27,54.0,2.0,2.0,8.0,3.0,7.0,0.241259
105830,zupcibo01,Bob,Zupcic,R,1991-09-07,1994-08-04,1994,1,BOS,AL,...,0.0,1.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.000000
105831,zupcibo01,Bob,Zupcic,R,1991-09-07,1994-08-04,1994,2,CHA,AL,...,0.0,0.0,4,16.0,0.0,0.0,4.0,1.0,2.0,0.204545
105832,zupofr01,Frank,Zupo,L,1957-07-01,1961-05-09,1957,1,BAL,AL,...,0.0,0.0,1,4.0,0.0,0.0,0.0,0.0,0.0,0.083333
105833,zupofr01,Frank,Zupo,L,1957-07-01,1961-05-09,1958,1,BAL,AL,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.000000
105834,zupofr01,Frank,Zupo,L,1957-07-01,1961-05-09,1961,1,BAL,AL,...,0.0,0.0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.500000
105835,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1982,1,ATL,NL,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
105836,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1983,1,ATL,NL,...,0.0,0.0,2,1.0,0.0,1.0,0.0,0.0,0.0,0.000000
105837,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1984,1,ATL,NL,...,0.0,0.0,2,3.0,0.0,0.0,0.0,0.0,0.0,0.200000
105838,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1985,1,ATL,NL,...,2.0,0.0,16,14.0,1.0,0.0,4.0,0.0,3.0,0.252632
105839,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1986,1,NYA,AL,...,0.0,0.0,5,4.0,0.0,0.0,4.0,0.0,1.0,0.083333
105840,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1987,1,NYA,AL,...,0.0,0.0,0,4.0,0.0,0.0,2.0,0.0,1.0,0.176471
105841,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1988,1,CLE,AL,...,0.0,0.0,8,13.0,0.0,0.0,8.0,0.0,3.0,0.230769
105842,zuvelpa01,Paul,Zuvella,R,1982-09-04,1991-05-02,1989,1,CLE,AL,...,0.0,0.0,1,11.0,0.0,1.0,0.0,0.0,0.0,0.275862
105846,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1954,1,CIN,NL,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.500000
105847,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1954,2,DET,AL,...,0.0,1.0,1,14.0,0.0,0.0,9.0,0.0,2.0,0.125000
105848,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1955,1,DET,AL,...,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0,0.000000
105849,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1955,2,BAL,AL,...,0.0,0.0,1,5.0,0.0,0.0,1.0,0.0,1.0,0.217391
105850,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1956,1,BAL,AL,...,0.0,0.0,1,7.0,0.0,0.0,4.0,0.0,0.0,0.117647
105851,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1957,1,BAL,AL,...,0.0,0.0,3,8.0,0.0,0.0,2.0,0.0,0.0,0.130435
105852,zuverge01,George,Zuverink,R,1951-04-21,1959-06-15,1958,1,BAL,AL,...,0.0,0.0,1,2.0,0.0,0.0,0.0,0.0,0.0,0.222222
105854,zwilldu01,Dutch,Zwilling,L,1910-08-14,1916-07-12,1910,1,CHA,AL,...,1.0,0.0,11,16.0,0.0,1.0,1.0,0.0,0.0,0.183908
105855,zwilldu01,Dutch,Zwilling,L,1910-08-14,1916-07-12,1914,1,CHF,FL,...,21.0,0.0,46,68.0,0.0,1.0,10.0,0.0,0.0,0.312500
105856,zwilldu01,Dutch,Zwilling,L,1910-08-14,1916-07-12,1915,1,CHF,FL,...,24.0,0.0,67,65.0,0.0,2.0,18.0,0.0,0.0,0.286496
105857,zwilldu01,Dutch,Zwilling,L,1910-08-14,1916-07-12,1916,1,CHN,NL,...,0.0,0.0,4,6.0,0.0,0.0,2.0,0.0,0.0,0.113208

In [167]:
allbatting.to_csv("Batting-data.csv", index = False)