# Plane Crashes

<img src="plane-crash.jpg">

<font color=red>__Importando librerías__</font>

In [454]:
import pandas as pd 
import numpy as np

<font color=red>__Importando base__</font>

In [430]:
#Parseo y junto las variables de tiempo date and time

crash_plane = pd.read_csv('planecrashinfo_20181121001952.csv')

<font color=red>__Conociendo la base y sus valores__</font>

In [431]:
#Primeros 3 valores

crash_plane.head(3)

,date,time,location,operator,flight_no,route,ac_type,registration,cn_ln,aboard,fatalities,ground,summary
0,"September 17, 1908",17:18,"Fort Myer, Virginia",Military - U.S. Army,?,Demonstration,Wright Flyer III,?,1,2 (passengers:1 crew:1),1 (passengers:1 crew:0),0,"During a demonstration flight, a U.S. Army fly..."
1,"September 07, 1909",?,"Juvisy-sur-Orge, France",?,?,Air show,Wright Byplane,SC1,?,1 (passengers:0 crew:1),1 (passengers:0 crew:0),0,Eugene Lefebvre was the first pilot to ever be...
2,"July 12, 1912",06:30,"Atlantic City, New Jersey",Military - U.S. Navy,?,Test flight,Dirigible,?,?,5 (passengers:0 crew:5),5 (passengers:0 crew:5),0,First U.S. dirigible Akron exploded just offsh...

In [432]:
#Ultimos 3 valores 

crash_plane.tail(3)

,date,time,location,operator,flight_no,route,ac_type,registration,cn_ln,aboard,fatalities,ground,summary
5780,"September 28, 2018",1010,"Chuuk, Micronesia",Air Niugini,?,Pohnpei - Chuuk,Boeing 737-8BK,P2-PXE,33024/1688,47 (passengers:35 crew:12),1 (passengers:1 crew:0),0,The aircraft was approaching for a landing at ...
5781,"October 29, 2018",0631,"Off Jakarta, Indonesia",Lion Air,610,Jakarta - Pangkal Pinang,Boeing 737-MAX 8,PK-LQP,43000/7058,189 (passengers:181 crew:8),189 (passengers:181 crew:8),0,"The airliner crashed into the Jakarta Sea, 13 ..."
5782,"November 06, 2018",0253,"Georgetown, Guyana",Fly Jamaica Airways,?,Georgetown - Toronto,Boeing 757-N23,N524AT,30233/895,128 (passengers:120 crew:8),1 (passengers:1 crew:0),0,"After taking off and reaching FL200, the crew ..."

In [433]:
#Conociendo los tipos de variables que tengo en cada columna 

crash_plane.dtypes

date            object
time            object
location        object
operator        object
flight_no       object
route           object
ac_type         object
registration    object
cn_ln           object
aboard          object
fatalities      object
ground          object
summary         object
dtype: object

In [411]:
#Conociendo algunos parametros estadisticos actuales de mi base 

crash_plane.describe()

,date,time,location,operator,flight_no,route,ac_type,registration,cn_ln,aboard,fatalities,ground,summary
count,5783,5783,5783,5783,5783,5783,5783,5783,5783,5783,5783,5783,5783
unique,5213,1346,4715,2821,890,3875,2742,5394,4149,1042,917,54,5368
top,"August 31, 1988",?,"Moscow, Russia",Aeroflot,?,?,Douglas DC-3,?,?,2 (passengers:0 crew:2),1 (passengers:0 crew:1),0,?
freq,4,2108,18,260,4436,1494,341,352,1207,236,288,5474,231

In [413]:
#Conociendo las columnas con las que voy a trabajar en la base 

crash_plane.columns

Index(['date', 'time', 'location', 'operator', 'flight_no', 'route', 'ac_type',
       'registration', 'cn_ln', 'aboard', 'fatalities', 'ground', 'summary'],
      dtype='object')

<font color=red>__Missing values: reconociendo valores perdidos__</font>

In [414]:
null_cols = crash_plane.isnull().sum()
null_cols[null_cols > 0]
print(null_cols)

print("Encontre 0 valores nulos pero conociendo mi base puedo darme cuenta que hay valores que son nulos expresados en ? u otras variables")

date            0
time            0
location        0
operator        0
flight_no       0
route           0
ac_type         0
registration    0
cn_ln           0
aboard          0
fatalities      0
ground          0
summary         0
dtype: int64
Encontre 0 valores nulos pero conociendo mi base puedo darme cuenta que hay valores que son nulos expresados en ? u otras variables

<font color="red">Comenzamos modificando tiempo, uno de las columnas más importantes para entender a que hora y minutos sucedió el accidente. Esto es importante para un correspondiente informe periodístico y forense</font>

### Normalizando columna 'time'

In [434]:
#Limpiando los valores que dispersan mi muestra para determinar la hora del accidente 

crash_plane['time'] = crash_plane['time'].str.replace('?', '00:00')
crash_plane['time'] = crash_plane['time'].str.replace('c', '')
#crash_plane['time'] = crash_plane['time'].str.replace(':18', '00:00')
#crash_plane['time'] = crash_plane['time'].str.replace('17', '00:17')
print(crash_plane['time'])

#raw_data['Mycol'] =  pd.to_datetime(raw_data['Mycol'], format='%d%b%Y:%H:%M:%S.%f')

0        17:18
1        00:00
2        06:30
3        00:00
4        18:30
5        10:30
6        01:00
7        15:20
8        00:00
9        01:00
10       23:45
11       00:00
12       23:45
13       00:00
14       00:00
15       05:15
16       08:45
17       00:00
18       07:00
19       07:45
20       21:30
21       00:00
22       10:00
23       00:00
24       00:00
25       00:00
26       00:00
27       00:00
28       00:00
29       00:00
         ...
5753      1120
5754      0815
5755      0653
5756      1530
5757      1402
5758      1335
5759      1015
5760      1600
5761      0830
5762      0800
5763      1815
5764      1216
5765     00:00
5766      1731
5767      1431
5768      0926
5769      1451
5770      1908
5771     14:15
5772      1120
5773      0800
5774      1004
5775      1130
5776      1208
5777      1700
5778      0744
5779      1655
5780      1010
5781      0631
5782      0253
Name: time, Length: 5783, dtype: object

## Normalizando columna Date

In [437]:

#raw_data['Mycol'] =  pd.to_datetime(raw_data['Myco, format='%d%b%Y:%H:%M:%S.%f')
crash_plane['date'] = crash_plane['date'].str.replace('January', '1')
crash_plane['date'] = crash_plane['date'].str.replace('February', '2')
crash_plane['date']= crash_plane['date'].str.replace('March', '3')
crash_plane['date'] = crash_plane['date'].str.replace('Marh', '3')
crash_plane['date'] = crash_plane['date'].str.replace('April', '4')
crash_plane['date'] = crash_plane['date'].str.replace('May', '5')
crash_plane['date'] = crash_plane['date'].str.replace('June', '6')
crash_plane['date'] = crash_plane['date'].str.replace('July', '7')
crash_plane['date'] = crash_plane['date'].str.replace('August', '8')
crash_plane['date'] = crash_plane['date'].str.replace('September', '9')
crash_plane['date'] = crash_plane['date'].str.replace('October', '10')
crash_plane['date'] = crash_plane['date'].str.replace('Otober', '10')
crash_plane['date'] = crash_plane['date'].str.replace('November', '11')
crash_plane['date'] = crash_plane['date'].str.replace('December', '12')
crash_plane['date'] = crash_plane['date'].str.replace('Deember', '12')
crash_plane['date'] = crash_plane['date'].str.replace(',','')
crash_plane['date'] = crash_plane['date'].str.replace(' ','-')
print(set(crash_plane['date']))

{'8-24-2004', '3-10-1946', '2-22-1957', '11-18-1923', '12-31-1976', '1-30-1991', '2-19-1955', '12-08-1964', '11-14-1990', '12-14-1998', '9-08-1989', '3-08-1967', '6-15-1953', '8-13-1940', '1-29-1986', '2-08-1989', '5-04-1976', '8-20-1991', '1-11-1948', '12-31-1970', '1-27-1968', '3-11-2018', '8-17-1996', '8-03-1949', '12-17-1978', '9-26-1997', '8-09-1974', '4-24-1974', '6-27-1980', '11-21-1977', '1-04-2009', '6-30-1973', '4-09-1951', '7-31-1987', '1-21-1972', '9-05-1958', '3-26-1955', '8-09-2013', '7-12-1912', '2-03-1963', '3-20-1982', '4-09-1965', '4-07-1958', '11-27-1987', '8-02-1988', '12-17-2002', '9-09-1998', '6-01-2003', '8-24-1960', '7-09-2006', '1-05-2007', '1-16-1987', '5-10-1977', '2-19-1979', '2-10-2011', '11-16-1954', '10-02-1972', '12-16-2006', '9-21-1981', '4-28-1960', '5-03-1985', '2-06-1970', '4-15-2002', '12-22-1959', '2-09-1974', '5-25-1919', '4-18-1984', '9-15-1951', '2-10-1967', '11-18-1978', '8-26-1988', '10-10-2000', '7-01-1994', '8-29-1970', '10-04-1989', '1-02-1965', '9-17-1961', '1-05-1994', '1-31-1955', '12-01-1944', '9-09-1958', '11-29-1976', '4-14-1980', '1-11-1983', '10-31-1929', '10-10-2013', '3-17-1957', '5-28-1985', '6-30-1974', '8-04-1982', '9-02-2006', '10-01-2002', '11-28-2004', '6-01-1982', '11-25-1978', '12-30-1985', '1-26-1990', '7-20-1942', '7-30-1997', '4-28-1951', '9-18-1994', '11-01-1998', '8-14-1941', '3-21-1956', '12-23-1978', '9-25-1996', '12-05-1921', '11-15-2000', '10-19-1943', '8-11-1957', '9-05-1980', '2-01-1997', '10-30-1930', '9-04-1964', '9-11-1979', '6-07-2008', '12-20-1997', '7-15-1966', '8-21-1992', '2-27-1990', '1-27-1973', '2-16-2014', '7-12-1951', '11-27-2006', '7-13-1968', '8-27-1990', '8-11-1955', '9-22-1960', '7-15-1968', '4-27-1993', '9-07-1923', '9-19-1988', '5-02-1939', '4-14-1953', '9-26-1978', '11-04-1987', '3-27-1990', '10-24-1954', '8-25-1977', '10-14-1952', '8-09-2011', '3-07-1955', '10-23-1957', '9-15-1952', '5-24-1938', '2-21-1968', '11-17-1975', '5-18-1929', '8-14-1978', '9-24-1916', '3-20-1979', '8-29-1990', '2-19-1949', '4-08-1947', '3-07-1999', '7-28-2011', '4-20-1972', '6-25-1999', '5-12-1963', '10-19-1953', '4-20-1968', '11-16-1927', '1-08-2001', '8-15-1984', '3-31-1986', '5-03-2006', '4-18-1979', '8-18-1968', '2-28-1984', '10-13-1969', '8-02-1985', '6-11-2004', '6-25-2015', '1-22-1976', '9-23-1996', '10-09-2000', '5-29-1972', '12-30-1945', '10-05-1930', '10-22-1975', '11-13-1996', '6-20-1969', '3-09-2000', '2-03-2005', '7-07-2006', '11-16-1946', '4-03-2008', '8-13-1961', '3-17-1979', '3-08-2014', '8-16-1954', '6-24-1960', '11-16-1937', '1-17-1936', '4-05-1966', '7-22-1973', '8-12-1958', '3-19-1993', '7-09-1996', '3-17-1965', '2-01-1991', '9-17-1999', '5-04-2002', '11-08-2002', '2-17-1971', '8-17-1983', '2-03-1992', '7-13-1956', '12-29-1962', '4-03-1967', '7-28-1962', '2-25-1981', '10-26-1994', '6-11-2012', '5-24-1981', '8-03-1989', '1-08-1931', '6-22-1934', '6-01-1943', '7-27-1992', '7-11-1945', '5-11-1964', '4-28-1970', '5-05-1983', '1-25-1982', '8-31-1967', '6-17-1971', '3-17-1929', '8-30-1985', '2-04-2015', '4-01-1935', '10-11-1985', '5-09-1995', '8-30-1975', '6-17-1953', '1-14-1959', '4-20-1960', '11-30-1975', '12-15-1942', '1-21-1960', '10-03-1979', '8-25-1978', '6-13-1952', '4-29-2000', '3-03-1978', '3-14-1939', '2-07-1982', '4-04-1984', '11-11-1990', '4-22-1992', '2-26-1941', '1-17-2004', '2-22-1964', '12-04-1964', '8-07-1975', '12-12-1963', '6-11-1931', '3-21-1989', '9-08-1974', '6-07-1943', '12-21-1961', '11-10-1965', '11-21-1971', '6-01-1973', '3-24-1980', '10-01-1981', '12-01-1959', '1-04-1938', '2-26-1979', '2-06-1982', '1-21-1985', '7-23-2007', '11-08-2003', '5-14-1917', '4-10-1952', '2-14-1956', '7-03-1975', '6-28-1985', '1-14-1963', '9-11-2003', '1-13-1970', '6-13-2007', '11-07-1920', '6-30-1962', '9-08-2009', '3-16-1960', '2-01-1957', '2-16-2005', '10-27-1951', '3-31-1965', '12-15-1953', '7-21-1997', '1-27-1928', '6-11-1947', '9-15-1989', '10-02-2015', '12-16-1960', '6-25-1958', '3-17-1946', '8-23-2000', '1-15-1953', '3-08-1964', '3-04-1987', '5-30-1972', '10-09-1935', '9-16-1971', '10-15-1981', '8-07-1994', '11-05-1978', '6-03-1973', '5-12-1968', '2-16-1995', '9-04-1962', '3-07-1938', '11-28-1979', '6-11-2003', '2-04-1966', '9-23-1993', '3-22-1952', '2-09-1921', '10-27-1953', '1-13-1992', '5-23-1976', '6-17-1917', '12-05-1980', '6-14-1995', '8-12-1932', '7-14-1992', '5-20-1964', '4-24-1924', '9-20-2003', '12-03-1993', '7-16-2005', '7-08-2007', '7-03-1968', '3-24-1937', '12-11-1984', '5-21-1955', '12-25-2012', '11-23-1967', '4-17-1967', '10-28-1989', '1-23-1990', '1-01-2007', '8-04-2018', '11-11-1961', '12-29-1972', '9-29-1982', '11-01-2009', '3-05-1957', '10-27-1984', '3-17-1947', '11-15-1974', '9-28-1983', '12-20-1934', '3-31-1956', '11-03-1945', '3-26-1971', '1-06-1968', '7-09-1950', '2-15-1967', '12-11-1957', '4-22-1971', '5-11-1987', '2-03-1980', '12-06-1999', '12-24-1964', '9-30-1980', '2-07-2009', '1-22-1947', '10-10-1955', '8-14-1991', '10-31-1933', '11-09-1933', '2-10-1974', '12-04-1965', '11-13-1988', '8-06-2005', '7-15-1962', '4-19-2000', '9-04-2002', '10-10-1968', '1-10-1991', '4-27-1986', '12-01-1949', '3-02-2001', '12-23-2003', '4-29-2013', '10-03-1986', '3-10-2017', '3-31-1971', '11-27-1983', '6-08-1924', '7-11-1961', '10-03-1978', '12-05-2013', '4-14-1963', '9-09-1988', '11-26-1966', '8-21-1947', '7-13-1969', '10-27-2003', '9-16-1984', '6-06-1920', '12-22-1998', '10-07-2012', '7-27-1960', '9-18-1932', '1-28-1961', '5-08-1997', '10-06-1981', '8-29-1933', '9-14-1950', '9-06-1952', '10-19-1962', '9-11-1945', '12-08-1977', '3-06-1979', '7-23-1981', '10-22-2009', '8-16-2014', '4-11-2008', '1-09-1993', '4-23-1959', '10-10-1974', '2-14-1951', '12-16-1949', '10-24-1967', '2-14-1997', '10-15-1987', '11-01-1945', '1-28-1947', '4-29-1995', '8-14-1935', '1-17-1949', '4-28-1947', '7-08-1965', '8-07-1993', '6-21-2000', '9-12-1933', '2-28-1989', '8-30-1984', '5-17-2007', '12-06-1972', '2-05-1996', '7-13-2011', '4-04-1974', '12-08-1988', '5-08-2003', '8-27-1954', '10-02-1919', '7-03-1997', '4-17-1972', '1-13-2004', '8-10-1934', '7-24-1951', '11-08-1940', '7-06-1965', '12-29-1965', '11-22-1966', '6-09-1999', '1-12-1970', '2-21-2014', '10-07-1935', '8-22-1981', '4-05-2000', '5-03-1995', '9-16-2007', '8-01-2010', '3-22-2014', '10-06-1959', '6-03-2006', '8-08-1956', '12-25-2002', '7-16-1922', '9-19-1979', '11-10-1944', '1-13-1954', '4-03-1939', '12-23-1948', '3-11-1983', '3-04-2013', '7-11-1983', '4-27-1974', '5-26-2009', '1-08-1959', '9-21-1962', '7-03-1982', '5-11-2004', '4-12-2005', '1-16-1975', '9-17-2006', '6-23-1949', '8-24-1951', '5-25-1995', '8-03-1969', '11-16-1994', '7-05-2001', '12-18-2016', '7-12-1984', '8-08-1937', '4-27-1988', '10-04-1970', '4-17-1966', '8-02-1964', '5-26-1952', '12-21-1977', '7-26-1986', '12-24-1923', '1-15-2002', '8-30-1955', '8-21-1952', '11-05-2010', '6-08-2006', '8-21-1949', '8-08-1954', '9-21-1969', '6-24-1956', '8-05-2016', '6-16-1983', '7-28-1968', '1-23-1980', '5-02-1927', '9-13-1987', '9-19-2003', '4-17-2009', '1-16-1959', '12-08-1956', '5-25-2011', '9-20-2011', '8-26-1993', '2-18-1970', '7-04-1973', '12-03-1944', '10-22-1974', '6-17-1975', '3-01-1990', '1-10-1923', '8-25-1950', '6-30-1943', '10-09-1966', '4-04-1978', '12-28-1997', '3-15-2016', '2-18-2018', '11-14-1925', '3-17-1960', '10-04-1960', '11-03-1964', '8-09-1995', '5-31-1985', '7-15-1965', '4-05-1960', '1-09-1964', '6-26-1987', '10-20-1989', '3-18-1997', '4-06-1958', '1-13-1965', '9-23-1950', '11-09-1935', '4-26-1983', '11-12-2001', '2-28-1942', '1-07-1948', '5-02-1953', '9-20-1990', '4-15-1969', '8-15-1976', '8-07-1943', '6-25-1998', '3-08-1968', '6-19-1984', '6-17-1929', '3-11-1951', '8-14-2000', '7-15-1956', '11-11-2011', '3-12-2018', '12-31-1985', '4-07-1922', '11-04-1957', '6-12-1988', '2-21-2017', '6-03-1955', '11-20-1975', '3-02-1957', '12-10-2004', '12-09-2011', '8-06-1966', '8-31-1972', '9-05-1946', '1-18-1939', '12-12-1953', '6-21-1947', '9-29-1960', '10-08-2008', '8-15-1935', '8-21-1994', '1-15-2009', '12-04-1946', '7-30-1970', '4-26-1994', '9-15-1988', '10-13-1930', '5-27-1950', '7-12-1945', '2-02-1974', '4-04-1977', '10-15-1943', '8-11-1980', '10-12-1972', '10-19-1988', '10-12-1973', '10-10-1961', '11-05-1951', '8-27-1923', '12-11-2013', '4-19-1989', '4-21-1936', '8-19-1959', '11-07-1960', '12-10-1988', '12-07-2016', '10-30-1935', '1-21-1976', '1-31-1929', '10-08-1951', '9-24-2007', '2-03-1951', '6-16-1953', '2-15-1961', '12-08-1963', '11-19-1984', '3-03-1977', '11-01-1946', '3-05-1963', '3-19-2016', '11-23-1964', '10-03-1995', '12-29-1967', '2-28-1993', '12-25-1986', '9-21-1989', '1-11-1991', '4-22-1968', '8-12-1974', '12-11-2008', '11-15-1956', '3-07-2007', '6-19-1938', '2-20-1944', '5-02-1959', '12-27-1991', '7-24-1928', '3-26-1952', '12-05-1931', '3-29-1952', '4-02-1986', '6-19-1954', '1-06-1975', '7-18-1950', '5-06-1962', '7-19-1919', '10-26-1929', '4-08-1957', '3-28-1941', '4-19-1928', '5-30-1945', '2-25-1948', '3-27-1958', '8-08-1963', '10-03-1946', '2-07-1971', '11-26-1996', '9-02-1976', '7-12-2004', '1-13-1993', '2-14-2010', '11-04-2010', '11-20-1955', '11-09-1971', '6-18-1998', '3-07-1997', '11-13-1969', '4-06-1990', '8-07-2002', '11-11-1935', '9-22-1974', '7-09-1997', '12-09-1949', '8-29-1960', '2-01-1975', '2-05-2006', '5-15-1956', '8-30-1932', '12-26-1958', '4-21-1970', '6-05-1959', '5-27-1944', '2-12-1970', '9-02-1977', '12-16-1978', '8-01-1980', '1-14-1983', '2-01-1958', '12-28-1976', '3-18-2006', '3-03-1973', '2-15-1964', '11-02-1986', '9-03-1989', '3-19-1932', '6-09-1950', '9-07-1925', '5-28-1971', '1-10-1930', '8-29-1996', '7-27-1955', '6-30-1959', '7-31-1973', '12-10-2005', '1-18-1972', '9-23-1991', '1-20-1950', '1-02-2006', '3-07-1976', '5-06-1970', '10-08-1947', '12-16-1973', '9-06-1921', '10-17-1913', '8-15-1959', '8-16-1972', '11-04-1972', '5-18-1935', '1-30-1979', '3-26-1954', '1-08-1928', '7-15-1969', '3-12-1967', '10-06-1946', '9-19-1992', '9-18-2001', '10-07-2002', '3-06-2003', '7-31-1960', '5-11-1971', '10-02-1971', '7-21-1977', '6-09-1946', '2-07-1981', '9-24-1972', '5-12-1962', '12-17-1960', '1-18-1960', '9-15-1946', '12-11-2004', '9-08-1968', '4-01-1968', '12-29-1951', '9-23-1989', '10-31-1995', '8-27-1937', '1-06-1945', '6-23-1957', '12-20-2001', '6-10-1970', '1-03-1947', '2-02-1949', '1-27-2001', '8-16-1965', '10-30-1974', '2-16-1998', '9-07-1984', '12-09-1938', '5-12-1971', '10-02-1926', '1-26-1935', '2-16-1968', '6-13-1971', '9-22-1981', '4-27-2007', '11-20-2000', '5-04-1966', '3-06-1955', '2-11-1977', '9-16-1931', '8-26-1978', '11-14-1970', '4-27-1980', '6-22-1982', '12-14-1987', '8-15-2002', '11-19-2005', '2-03-1998', '9-05-1999', '1-14-1946', '8-27-2010', '1-12-1956', '3-14-1970', '3-14-2002', '2-13-2013', '12-16-1918', '10-10-2001', '1-29-2018', '1-09-1998', '1-25-1947', '2-16-1972', '4-20-1990', '8-28-1939', '4-30-1954', '3-10-1949', '10-16-1970', '9-27-1973', '10-26-1932', '1-29-2013', '2-22-1943', '6-15-2001', '9-21-1993', '9-26-1926', '6-09-1936', '11-01-1979', '7-16-1948', '9-28-1968', '4-28-1982', '12-12-1985', '11-15-2017', '5-17-1986', '11-26-1983', '3-02-1992', '8-09-2010', '3-17-1996', '3-31-1984', '5-16-1948', '10-29-1952', '1-23-1957', '2-05-1960', '3-05-1967', '12-20-1952', '2-29-1964', '6-13-1972', '1-25-1929', '9-10-1952', '10-11-1988', '7-19-1960', '4-07-1918', '3-12-1985', '1-20-1934', '2-15-1936', '5-30-1970', '10-19-1968', '11-15-1987', '12-03-1972', '2-06-2007', '11-17-1955', '4-09-2009', '12-22-1987', '12-25-1976', '3-31-2006', '11-23-1998', '12-29-1994', '1-13-1948', '5-11-1996', '5-06-1969', '1-17-1967', '11-08-1965', '10-31-1972', '2-05-1979', '2-01-1985', '6-21-1996', '10-14-2013', '12-27-1947', '8-03-1970', '5-31-2000', '11-09-1995', '4-01-1997', '3-30-1977', '1-14-1970', '7-26-1944', '10-15-1986', '7-03-2009', '6-04-1976', '5-09-1982', '4-09-1945', '2-01-1932', '12-07-1996', '9-14-1953', '3-30-1920', '3-08-1926', '4-22-1974', '3-08-1966', '3-01-1978', '10-01-1938', '9-26-1949', '1-04-2002', '12-17-1943', '4-08-1922', '8-08-2003', '10-23-1946', '2-23-1948', '11-11-1947', '12-10-1949', '4-17-1959', '8-22-1930', '12-06-1936', '9-21-2010', '12-27-1968', '12-04-1935', '4-21-1950', '1-27-1966', '8-06-1991', '4-21-1942', '3-12-1992', '8-29-1961', '8-06-2008', '7-05-1970', '11-30-1955', '7-06-2011', '7-14-2001', '12-21-1975', '8-16-2010', '8-06-1936', '7-28-1945', '7-18-1968', '12-09-1992', '12-10-1935', '9-18-1944', '7-11-1972', '12-09-1973', '1-23-1982', '6-28-1983', '9-27-1989', '8-16-1920', '10-09-1974', '9-01-1975', '9-27-1949', '11-24-1931', '6-13-1961', '1-18-1959', '10-22-1963', '1-10-1974', '10-20-1977', '2-10-1978', '8-25-1928', '12-15-2008', '9-17-1929', '7-16-1957', '1-22-1962', '12-08-1934', '2-25-1960', '1-13-1968', '12-28-1973', '11-19-1943', '10-08-1991', '9-27-1944', '2-24-1973', '4-14-1958', '12-07-2004', '6-26-1994', '8-13-2004', '1-17-2003', '10-04-1928', '12-04-1960', '4-09-2008', '10-10-1970', '9-06-1977', '12-21-1980', '6-30-1945', '2-03-1964', '4-06-1994', '12-22-1995', '10-06-1937', '6-04-1967', '6-22-1967', '9-18-1984', '2-09-1938', '1-25-1990', '6-18-1972', '12-09-1979', '1-10-1954', '8-18-2012', '11-28-2009', '8-28-1976', '9-27-2008', '11-11-1946', '10-02-1969', '3-07-1924', '12-06-1969', '4-05-1978', '7-31-1964', '5-21-2000', '4-25-2007', '9-02-1964', '8-26-1969', '5-15-1970', '7-04-1922', '4-19-1945', '12-14-1977', '5-25-2000', '6-04-2002', '1-08-2006', '1-14-1980', '12-11-1999', '12-29-1964', '8-05-1969', '10-12-1985', '7-24-1976', '10-07-2007', '10-27-2011', '4-24-1980', '3-08-1994', '11-03-1973', '12-31-1967', '7-08-1961', '9-24-1959', '8-28-1991', '1-05-1967', '2-20-1991', '8-05-1994', '5-13-1959', '1-28-1986', '5-18-1958', '1-18-1996', '2-19-1982', '11-08-1997', '6-30-1961', '11-06-1924', '4-16-2008', '1-17-1923', '12-12-1974', '7-31-1944', '1-31-1946', '3-15-1948', '12-08-1972', '9-15-1980', '7-06-1982', '9-13-1997', '7-26-1988', '5-01-1986', '8-27-1985', '4-12-1990', '10-01-1942', '4-30-1936', '5-16-1936', '3-11-1943', '11-21-1978', '12-21-1939', '3-15-1981', '10-31-1981', '9-02-1944', '10-16-1988', '8-21-1967', '2-14-1942', '1-17-1989', '3-28-1933', '12-23-1987', '7-13-1949', '7-25-1957', '10-29-1940', '3-22-1978', '12-21-1996', '2-24-1931', '11-08-1943', '7-25-1980', '9-30-1970', '7-20-1951', '11-26-1968', '6-08-1988', '3-16-1991', '11-18-2006', '3-21-1932', '12-02-2014', '12-21-1990', '6-14-1952', '7-01-1957', '8-24-1938', '9-03-1946', '1-19-1952', '11-13-1966', '2-07-1967', '7-12-1997', '1-11-1937', '1-15-1966', '9-15-1964', '2-26-1947', '7-29-1998', '7-19-1967', '3-04-1917', '1-30-1975', '5-31-1977', '8-14-1968', '3-12-1997', '6-26-2003', '3-02-1979', '11-28-2001', '8-17-1963', '6-30-2009', '4-30-1974', '8-09-1931', '5-19-1972', '10-29-1992', '3-04-1997', '7-15-1975', '6-09-1993', '8-23-2001', '11-08-2007', '4-06-1993', '9-03-1925', '7-02-1963', '2-06-1992', '7-27-1990', '7-27-2006', '8-30-2014', '5-09-1933', '1-19-1960', '5-12-1967', '12-21-1967', '3-25-1937', '6-10-1990', '6-05-1987', '8-31-1934', '9-02-2000', '6-12-1967', '1-12-1951', '9-15-1954', '7-07-1980', '10-30-1942', '12-31-2017', '1-29-1936', '12-20-1972', '7-09-1973', '1-17-1999', '9-03-1962', '2-18-1966', '3-22-1986', '8-05-1984', '11-17-1988', '5-16-1947', '10-28-1974', '8-24-1946', '1-13-1984', '9-02-1948', '8-04-2003', '2-21-1980', '6-21-1983', '5-16-1938', '7-24-1966', '5-23-2004', '1-19-1955', '3-06-2018', '12-22-1962', '7-26-1975', '12-19-1984', '8-17-2004', '7-15-1960', '4-10-2006', '11-07-2008', '11-19-2013', '4-12-1964', '4-03-1954', '5-23-1960', '4-11-1982', '1-07-1994', '8-05-1950', '3-23-2005', '7-17-2014', '1-29-1997', '12-06-1968', '7-03-1970', '3-20-1964', '8-04-1968', '3-21-1980', '7-14-1977', '4-01-1991', '7-12-1995', '2-20-1984', '12-23-1946', '7-27-2000', '4-10-2010', '11-22-1975', '4-01-2002', '9-04-2010', '4-15-1985', '11-25-1932', '11-08-1961', '12-24-1999', '3-22-2000', '4-26-1982', '7-29-1951', '6-07-1992', '11-15-1978', '11-28-1989', '11-27-1996', '8-29-1979', '1-21-1959', '1-23-1985', '11-23-1982', '5-05-1976', '3-19-1998', '8-23-1942', '3-23-1963', '11-16-1958', '8-31-1982', '3-09-2009', '7-21-1949', '7-07-2014', '2-13-1965', '2-16-2003', '6-23-1959', '10-16-2000', '8-06-1980', '7-17-1963', '3-05-1969', '11-25-1985', '4-13-1987', '9-14-1980', '11-20-1964', '1-18-1990', '1-18-1946', '8-01-1977', '10-25-1999', '5-24-1952', '6-20-2008', '3-01-1976', '8-20-2008', '9-23-1927', '3-27-1977', '7-10-2017', '6-03-1988', '11-04-1980', '10-04-1986', '1-01-2002', '3-07-1978', '6-02-1937', '5-15-1991', '9-03-1997', '12-28-1946', '2-16-1967', '6-27-1958', '3-31-1995', '12-13-1967', '11-23-1976', '11-28-1971', '10-01-1977', '3-12-1996', '3-30-2000', '8-22-1985', '5-29-1995', '7-24-1973', '12-11-1965', '10-21-1948', '6-23-2010', '11-21-2015', '5-12-1942', '12-25-1952', '12-05-1981', '7-05-2003', '1-12-2007', '12-15-1981', '6-02-2005', '11-25-1967', '12-31-1954', '2-06-1996', '11-02-1938', '7-01-1948', '5-08-1972', '5-02-2004', '10-16-1944', '9-30-1975', '11-15-1952', '8-02-1979', '10-22-1985', '2-07-1991', '9-25-2009', '6-06-1971', '2-10-1936', '7-30-1962', '11-05-1976', '3-02-1948', '2-26-1981', '4-07-1957', '5-03-2009', '5-18-2018', '9-27-1942', '3-04-1977', '2-13-1970', '5-03-1986', '5-13-1995', '8-22-2002', '8-13-2008', '8-21-1942', '12-29-1961', '10-19-2013', '9-28-2018', '5-05-1957', '5-11-1973', '7-21-1951', '6-05-1983', '1-29-1989', '2-24-1989', '1-22-1996', '12-20-1995', '12-08-1937', '7-15-1947', '12-31-1968', '1-25-2010', '9-13-1994', '3-21-1991', '2-17-1979', '11-20-1933', '2-08-1993', '4-13-1982', '1-18-1994', '12-29-1954', '1-26-1961', '10-10-1944', '1-27-1951', '11-05-1946', '7-31-2015', '11-14-1989', '11-26-1991', '1-30-1974', '11-24-2001', '2-19-2003', '10-03-2013', '4-12-1960', '1-03-1961', '8-08-1984', '12-03-2008', '10-31-1973', '2-03-1975', '12-07-2011', '10-10-1997', '6-08-1954', '11-16-1981', '10-06-1927', '12-31-1957', '4-17-1992', '1-05-1995', '2-27-2001', '7-20-1960', '10-21-1971', '10-19-1934', '11-19-1936', '12-13-1950', '12-22-1950', '6-10-1997', '8-04-1939', '1-06-1946', '1-02-1971', '6-03-1963', '3-25-1991', '9-11-1991', '11-20-1993', '1-16-1928', '12-10-1928', '3-05-2000', '3-23-1946', '8-06-1949', '4-08-1951', '10-13-1991', '9-16-2000', '1-08-1975', '8-29-1981', '10-20-1919', '1-29-1963', '3-30-1983', '3-24-2006', '1-22-2010', '12-14-2006', '2-10-1930', '3-27-1986', '2-12-1926', '12-08-1995', '12-06-1984', '6-22-1951', '7-22-2016', '12-25-1954', '11-27-1965', '6-28-1969', '11-10-1962', '1-16-1999', '12-15-1944', '6-01-1991', '7-18-1933', '4-21-1921', '6-11-1933', '4-02-1956', '8-08-1951', '5-29-2010', '6-26-1959', '9-24-1975', '11-17-2006', '8-11-1979', '3-30-1986', '3-20-1966', '11-29-1977', '8-23-1988', '3-08-1965', '4-12-1988', '2-03-1988', '2-07-1953', '5-07-1994', '1-09-1946', '7-19-1961', '11-29-1987', '1-26-2008', '7-30-1969', '5-27-1972', '2-27-1950', '8-12-1936', '11-12-1971', '5-06-1935', '9-25-1985', '2-24-1939', '9-09-1973', '5-25-1987', '3-19-1968', '10-15-1951', '3-01-1988', '1-16-1965', '2-12-1990', '9-21-1995', '11-29-2009', '3-15-2008', '5-22-1931', '6-03-1972', '4-22-1966', '1-12-1989', '12-25-1999', '6-10-1991', '9-14-2002', '3-03-1942', '2-14-1991', '2-11-2018', '11-29-1970', '11-13-1951', '4-07-1999', '9-27-1965', '5-10-1975', '7-07-1948', '2-08-1963', '12-16-1981', '3-29-1995', '8-18-1996', '8-24-2003', '2-20-1956', '2-01-1954', '12-12-1986', '7-20-1999', '11-04-1940', '11-18-1988', '3-14-1953', '12-24-1966', '12-08-1987', '5-10-1930', '4-16-1988', '7-02-2004', '4-02-1951', '4-07-1981', '3-16-1984', '12-21-1952', '2-03-1982', '11-15-1945', '5-28-1935', '3-13-1974', '6-26-1950', '4-04-1970', '8-15-1966', '8-20-1957', '1-02-1984', '6-09-1973', '7-23-1991', '12-17-1955', '9-08-1932', '7-24-1992', '8-21-2004', '1-21-1967', '1-26-1947', '10-15-1973', '12-03-1987', '5-11-1953', '11-11-1926', '10-31-1978', '1-27-1959', '9-04-1971', '9-17-1932', '2-27-1975', '6-01-1976', '10-29-1953', '8-21-1989', '10-20-1963', '3-12-2009', '11-28-1952', '3-18-1957', '1-21-1943', '4-27-1994', '4-19-1983', '4-02-1955', '4-30-1946', '5-26-2008', '10-09-1964', '9-08-1959', '1-11-1980', '11-13-1978', '4-09-1952', '1

## Normalizando columna Operator

In [438]:
#Normalizando columna Operator eliminando - y ?

crash_plane['operator'] = crash_plane['operator'].str.replace('-', '')
crash_plane['operator'] = crash_plane['operator'].str.replace('?', 'sin datos')

crash_plane['operator']

0                      Military  U.S. Army
1                                sin datos
2                      Military  U.S. Navy
3                                  Private
4                    Military  German Navy
5                    Military  German Navy
6                    Military  German Navy
7                    Military  German Navy
8                    Military  German Army
9                    Military  German Navy
10                   Military  German Navy
11                   Military  German Army
12                   Military  German Navy
13                   Military  German Army
14                   Military  German Navy
15                   Military  German Navy
16                   Military  German Navy
17                               sin datos
18                   Military  German Navy
19                   Military  German Navy
20                   Military  German Navy
21                   Military  German Navy
22                   Military  German Navy
23                  US Aerial Mail Service
24                  US Aerial Mail Service
25                  US Aerial Mail Service
26                         Caproni Company
27           Aircraft Transport and Travel
28                  US Aerial Mail Service
29           Aircraft Transport and Travel
                       ...
5753                         Swan Aviation
5754                       ETA Air Charter
5755                    Air Cargo Carriers
5756                  A&C Big Sky Aviation
5757                            Summit Air
5758                     Myanmar Air Force
5759                          Angel Flight
5760                                  USMC
5761     Valan International Cargo Charter
5762                       Costal Aviation
5763                    West Wind Aviation
5764                             Naure Air
5765    People's Liberation Army Air Force
5766                              Papillon
5767                      Saratov Airlines
5768                  Iran Aseman Airlines
5769           Military  Russian Air Force
5770                   Liberty Helicopters
5771                     USBangla Airlines
5772                      Lite Air Express
5773          Military  Algerian Air Force
5774                    Southwest Airlines
5775                Military  US Air Force
5776       Cubana (leased from Global Air)
5777                               Fly SAX
5778                             Rovos Air
5779                                Ju Air
5780                           Air Niugini
5781                              Lion Air
5782                   Fly Jamaica Airways
Name: operator, Length: 5783, dtype: object

## Normalizando columna Flight_no

In [439]:
crash_plane['flight_no'] = crash_plane['flight_no'].astype('str')
crash_plane['flight_no'].dtype

crash_plane['flight_no'] = crash_plane['flight_no'].replace('?','0')
crash_plane['flight_no'] = crash_plane['flight_no'].replace('F-AIKG','0')
crash_plane['flight_no'] = crash_plane['flight_no'].replace('15A','15')

crash_plane['flight_no']


#data["Age"]= data["Age"].replace(25.0, "Twenty five")
#filter = data["Age"]=="Twenty five"
  
# printing only filtered columns 
#data.where(filter).dropna()

0           0
1           0
2           0
3           0
4           0
5           0
6           0
7           0
8           0
9           0
10          0
11          0
12          0
13          0
14          0
15          0
16          0
17          0
18          0
19          0
20          0
21          0
22          0
23          0
24          0
25          0
26          0
27          0
28          0
29          0
        ...
5753        0
5754        0
5755        0
5756        0
5757      409
5758        0
5759        0
5760        0
5761        0
5762        0
5763        0
5764        0
5765        0
5766        0
5767      703
5768     3704
5769        0
5770        0
5771      221
5772        0
5773        0
5774     1380
5775        0
5776      972
5777    50102
5778        0
5779        0
5780        0
5781      610
5782        0
Name: flight_no, Length: 5783, dtype: object

## Normalizando route

In [440]:
crash_plane['route'] = crash_plane['route'].replace('?','0')
crash_plane['route'] = crash_plane['route'].replace('0','sin datos')

crash_plane['route']

0                                       Demonstration
1                                            Air show
2                                         Test flight
3                                           sin datos
4                                           sin datos
5                                           sin datos
6                                           sin datos
7                                           sin datos
8                                           sin datos
9                                           sin datos
10                                          sin datos
11                                          sin datos
12                                          sin datos
13                                          sin datos
14                                          sin datos
15                                          sin datos
16                                          sin datos
17                                          sin datos
18                                          sin datos
19                                          sin datos
20                                          sin datos
21                                          sin datos
22                                          sin datos
23                                          sin datos
24                                          sin datos
25                                          sin datos
26                                    Venice  Taliedo
27                                          sin datos
28                                          sin datos
29                                          sin datos
                            ...
5753                               Istanbul - Bozuyuk
5754             Beira, Mozambique - Harare, Zimbabwe
5755                          Louisville - Charleston
5756                  Philadelphia, PA - Teteboro, NJ
5757                                        sin datos
5758                                   Myeik - Yangon
5759                            Suttontown - Adelaide
5760                 Cherry Point, NC - El Centro, CA
5761                           Burkina Faso - Abidjan
5762                               Arusha - Serengeti
5763                       Fond-du-Lac - Stony Rapids
5764                          Punta Islita - San Jose
5765                                        sin datos
5766                                      Sightseeing
5767                                    Moscow - Orsk
5768                                   Tehran - Yasuj
5769    Kuweires Air Base - Latakia-Khmeimim Air Base
5770                                      Sightseeing
5771                                Dhaka - Kathmandu
5772                                 Plaridel - Laoag
5773                   Boufarik AB - Bechar - Tindouf
5774                                New York - Dallas
5775                                Savannah - Tuscon
5776                                  Havana- Holguin
5777                                 Kitale - Nairobi
5778                                      Test Flight
5779                              Locorno - Dubendorf
5780                                  Pohnpei - Chuuk
5781                         Jakarta - Pangkal Pinang
5782                             Georgetown - Toronto
Name: route, Length: 5783, dtype: object

## Normalizando columna AcType

In [441]:
import re

crash_plane['ac_type'] = crash_plane['ac_type'].replace('\)','')
crash_plane['ac_type'] = crash_plane['ac_type'].replace('\(','')

#crash_plane['ac_type'] = crash_plane['ac_type'].str.replace(r'\s+\(\w+\)\s+', '', regex=True)

crash_plane['ac_type']

0                            Wright Flyer III
1                              Wright Byplane
2                                   Dirigible
3                            Curtiss seaplane
4                      Zeppelin L-1 (airship)
5                      Zeppelin L-2 (airship)
6                      Zeppelin L-8 (airship)
7                     Zeppelin L-10 (airship)
8               Schutte-Lanz S-L-10 (airship)
9                     Zeppelin L-32 (airship)
10                    Zeppelin L-31 (airship)
11                   Super Zeppelin (airship)
12                    Zeppelin L-34 (airship)
13                                    Airship
14               Schutte-Lanz S-L-9 (airship)
15                    Zeppelin L-22 (airship)
16                    Zeppelin L-43 (airship)
17                   Zepplin LZ-95 (air ship)
18                    Zeppelin L-23 (airship)
19                    Zeppelin L-44 (airship)
20                    Zeppelin L-59 (airship)
21                    Zeppelin L-70 (airship)
22                    Zeppelin L-53 (airship)
23                          De Havilland DH-4
24                          De Havilland DH-4
25                          De Havilland DH-4
26                              Caproni Ca.48
27                          De Havilland DH-4
28                              Curtiss R-4LM
29                          De Havilland DH-4
                        ...
5753                           Sikorsky S-76C
5754              Britten-Norman BN2 Islander
5755                           Shorts 300-200
5756                          Learjet 35A-452
5757                         Let L-410UVP-E20
5758                        Shaanxi Y-8F-200W
5759                     Socata TB1-10 Tobago
5760                Lockheed KC-130T Hercules
5761                        Antonov AN-26-100
5762                Cessna 208B Grand Caravan
5763                                ATR42-320
5764                Cessna 208B Grand Caravan
5765                          Shaanxi Y-8GX-3
5766                      Eurocopter EC 130B4
5767                       Antonov AN-148-100
5768                     Iran Aseman Airlines
5769                            Antonov An-26
5770                      Eurocopter AS 350B2
5771    de Havilland Canada DHC-8-402Q Dash 8
5772                       Piper PA-32RT-300T
5773                           Ilyushin 76-TD
5774                           Boeing 737-7H4
5775                Lockheed HC-130H Hercules
5776                           Boeing 737-201
5777                Cessna 208B Grand Caravan
5778                           Convair CV-340
5779                            Junkers JU-52
5780                           Boeing 737-8BK
5781                         Boeing 737-MAX 8
5782                           Boeing 757-N23
Name: ac_type, Length: 5783, dtype: object

## Normalizando aboard

In [442]:
import re

crash_plane['aboard'] = crash_plane['aboard'].str.replace('(', '')
crash_plane['aboard'] = crash_plane['aboard'].str.replace(')', '')
crash_plane['aboard'] = crash_plane['aboard'].str.replace(':', '')



crash_plane['aboard'] = crash_plane['aboard'].str.replace(r'passengers\d+\s+crew\d+', '', regex=True)
crash_plane['aboard'] = crash_plane['aboard'].str.replace(r'passengers\D+\s+crew\D+', '', regex=True)
crash_plane['aboard'] = crash_plane['aboard'].str.replace(r'passengers\d', '', regex=True)
crash_plane['aboard'] = crash_plane['aboard'].str.replace(r'\s+passengers','' , regex=True)
crash_plane['aboard'] = crash_plane['aboard'].str.replace(r'\s+crew','' , regex=True)

crash_plane['aboard'] = crash_plane['aboard'].str.replace('\xa0', '')
crash_plane['aboard'] = crash_plane['aboard'].str.replace(':', '')
crash_plane['aboard'] = crash_plane['aboard'].str.replace('?', '')
crash_plane['aboard'] = crash_plane['aboard'].str.replace(' ', '')
crash_plane['aboard'] = crash_plane['aboard'].replace('',0)

#print(crash_plane['aboard'].iloc[5])
print(crash_plane['aboard'])
#crash_plane['aboard'] = crash_plane['aboard'].str.replace('passengers', '')
#crash_plane['aboard'] = crash_plane['aboard'].str.replace('crew', '')
#print(set(crash_plane['aboard']))
#crash_plane['ac_type'] = crash_plane['ac_type'].replace('\(','')

0         2
1         1
2         5
3         1
4        20
5        30
6        41
7        19
8        20
9        22
10       19
11       28
12       20
13       20
14       23
15       21
16       24
17       16
18       18
19       18
20       23
21       22
22       19
23        1
24        1
25        1
26       14
27        1
28        1
29        0
       ...
5753      7
5754      6
5755      2
5756      2
5757      3
5758    122
5759      3
5760     16
5761     10
5762     11
5763     25
5764     12
5765     12
5766      7
5767     71
5768     66
5769     39
5770      6
5771     71
5772      5
5773    257
5774    149
5775      9
5776    113
5777     10
5778     19
5779     20
5780     47
5781    189
5782    128
Name: aboard, Length: 5783, dtype: object

## Normalizando fatalidades

In [443]:
#Me encuentro con passengers y crew que quiero eliminar y dejar solo un numero que muestre las fatalidades

crash_plane['fatalities']

0            1   (passengers:1  crew:0)
1            1   (passengers:0  crew:0)
2            5   (passengers:0  crew:5)
3            1   (passengers:0  crew:1)
4           14   (passengers:?  crew:?)
5           30   (passengers:?  crew:?)
6           21   (passengers:?  crew:?)
7           19   (passengers:?  crew:?)
8           20   (passengers:?  crew:?)
9           22   (passengers:?  crew:?)
10         19   (passengers:0  crew:19)
11          27   (passengers:?  crew:?)
12          20   (passengers:?  crew:?)
13          20   (passengers:?  crew:?)
14          23   (passengers:?  crew:?)
15          21   (passengers:?  crew:?)
16          24   (passengers:?  crew:?)
17          14   (passengers:?  crew:?)
18          18   (passengers:?  crew:?)
19          18   (passengers:?  crew:?)
20          23   (passengers:?  crew:?)
21          22   (passengers:?  crew:?)
22          19   (passengers:?  crew:?)
23           1   (passengers:0  crew:1)
24           1   (passengers:0  crew:1)
25           1   (passengers:0  crew:1)
26         14   (passengers:12  crew:2)
27           1   (passengers:0  crew:1)
28           1   (passengers:0  crew:1)
29           0   (passengers:?  crew:?)
                     ...
5753         7   (passengers:5  crew:2)
5754         6   (passengers:4  crew:2)
5755         2   (passengers:0  crew:2)
5756         2   (passengers:0  crew:2)
5757         2   (passengers:0  crew:2)
5758    122   (passengers:108  crew:14)
5759         3   (passengers:2  crew:1)
5760       16   (passengers:14  crew:2)
5761         4   (passengers:4  crew:0)
5762       11   (passengers:10  crew:1)
5763         1   (passengers:1  crew:0)
5764       12   (passengers:10  crew:2)
5765        12   (passengers:7  crew:5)
5766         3   (passengers:3  crew:0)
5767       71   (passengers:65  crew:6)
5768       66   (passengers:60  crew:6)
5769       39   (passengers:33  crew:6)
5770         5   (passengers:5  crew:0)
5771       51   (passengers:47  crew:4)
5772         5   (passengers:3  crew:2)
5773    257   (passengers:247  crew:10)
5774         1   (passengers:1  crew:0)
5775         9   (passengers:0  crew:9)
5776     112   (passengers:106  crew:6)
5777        10   (passengers:8  crew:2)
5778         1   (passengers:0  crew:1)
5779       20   (passengers:17  crew:3)
5780         1   (passengers:1  crew:0)
5781     189   (passengers:181  crew:8)
5782         1   (passengers:1  crew:0)
Name: fatalities, Length: 5783, dtype: object

In [446]:
#Sigo utilizando la libreria re para dejar lista la base 

crash_plane['fatalities'] = crash_plane['fatalities'].str.replace('(', '')
crash_plane['fatalities'] = crash_plane['fatalities'].str.replace(')', '')
crash_plane['fatalities'] = crash_plane['fatalities'].str.replace(':', '')



crash_plane['fatalities'] = crash_plane['fatalities'].str.replace(r'passengers\d+\s+crew\d+', '', regex=True)
crash_plane['fatalities'] = crash_plane['fatalities'].str.replace(r'passengers\D+\s+crew\D+', '', regex=True)
crash_plane['fatalities'] = crash_plane['fatalities'].str.replace(r'passengers\d', '', regex=True)
crash_plane['fatalities'] = crash_plane['fatalities'].str.replace(r'\s+passengers','' , regex=True)
crash_plane['fatalities'] = crash_plane['fatalities'].str.replace(r'\s+crew','' , regex=True)

crash_plane['fatalities'] = crash_plane['fatalities'].str.replace('\xa0', '')
crash_plane['fatalities'] = crash_plane['fatalities'].str.replace(':', '')
crash_plane['fatalities'] = crash_plane['fatalities'].str.replace('?', '')
crash_plane['fatalities'] = crash_plane['fatalities'].str.replace(' ', '')
crash_plane['fatalities'] = crash_plane['fatalities'].replace('',0)

In [390]:
crash_plane['fatalities']

0         1
1         1
2         5
3         1
4        14
5        30
6        21
7        19
8        20
9        22
10       19
11       27
12       20
13       20
14       23
15       21
16       24
17       14
18       18
19       18
20       23
21       22
22       19
23        1
24        1
25        1
26       14
27        1
28        1
29        0
       ...
5753      7
5754      6
5755      2
5756      2
5757      2
5758    122
5759      3
5760     16
5761      4
5762     11
5763      1
5764     12
5765     12
5766      3
5767     71
5768     66
5769     39
5770      5
5771     51
5772      5
5773    257
5774      1
5775      9
5776    112
5777     10
5778      1
5779     20
5780      1
5781    189
5782      1
Name: fatalities, Length: 5783, dtype: object

## Una vez normalizada cada columna y entender los datos, procedo a cambiar los tipos

In [424]:
#Le damos un vistazo nuevamente
crash_plane.head(2)

,date,time,location,operator,flight_no,route,ac_type,registration,cn_ln,aboard,fatalities,ground,summary
0,9-17-1908,17:18,"Fort Myer, Virginia",Military U.S. Army,0,Demonstration,Wright Flyer III,?,1,2,1,0,"During a demonstration flight, a U.S. Army fly..."
1,9-07-1909,00:00,"Juvisy-sur-Orge, France",sin datos,0,Air show,Wright Byplane,SC1,?,1,1,0,Eugene Lefebvre was the first pilot to ever be...

In [447]:
#Cambiando formatos de variables


crash_plane['date'] =  pd.to_datetime(crash_plane['date'], format='%m-%d-%Y')
#crash_plane['time'] =  pd.to_datetime(crash_plane['time'], format='%H%M')

crash_plane['aboard'] = crash_plane['aboard'].astype(int)
crash_plane['fatalities'] = crash_plane['fatalities'].astype(int)

In [449]:
crash_plane.dtypes

print("Ahora, la columna date es de tipo fecha")
print("Las columnas aboard y fatalities son de tipo int")

date            datetime64[ns]
time                    object
location                object
operator                object
flight_no               object
route                   object
ac_type                 object
registration            object
cn_ln                   object
aboard                   int64
fatalities               int64
ground                  object
summary                 object
dtype: object

## Seleccionando solo columnas que voy a tener en cuenta en estudio

In [450]:
new_crash_plane = crash_plane[['date','location', 'aboard', 'fatalities', 'summary']]

In [451]:
new_crash_plane.head(10)

,date,location,aboard,fatalities,summary
0,1908-09-17,"Fort Myer, Virginia",2,1,"During a demonstration flight, a U.S. Army fly..."
1,1909-09-07,"Juvisy-sur-Orge, France",1,1,Eugene Lefebvre was the first pilot to ever be...
2,1912-07-12,"Atlantic City, New Jersey",5,5,First U.S. dirigible Akron exploded just offsh...
3,1913-08-06,"Victoria, British Columbia, Canada",1,1,The first fatal airplane accident in Canada oc...
4,1913-09-09,Over the North Sea,20,14,The airship flew into a thunderstorm and encou...
5,1913-10-17,"Near Johannisthal, Germany",30,30,Hydrogen gas which was being vented was sucked...
6,1915-03-05,"Tienen, Belgium",41,21,Crashed into trees while attempting to land af...
7,1915-09-03,"Off Cuxhaven, Germany",19,19,"Exploded and burned near Neuwerk Island, when..."
8,1916-07-28,"Near Jambol, Bulgeria",20,20,"Crashed near the Black Sea, cause unknown."
9,1916-09-24,"Billericay, England",22,22,Shot down by British aircraft crashing in flames.

<font color=blue>Agregando una nueva columna llamada gravedad que va de mayor a menor segun la diferencia que hubo entre personas abordo del avion y personas fallecidas</font>

In [460]:
del new_crash_plane['gravedad']

new_crash_plane.head(10)

,date,location,aboard,fatalities,summary
0,1908-09-17,"Fort Myer, Virginia",2,1,"During a demonstration flight, a U.S. Army fly..."
1,1909-09-07,"Juvisy-sur-Orge, France",1,1,Eugene Lefebvre was the first pilot to ever be...
2,1912-07-12,"Atlantic City, New Jersey",5,5,First U.S. dirigible Akron exploded just offsh...
3,1913-08-06,"Victoria, British Columbia, Canada",1,1,The first fatal airplane accident in Canada oc...
4,1913-09-09,Over the North Sea,20,14,The airship flew into a thunderstorm and encou...
5,1913-10-17,"Near Johannisthal, Germany",30,30,Hydrogen gas which was being vented was sucked...
6,1915-03-05,"Tienen, Belgium",41,21,Crashed into trees while attempting to land af...
7,1915-09-03,"Off Cuxhaven, Germany",19,19,"Exploded and burned near Neuwerk Island, when..."
8,1916-07-28,"Near Jambol, Bulgeria",20,20,"Crashed near the Black Sea, cause unknown."
9,1916-09-24,"Billericay, England",22,22,Shot down by British aircraft crashing in flames.