In [5]:
import pandas as pd

In [6]:
import pymysql
from sqlalchemy import create_engine

In [7]:
import sqlite3

In [8]:
with sqlite3.connect("database.sqlite") as con:
    countries = pd.read_sql("SELECT * from Country", con)
    matches = pd.read_sql("SELECT * from Match", con)
    leagues = pd.read_sql("SELECT * from League", con)
    teams = pd.read_sql("SELECT * from Team", con)
    teams_stats = pd.read_sql("SELECT * from Team_Attributes", con)
    players = pd.read_sql("SELECT * from Player", con)

    player_stats = pd.read_sql("SELECT * from Player_Attributes", con)

In [20]:
matches.head()
#aqui vamos a usar el drop para quitar las columnas que no sean útiles para un posterior análisis. 
newMatchesTable = matches.drop(columns=['country_id','league_id', 'home_player_X1', 'home_player_X2', 'home_player_X3', 'home_player_X4', 'home_player_X5', 'home_player_X6', 'home_player_X7', 'home_player_X8', 'home_player_X9', 'home_player_X10', 'home_player_X11', 'away_player_X1', 'away_player_X2', 'away_player_X3', 'away_player_X4', 'away_player_X5', 'away_player_X6', 'away_player_X7', 'away_player_X8', 'away_player_X9', 'away_player_X10', 'away_player_X11','home_player_Y1','home_player_Y2','home_player_Y3','home_player_Y4','home_player_Y5','home_player_Y6','home_player_Y7','home_player_Y8','home_player_Y9','home_player_Y10','home_player_Y11','away_player_Y1','away_player_Y2','away_player_Y3','away_player_Y4','away_player_Y5','away_player_Y6','away_player_Y7','away_player_Y8','away_player_Y9','away_player_Y10','away_player_Y11', 'home_player_1', 'home_player_2', 'home_player_3', 'home_player_4', 'home_player_5', 'home_player_6', 'home_player_7', 'home_player_8', 'home_player_9', 'home_player_10', 'home_player_11', 'away_player_1', 'away_player_2', 'away_player_3', 'away_player_4', 'away_player_5', 'away_player_6', 'away_player_7', 'away_player_8', 'away_player_9', 'away_player_10', 'away_player_11'])
newMatchesTable

,id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,1,None,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,0,None,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,3,None,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,0,None,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,3,None,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
5,6,2008/2009,1,2008-09-24 00:00:00,492478,8203,8342,1,1,None,...,1.67,4.35,3.40,1.70,4.50,3.40,1.70,NaN,NaN,NaN
6,7,2008/2009,1,2008-08-16 00:00:00,492479,9999,8571,2,2,None,...,3.60,2.10,3.25,3.00,1.85,3.25,3.75,2.10,3.25,3.10
7,8,2008/2009,1,2008-08-16 00:00:00,492480,4049,9996,1,2,None,...,2.40,2.80,3.25,2.25,2.80,3.20,2.25,2.88,3.25,2.20
8,9,2008/2009,1,2008-08-16 00:00:00,492481,10001,9986,1,0,None,...,3.10,2.25,3.25,2.80,2.20,3.30,2.80,2.25,3.20,2.80
9,10,2008/2009,10,2008-11-01 00:00:00,492564,8342,8571,4,1,None,...,10.00,1.30,4.35,8.50,1.25,5.00,10.00,1.29,4.50,9.00
10,11,2008/2009,10,2008-10-31 00:00:00,492565,9985,9986,1,2,None,...,10.00,1.28,4.50,8.50,1.25,5.00,10.00,1.25,5.00,9.00
11,12,2008/2009,10,2008-11-02 00:00:00,492566,10000,9991,0,2,None,...,2.50,2.65,3.30,2.30,2.60,3.25,2.50,2.62,3.20,2.38
12,13,2008/2009,10,2008-11-01 00:00:00,492567,9994,9998,0,0,None,...,4.25,2.00,3.20,3.40,1.85,3.30,4.00,1.83,3.30,3.80
13,14,2008/2009,10,2008-11-01 00:00:00,492568,7947,10001,2,2,None,...,2.38,2.75,3.20,2.30,2.75,3.25,2.35,2.75,3.20,2.30
14,15,2008/2009,10,2008-11-01 00:00:00,492569,8203,9999,1,2,None,...,4.75,1.70,3.40,4.35,1.75,3.40,4.25,1.70,3.40,4.33
15,16,2008/2009,10,2008-11-01 00:00:00,492570,9996,9984,0,1,None,...,2.88,2.20,3.25,2.90,2.30,3.25,2.85,2.30,3.20,2.75
16,17,2008/2009,10,2008-11-01 00:00:00,492571,4049,9987,1,3,None,...,1.62,5.50,3.50,1.55,5.25,3.60,1.60,6.00,3.60,1.50
17,18,2008/2009,10,2008-11-02 00:00:00,492572,9993,8635,1,3,None,...,1.80,3.60,3.25,1.90,4.10,3.40,1.80,3.80,3.30,1.83
18,19,2008/2009,11,2008-11-08 00:00:00,492573,8635,9994,2,3,None,...,9.00,1.28,4.50,8.50,1.30,4.75,7.50,1.30,4.50,8.50
19,20,2008/2009,11,2008-11-08 00:00:00,492574,9998,9996,0,0,None,...,2.75,2.35,3.25,2.65,2.30,3.20,2.75,2.30,3.25,2.70
20,21,2008/2009,11,2008-11-09 00:00:00,492575,9986,8342,2,2,None,...,2.10,3.25,3.25,2.00,3.10,3.20,2.15,3.10,3.25,2.10
21,22,2008/2009,11,2008-11-07 00:00:00,492576,9984,10000,2,0,None,...,4.25,1.75,3.25,4.35,1.80,3.30,4.20,1.70,3.30,4.50
22,23,2008/2009,11,2008-11-08 00:00:00,492577,9991,7947,1,1,None,...,7.00,1.35,4.00,7.50,1.40,4.20,7.00,1.36,4.20,7.00
23,24,2008/2009,11,2008-11-08 00:00:00,492578,9999,4049,1,2,None,...,4.00,1.80,3.25,4.00,1.85,3.30,4.00,1.80,3.30,4.00
24,25,2008/2009,11,2008-11-08 00:00:00,492579,8571,8203,0,0,None,...,3.50,2.00,3.25,3.25,1.95,3.20,3.50,2.00,3.25,3.30
25,26,2008/2009,11,2008-11-08 00:00:00,492580,10001,9987,1,0,None,...,2.60,2.40,3.25,2.60,2.50,3.25,2.50,2.50,3.20,2.50
26,27,2008/2009,11,2008-11-09 00:00:00,492581,9993,9985,1,3,None,...,1.95,3.75,3.25,1.85,3.60,3.25,1.95,3.50,3.30,1.91
27,28,2008/2009,12,2008-11-16 00:00:00,492582,8342,8635,1,1,None,...,3.30,2.25,3.10,2.80,2.10,3.20,3.20,2.20,3.20,2.90
28,29,2008/2009,12,2008-11-15 00:00:00,492583,9987,9999,1,1,None,...,10.00,1.25,5.00,9.00,1.27,5.00,8.50,1.25,5.00,9.00
29,30,2008/2009,12,2008-11-15 00:00:00,492584,10000,9993,2,2,None,...,3.40,2.10,3.30,3.10,2.00,3.20,3.50,2.00,3.25,3.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25949,25950,2015/2016,4,2015-08-08 00:00:00,1992066,9956,7896,6,1,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25950,25951,2015/2016,4,2015-08-08 00:00:00,1992067,10199,9931,1,3,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25951,25952,2015/2016,4,2015-08-09 00:00:00,1992068,10190,10243,0,2,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25952,25953,2015/2016,4,2015-08-09 00:00:00,1992069,9824,10179,1,1,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25953,25954,2015/2016,4,2015-08-09 00:00:00,1992070,10192,10191,3,1,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25954,25955,2015/2016,5,2015-08-12 00:00:00,1992071,9931,10191,3,1,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25955,25956,2015/2016,5,2015-08-12 00:00:00,1992072,10192,7896,0,1,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25956,25957,2015/2016,5,2015-08-12 00:00:00,1992073,10199,10190,0,1,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25957,25958,2015/2016,5,2015-08-13 00:00:00,1992074,10179,10243,3,1,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25958,25959,2015/2016,5,2015-08-13 00:00:00,1992075,9824,9956,3,3,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25959,25960,2015/2016,6,2015-08-22 00:00:00,1992076,7896,9931,1,3,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25960,25961,2015/2016,6,2015-08-23 00:00:00,1992077,10179,10192,1,3,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25961,25962,2015/2016,6,2015-08-23 00:00:00,1992078,10190,9956,0,2,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25962,25963,2015/2016,6,2015-08-23 00:00:00,1992079,10191,9824,1,0,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25963,25964,2015/2016,6,2015-08-22 00:00:00,1992080,10243,10199,2,5,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25964,25965,2015/2016,7,2015-08-29 00:00:00,1992081,7896,10199,0,1,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25965,25966,2015/2016,7,2015-08-29 00:00:00,1992082,9824,10190,1,0,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25966,25967,2015/2016,7,2015-08-30 00:00:00,1992083,10191,10179,0,2,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25967,25968,2015/2016,7,2015-08-30 00:00:00,1992084,9931,10243,3,1,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25968,25969,2015/2016,7,2015-08-30 00:00:00,1992085,9956,10192,3,2,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25969,25970,2015/2016,8,2015-09-12 00:00:00,1992086,9931,10190,2,1,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25970,25971,2015/2016,8,2015-09-12 00:00:00,1992087,10192,9824,4,0,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25971,25972,2015/2016,8,2015-09-13 00:00:00,1992088,10199,9956,3,3,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25972,25973,2015/2016,8,2015-09-13 00:00:00,1992089,10243,10191,3,3,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25973,25974,2015/2016,8,2015-09-13 00:00:00,1992090,10179,7896,3,0,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25974,25975,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,0,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25975,25976,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,2,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25976,25977,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,0,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25977,25978,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,0,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25978,25979,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,3,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
leagues    #aqui cambiamos el orden de las columnas de la tabla 'leagues' 
leagues_new_order = ['name','id','country_id']

newDataSet = leagues[leagues_new_order]
newDataSet

                        name     id  country_id
0     Belgium Jupiler League      1           1
1     England Premier League   1729        1729
2             France Ligue 1   4769        4769
3      Germany 1. Bundesliga   7809        7809
4              Italy Serie A  10257       10257
5     Netherlands Eredivisie  13274       13274
6         Poland Ekstraklasa  15722       15722
7   Portugal Liga ZON Sagres  17642       17642
8    Scotland Premier League  19694       19694
9            Spain LIGA BBVA  21518       21518
10  Switzerland Super League  24558       24558

In [11]:
leagues   #aqui creé un nuevo data set para la tabla leagues en donde excluí la variable country_id, ya que daba la misma informacion que la columna id
leagues_1 = leagues[['id', 'name' ]]

leagues_1

leagues_1 = leagues_1.rename(columns = {'name': 'League Names'})   #aqui le cambiamos el nombre a 'names' y lo cambiamos a 'League Names' para que fuera más descriptivo el título. 
leagues_1

       id              League Names
0       1    Belgium Jupiler League
1    1729    England Premier League
2    4769            France Ligue 1
3    7809     Germany 1. Bundesliga
4   10257             Italy Serie A
5   13274    Netherlands Eredivisie
6   15722        Poland Ekstraklasa
7   17642  Portugal Liga ZON Sagres
8   19694   Scotland Premier League
9   21518           Spain LIGA BBVA
10  24558  Switzerland Super League

In [12]:
teams 

#aqui uniré las tablas "teams" y "matches" porque la tabla matches no tiene la columna "team_long_name" y la tabla team si la tiene. Por lo cual identificar a los equipos por su nomnbre va a ser mucho más fácil que por su id.  
pd.concat([teams,matches], axis=1)

,id,team_api_id,team_fifa_api_id,team_long_name,team_short_name,id,country_id,league_id,season,stage,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1.0,9987.0,673.0,KRC Genk,GEN,1,1,1,2008/2009,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2.0,9993.0,675.0,Beerschot AC,BAC,2,1,1,2008/2009,1,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3.0,10000.0,15005.0,SV Zulte-Waregem,ZUL,3,1,1,2008/2009,1,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4.0,9994.0,2007.0,Sporting Lokeren,LOK,4,1,1,2008/2009,1,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5.0,9984.0,1750.0,KSV Cercle Brugge,CEB,5,1,1,2008/2009,1,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
5,6.0,8635.0,229.0,RSC Anderlecht,AND,6,1,1,2008/2009,1,...,1.67,4.35,3.40,1.70,4.50,3.40,1.70,NaN,NaN,NaN
6,7.0,9991.0,674.0,KAA Gent,GEN,7,1,1,2008/2009,1,...,3.60,2.10,3.25,3.00,1.85,3.25,3.75,2.10,3.25,3.10
7,8.0,9998.0,1747.0,RAEC Mons,MON,8,1,1,2008/2009,1,...,2.40,2.80,3.25,2.25,2.80,3.20,2.25,2.88,3.25,2.20
8,9.0,7947.0,NaN,FCV Dender EH,DEN,9,1,1,2008/2009,1,...,3.10,2.25,3.25,2.80,2.20,3.30,2.80,2.25,3.20,2.80
9,10.0,9985.0,232.0,Standard de Liège,STL,10,1,1,2008/2009,10,...,10.00,1.30,4.35,8.50,1.25,5.00,10.00,1.29,4.50,9.00
10,11.0,8203.0,110724.0,KV Mechelen,MEC,11,1,1,2008/2009,10,...,10.00,1.28,4.50,8.50,1.25,5.00,10.00,1.25,5.00,9.00
11,12.0,8342.0,231.0,Club Brugge KV,CLB,12,1,1,2008/2009,10,...,2.50,2.65,3.30,2.30,2.60,3.25,2.50,2.62,3.20,2.38
12,13.0,9999.0,546.0,KSV Roeselare,ROS,13,1,1,2008/2009,10,...,4.25,2.00,3.20,3.40,1.85,3.30,4.00,1.83,3.30,3.80
13,14.0,8571.0,100081.0,KV Kortrijk,KOR,14,1,1,2008/2009,10,...,2.38,2.75,3.20,2.30,2.75,3.25,2.35,2.75,3.20,2.30
14,15.0,4049.0,NaN,Tubize,TUB,15,1,1,2008/2009,10,...,4.75,1.70,3.40,4.35,1.75,3.40,4.25,1.70,3.40,4.33
15,16.0,9996.0,111560.0,Royal Excel Mouscron,MOU,16,1,1,2008/2009,10,...,2.88,2.20,3.25,2.90,2.30,3.25,2.85,2.30,3.20,2.75
16,17.0,10001.0,681.0,KVC Westerlo,WES,17,1,1,2008/2009,10,...,1.62,5.50,3.50,1.55,5.25,3.60,1.60,6.00,3.60,1.50
17,18.0,9986.0,670.0,Sporting Charleroi,CHA,18,1,1,2008/2009,10,...,1.80,3.60,3.25,1.90,4.10,3.40,1.80,3.80,3.30,1.83
18,614.0,9997.0,680.0,Sint-Truidense VV,STT,19,1,1,2008/2009,11,...,9.00,1.28,4.50,8.50,1.30,4.75,7.50,1.30,4.50,8.50
19,1034.0,9989.0,239.0,Lierse SK,LIE,20,1,1,2008/2009,11,...,2.75,2.35,3.25,2.65,2.30,3.20,2.75,2.30,3.25,2.70
20,1042.0,6351.0,2013.0,KAS Eupen,EUP,21,1,1,2008/2009,11,...,2.10,3.25,3.25,2.00,3.10,3.20,2.15,3.10,3.25,2.10
21,1513.0,1773.0,100087.0,Oud-Heverlee Leuven,O-H,22,1,1,2008/2009,11,...,4.25,1.75,3.25,4.35,1.80,3.30,4.20,1.70,3.30,4.50
22,2004.0,8475.0,110913.0,Waasland-Beveren,WAA,23,1,1,2008/2009,11,...,7.00,1.35,4.00,7.50,1.40,4.20,7.00,1.36,4.20,7.00
23,2476.0,8573.0,682.0,KV Oostende,OOS,24,1,1,2008/2009,11,...,4.00,1.80,3.25,4.00,1.85,3.30,4.00,1.80,3.30,4.00
24,2510.0,274581.0,111560.0,Royal Excel Mouscron,MOP,25,1,1,2008/2009,11,...,3.50,2.00,3.25,3.25,1.95,3.20,3.50,2.00,3.25,3.30
25,3457.0,10260.0,11.0,Manchester United,MUN,26,1,1,2008/2009,11,...,2.60,2.40,3.25,2.60,2.50,3.25,2.50,2.50,3.20,2.50
26,3458.0,10261.0,13.0,Newcastle United,NEW,27,1,1,2008/2009,11,...,1.95,3.75,3.25,1.85,3.60,3.25,1.95,3.50,3.30,1.91
27,3459.0,9825.0,1.0,Arsenal,ARS,28,1,1,2008/2009,12,...,3.30,2.25,3.10,2.80,2.10,3.20,3.20,2.20,3.20,2.90
28,3460.0,8659.0,109.0,West Bromwich Albion,WBA,29,1,1,2008/2009,12,...,10.00,1.25,5.00,9.00,1.27,5.00,8.50,1.25,5.00,9.00
29,3461.0,8472.0,106.0,Sunderland,SUN,30,1,1,2008/2009,12,...,3.40,2.10,3.30,3.10,2.00,3.20,3.50,2.00,3.25,3.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25949,NaN,NaN,NaN,NaN,NaN,25950,24558,24558,2015/2016,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25950,NaN,NaN,NaN,NaN,NaN,25951,24558,24558,2015/2016,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25951,NaN,NaN,NaN,NaN,NaN,25952,24558,24558,2015/2016,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25952,NaN,NaN,NaN,NaN,NaN,25953,24558,24558,2015/2016,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25953,NaN,NaN,NaN,NaN,NaN,25954,24558,24558,2015/2016,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25954,NaN,NaN,NaN,NaN,NaN,25955,24558,24558,2015/2016,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25955,NaN,NaN,NaN,NaN,NaN,25956,24558,24558,2015/2016,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25956,NaN,NaN,NaN,NaN,NaN,25957,24558,24558,2015/2016,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25957,NaN,NaN,NaN,NaN,NaN,25958,24558,24558,2015/2016,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25958,NaN,NaN,NaN,NaN,NaN,25959,24558,24558,2015/2016,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25959,NaN,NaN,NaN,NaN,NaN,25960,24558,24558,2015/2016,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25960,NaN,NaN,NaN,NaN,NaN,25961,24558,24558,2015/2016,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25961,NaN,NaN,NaN,NaN,NaN,25962,24558,24558,2015/2016,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25962,NaN,NaN,NaN,NaN,NaN,25963,24558,24558,2015/2016,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25963,NaN,NaN,NaN,NaN,NaN,25964,24558,24558,2015/2016,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25964,NaN,NaN,NaN,NaN,NaN,25965,24558,24558,2015/2016,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25965,NaN,NaN,NaN,NaN,NaN,25966,24558,24558,2015/2016,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25966,NaN,NaN,NaN,NaN,NaN,25967,24558,24558,2015/2016,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25967,NaN,NaN,NaN,NaN,NaN,25968,24558,24558,2015/2016,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25968,NaN,NaN,NaN,NaN,NaN,25969,24558,24558,2015/2016,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25969,NaN,NaN,NaN,NaN,NaN,25970,24558,24558,2015/2016,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25970,NaN,NaN,NaN,NaN,NaN,25971,24558,24558,2015/2016,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25971,NaN,NaN,NaN,NaN,NaN,25972,24558,24558,2015/2016,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25972,NaN,NaN,NaN,NaN,NaN,25973,24558,24558,2015/2016,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25973,NaN,NaN,NaN,NaN,NaN,25974,24558,24558,2015/2016,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25974,NaN,NaN,NaN,NaN,NaN,25975,24558,24558,2015/2016,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25975,NaN,NaN,NaN,NaN,NaN,25976,24558,24558,2015/2016,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25976,NaN,NaN,NaN,NaN,NaN,25977,24558,24558,2015/2016,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25977,NaN,NaN,NaN,NaN,NaN,25978,24558,24558,2015/2016,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25978,NaN,NaN,NaN,NaN,NaN,25979,24558,24558,2015/2016,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
teams_stats   #aqui filtré la tabla con los equipos que tuviesen una presión en la defensa {defencePressure} mayor a 50
newTeamsStats = teams_stats.rename(columns = {'defencePressure': 'Defense Pressure'})   #aqui le cambiamos el nombre a 'names' y lo cambiamos a 'League Names' para que fuera más descriptivo el título. 

defensePressurefilter = newTeamsStats[teams_stats['defencePressure']>50]

defensePressurefilter

newTeamsStats.loc[newTeamsStats['Defense Pressure'] > 50, 'New '] = 'High Pressure at defense!!'
newTeamsStats

,id,team_fifa_api_id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,...,chanceCreationShootingClass,chanceCreationPositioningClass,Defense Pressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass,New
0,1,434,9930,2010-02-22 00:00:00,60,Balanced,NaN,Little,50,Mixed,...,Normal,Organised,50,Medium,55,Press,45,Normal,Cover,NaN
1,2,434,9930,2014-09-19 00:00:00,52,Balanced,48.0,Normal,56,Mixed,...,Normal,Organised,47,Medium,44,Press,54,Normal,Cover,NaN
2,3,434,9930,2015-09-10 00:00:00,47,Balanced,41.0,Normal,54,Mixed,...,Normal,Organised,47,Medium,44,Press,54,Normal,Cover,NaN
3,4,77,8485,2010-02-22 00:00:00,70,Fast,NaN,Little,70,Long,...,Lots,Organised,60,Medium,70,Double,70,Wide,Cover,High Pressure at defense!!
4,5,77,8485,2011-02-22 00:00:00,47,Balanced,NaN,Little,52,Mixed,...,Normal,Organised,47,Medium,47,Press,52,Normal,Cover,NaN
5,6,77,8485,2012-02-22 00:00:00,58,Balanced,NaN,Little,62,Mixed,...,Normal,Organised,40,Medium,40,Press,60,Normal,Cover,NaN
6,7,77,8485,2013-09-20 00:00:00,62,Balanced,NaN,Little,45,Mixed,...,Normal,Organised,42,Medium,42,Press,60,Normal,Cover,NaN
7,8,77,8485,2014-09-19 00:00:00,58,Balanced,64.0,Normal,62,Mixed,...,Normal,Organised,41,Medium,42,Press,60,Normal,Cover,NaN
8,9,77,8485,2015-09-10 00:00:00,59,Balanced,64.0,Normal,53,Mixed,...,Normal,Free Form,49,Medium,45,Press,63,Normal,Cover,NaN
9,10,614,8576,2010-02-22 00:00:00,60,Balanced,NaN,Little,40,Mixed,...,Normal,Organised,30,Deep,70,Double,30,Narrow,Offside Trap,NaN
10,11,614,8576,2011-02-22 00:00:00,65,Balanced,NaN,Little,45,Mixed,...,Normal,Organised,45,Medium,45,Press,50,Normal,Cover,NaN
11,12,614,8576,2012-02-22 00:00:00,59,Balanced,NaN,Little,52,Mixed,...,Normal,Organised,38,Medium,47,Press,53,Normal,Cover,NaN
12,13,614,8576,2013-09-20 00:00:00,59,Balanced,NaN,Little,52,Mixed,...,Normal,Organised,38,Medium,47,Press,53,Normal,Cover,NaN
13,14,614,8576,2014-09-19 00:00:00,59,Balanced,57.0,Normal,52,Mixed,...,Normal,Organised,38,Medium,47,Press,53,Normal,Cover,NaN
14,15,614,8576,2015-09-10 00:00:00,59,Balanced,57.0,Normal,52,Mixed,...,Normal,Organised,38,Medium,47,Press,53,Normal,Cover,NaN
15,16,47,8564,2010-02-22 00:00:00,45,Balanced,NaN,Little,30,Short,...,Lots,Free Form,30,Deep,35,Press,60,Normal,Offside Trap,NaN
16,17,47,8564,2011-02-22 00:00:00,65,Balanced,NaN,Little,50,Mixed,...,Normal,Free Form,50,Medium,50,Press,50,Normal,Offside Trap,NaN
17,18,47,8564,2012-02-22 00:00:00,45,Balanced,NaN,Little,50,Mixed,...,Normal,Free Form,45,Medium,45,Press,50,Normal,Cover,NaN
18,19,47,8564,2013-09-20 00:00:00,48,Balanced,NaN,Little,54,Mixed,...,Normal,Free Form,48,Medium,49,Press,53,Normal,Cover,NaN
19,20,47,8564,2014-09-19 00:00:00,48,Balanced,70.0,Lots,52,Mixed,...,Lots,Organised,58,Medium,57,Press,49,Normal,Cover,High Pressure at defense!!
20,21,47,8564,2015-09-10 00:00:00,48,Balanced,70.0,Lots,52,Mixed,...,Lots,Organised,58,Medium,57,Press,49,Normal,Cover,High Pressure at defense!!
21,22,1901,10215,2010-02-22 00:00:00,30,Slow,NaN,Little,30,Short,...,Normal,Organised,30,Deep,30,Contain,30,Narrow,Offside Trap,NaN
22,23,1901,10215,2011-02-22 00:00:00,30,Slow,NaN,Little,50,Mixed,...,Normal,Organised,30,Deep,45,Press,65,Normal,Cover,NaN
23,24,1901,10215,2012-02-22 00:00:00,45,Balanced,NaN,Little,44,Mixed,...,Normal,Organised,52,Medium,38,Press,61,Normal,Cover,High Pressure at defense!!
24,25,1901,10215,2013-09-20 00:00:00,45,Balanced,NaN,Little,44,Mixed,...,Normal,Organised,52,Medium,38,Press,61,Normal,Cover,High Pressure at defense!!
25,26,1901,10215,2014-09-19 00:00:00,52,Balanced,53.0,Normal,44,Mixed,...,Normal,Organised,39,Medium,38,Press,61,Normal,Cover,NaN
26,27,1901,10215,2015-09-10 00:00:00,53,Balanced,53.0,Normal,44,Mixed,...,Normal,Organised,39,Medium,38,Press,61,Normal,Cover,NaN
27,28,650,10217,2010-02-22 00:00:00,30,Slow,NaN,Little,35,Mixed,...,Normal,Organised,30,Deep,30,Contain,30,Narrow,Cover,NaN
28,29,650,10217,2011-02-22 00:00:00,53,Balanced,NaN,Little,53,Mixed,...,Normal,Organised,46,Medium,62,Press,65,Normal,Cover,NaN
29,30,650,10217,2012-02-22 00:00:00,38,Balanced,NaN,Little,44,Mixed,...,Normal,Organised,50,Medium,58,Press,62,Normal,Cover,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1428,1429,435,7955,2012-02-22 00:00:00,49,Balanced,NaN,Little,50,Mixed,...,Normal,Organised,34,Medium,31,Contain,51,Normal,Cover,NaN
1429,1430,1742,9868,2010-02-22 00:00:00,30,Slow,NaN,Little,30,Short,...,Lots,Organised,45,Medium,50,Press,45,Normal,Cover,NaN
1430,1431,1742,9868,2011-02-22 00:00:00,40,Balanced,NaN,Little,58,Mixed,...,Normal,Organised,46,Medium,52,Press,67,Wide,Cover,NaN
1431,1432,1742,9868,2012-02-22 00:00:00,60,Balanced,NaN,Little,44,Mixed,...,Normal,Organised,49,Medium,54,Press,50,Normal,Cover,NaN
1432,1433,1742,9868,2013-09-20 00:00:00,60,Balanced,NaN,Little,44,Mixed,...,Normal,Organised,49,Medium,54,Press,50,Normal,Cover,NaN
1433,1434,900,10192,2010-02-22 00:00:00,55,Balanced,NaN,Little,55,Mixed,...,Normal,Organised,55,Medium,55,Press,60,Normal,Offside Trap,High Pressure at defense!!
1434,1435,900,10192,2011-02-22 00:00:00,60,Balanced,NaN,Little,57,Mixed,...,Lots,Organised,48,Medium,49,Press,61,Normal,Cover,NaN
1435,1436,900,10192,2012-02-22 00:00:00,52,Balanced,NaN,Little,69,Long,...,Normal,Organised,44,Medium,34,Press,50,Normal,Cover,NaN
1436,1437,900,10192,2013-09-20 00:00:00,52,Balanced,NaN,Little,69,Long,...,Normal,Organised,44,Medium,34,Press,50,Normal,Cover,NaN
1437,1438,900,10192,2014-09-19 00:00:00,52,Balanced,56.0,Normal,64,Mixed,...,Normal,Organised,44,Medium,34,Press,50,Normal,Cover,NaN
1438,1439,900,10192,2015-09-10 00:00:00,52,Balanced,56.0,Normal,64,Mixed,...,Normal,Organised,44,Medium,34,Press,50,Normal,Cover,NaN
1439,1440,110749,8021,2010-02-22 00:00:00,55,Balanced,NaN,Little,60,Mixed,...,Lots,Organised,70,High,70,Double,70,Wide,Cover,High Pressure at defense!!
1440,1441,110749,8021,2011-02-22 00:00:00,54,Balanced,NaN,Little,37,Mixed,...,Normal,Organised,47,Medium,58,Press,52,Normal,Cover,NaN
1441,1442,110749,8021,2012-02-22 00:00:00,33,Slow,NaN,Little,38,Mixed,...,Lots,Organised,58,Medium,47,Press,52,Normal,Cover,High Pressure at defense!!
1442,1443,110749,8021,2013-09-20 00:00:00,33,Slow,NaN,Little,38,Mixed,...,Normal,Organised,58,Medium,47,Press,52,Normal,Cover,High Pressure at defense!!
1443,1444,110749,8021,2014-09-19 00:00:00,33,Slow,49.0,Normal,51,Mixed,...,Normal,Organised,58,Medium,38,Press,52,Normal,Cover,High Pressure at defense!!
1444,1445,244,8394,2010-02-22 00:00:00,30,Slow,NaN,Little,30,Short,...,Lots,Organised,40,Medium,30,Contain,45,Normal,Offside Trap,NaN
1445,1446,244,8394,2011-02-22 00:00:00,43,Balanced,NaN,Little,40,Mixed,...,Normal,Organised,38,Medium,40,Press,53,Normal,Cover,NaN
1446,1447,244,8394,2012-02-22 00:00:00,34,Balanced,NaN,Little,23,Short,...,Normal,Organised,51,Medium,46,Press,61,Normal,Cover,High Pressure at defense!!
1447,1448,244,8394,2013-09-20 00:00:00,38,Balanced,NaN,Little,23,Short,...,Normal,Organised,51,Medium,46,Press,61,Normal,Cover,High Pressure at defense!!
1448,1449,244,8394,2014-09-19 00:00:00,38,Balanced,48.0,Normal,35,Mixed,...,Normal,Organised,51,Medium,46,Press,61,Normal,Cover,High Pressure at defense!!
1449,1450,244,8394,2015-09-10 00:00:00,52,Balanced,52.0,Normal,50,Mixed,...,Normal,Organised,48,Medium,43,Press,49,Normal,Cover,NaN
1450,1451,112512,8027,2014-09-19 00:00:00,54,Balanced,51.0,Normal,40,Mixed,...,Normal,Organised,44,Medium,47,Press,52,Normal,Cover,NaN
1451,1452,112512,8027,2015-09-10 00:00:00,54,Balanced,51.0,Normal,40,Mixed,...,Normal,Organised,44,Medium,47,Press,52,Normal,Cover,NaN
1452,1453,15005,10000,2010-02-22 00:00:00,65,Balanced,NaN,Little,60,Mixed,...,Normal,Organised,70,High,60,Press,70,Wide,Cover,High Pressure at defense!!
1453,1454,15005,10000,2011-02-22 00:00:00,52,Balanced,NaN,Little,52,Mixed,...,Normal,Organised,46,Medium,48,Press,53,Normal,Cover,NaN
1454,1455,15005,10000,2012-02-22 00:00:00,54,Balanced,NaN,Little,51,Mixed,...,Normal,Organised,44,Medium,55,Press,53,Normal,Cover,NaN
1455,1456,15005,10000,2013-09-20 00:00:00,54,Balanced,NaN,Little,51,Mixed,...,Little,Organised,44,Medium,58,Press,37,Normal,Cover,NaN
1456,1457,15005,10000,2014-09-19 00:00:00,54,Balanced,42.0,Normal,51,Mixed,...,Little,Organised,44,Medium,58,Press,37,Normal,Cover,NaN
1457,1458,15005,10000,2015-09-10 00:00:00,54,Balanced,42.0,Normal,51,Mixed,...,Little,Organised,44,Medium,58,Press,37,Normal,Cover,NaN

In [22]:
newMatchesTable.to_csv('database.sqlite', sep='|', index=False)
newMatchesTable

,id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,1,None,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,0,None,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,3,None,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,0,None,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,3,None,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
5,6,2008/2009,1,2008-09-24 00:00:00,492478,8203,8342,1,1,None,...,1.67,4.35,3.40,1.70,4.50,3.40,1.70,NaN,NaN,NaN
6,7,2008/2009,1,2008-08-16 00:00:00,492479,9999,8571,2,2,None,...,3.60,2.10,3.25,3.00,1.85,3.25,3.75,2.10,3.25,3.10
7,8,2008/2009,1,2008-08-16 00:00:00,492480,4049,9996,1,2,None,...,2.40,2.80,3.25,2.25,2.80,3.20,2.25,2.88,3.25,2.20
8,9,2008/2009,1,2008-08-16 00:00:00,492481,10001,9986,1,0,None,...,3.10,2.25,3.25,2.80,2.20,3.30,2.80,2.25,3.20,2.80
9,10,2008/2009,10,2008-11-01 00:00:00,492564,8342,8571,4,1,None,...,10.00,1.30,4.35,8.50,1.25,5.00,10.00,1.29,4.50,9.00
10,11,2008/2009,10,2008-10-31 00:00:00,492565,9985,9986,1,2,None,...,10.00,1.28,4.50,8.50,1.25,5.00,10.00,1.25,5.00,9.00
11,12,2008/2009,10,2008-11-02 00:00:00,492566,10000,9991,0,2,None,...,2.50,2.65,3.30,2.30,2.60,3.25,2.50,2.62,3.20,2.38
12,13,2008/2009,10,2008-11-01 00:00:00,492567,9994,9998,0,0,None,...,4.25,2.00,3.20,3.40,1.85,3.30,4.00,1.83,3.30,3.80
13,14,2008/2009,10,2008-11-01 00:00:00,492568,7947,10001,2,2,None,...,2.38,2.75,3.20,2.30,2.75,3.25,2.35,2.75,3.20,2.30
14,15,2008/2009,10,2008-11-01 00:00:00,492569,8203,9999,1,2,None,...,4.75,1.70,3.40,4.35,1.75,3.40,4.25,1.70,3.40,4.33
15,16,2008/2009,10,2008-11-01 00:00:00,492570,9996,9984,0,1,None,...,2.88,2.20,3.25,2.90,2.30,3.25,2.85,2.30,3.20,2.75
16,17,2008/2009,10,2008-11-01 00:00:00,492571,4049,9987,1,3,None,...,1.62,5.50,3.50,1.55,5.25,3.60,1.60,6.00,3.60,1.50
17,18,2008/2009,10,2008-11-02 00:00:00,492572,9993,8635,1,3,None,...,1.80,3.60,3.25,1.90,4.10,3.40,1.80,3.80,3.30,1.83
18,19,2008/2009,11,2008-11-08 00:00:00,492573,8635,9994,2,3,None,...,9.00,1.28,4.50,8.50,1.30,4.75,7.50,1.30,4.50,8.50
19,20,2008/2009,11,2008-11-08 00:00:00,492574,9998,9996,0,0,None,...,2.75,2.35,3.25,2.65,2.30,3.20,2.75,2.30,3.25,2.70
20,21,2008/2009,11,2008-11-09 00:00:00,492575,9986,8342,2,2,None,...,2.10,3.25,3.25,2.00,3.10,3.20,2.15,3.10,3.25,2.10
21,22,2008/2009,11,2008-11-07 00:00:00,492576,9984,10000,2,0,None,...,4.25,1.75,3.25,4.35,1.80,3.30,4.20,1.70,3.30,4.50
22,23,2008/2009,11,2008-11-08 00:00:00,492577,9991,7947,1,1,None,...,7.00,1.35,4.00,7.50,1.40,4.20,7.00,1.36,4.20,7.00
23,24,2008/2009,11,2008-11-08 00:00:00,492578,9999,4049,1,2,None,...,4.00,1.80,3.25,4.00,1.85,3.30,4.00,1.80,3.30,4.00
24,25,2008/2009,11,2008-11-08 00:00:00,492579,8571,8203,0,0,None,...,3.50,2.00,3.25,3.25,1.95,3.20,3.50,2.00,3.25,3.30
25,26,2008/2009,11,2008-11-08 00:00:00,492580,10001,9987,1,0,None,...,2.60,2.40,3.25,2.60,2.50,3.25,2.50,2.50,3.20,2.50
26,27,2008/2009,11,2008-11-09 00:00:00,492581,9993,9985,1,3,None,...,1.95,3.75,3.25,1.85,3.60,3.25,1.95,3.50,3.30,1.91
27,28,2008/2009,12,2008-11-16 00:00:00,492582,8342,8635,1,1,None,...,3.30,2.25,3.10,2.80,2.10,3.20,3.20,2.20,3.20,2.90
28,29,2008/2009,12,2008-11-15 00:00:00,492583,9987,9999,1,1,None,...,10.00,1.25,5.00,9.00,1.27,5.00,8.50,1.25,5.00,9.00
29,30,2008/2009,12,2008-11-15 00:00:00,492584,10000,9993,2,2,None,...,3.40,2.10,3.30,3.10,2.00,3.20,3.50,2.00,3.25,3.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25949,25950,2015/2016,4,2015-08-08 00:00:00,1992066,9956,7896,6,1,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25950,25951,2015/2016,4,2015-08-08 00:00:00,1992067,10199,9931,1,3,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25951,25952,2015/2016,4,2015-08-09 00:00:00,1992068,10190,10243,0,2,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25952,25953,2015/2016,4,2015-08-09 00:00:00,1992069,9824,10179,1,1,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25953,25954,2015/2016,4,2015-08-09 00:00:00,1992070,10192,10191,3,1,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25954,25955,2015/2016,5,2015-08-12 00:00:00,1992071,9931,10191,3,1,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25955,25956,2015/2016,5,2015-08-12 00:00:00,1992072,10192,7896,0,1,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25956,25957,2015/2016,5,2015-08-12 00:00:00,1992073,10199,10190,0,1,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25957,25958,2015/2016,5,2015-08-13 00:00:00,1992074,10179,10243,3,1,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25958,25959,2015/2016,5,2015-08-13 00:00:00,1992075,9824,9956,3,3,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25959,25960,2015/2016,6,2015-08-22 00:00:00,1992076,7896,9931,1,3,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25960,25961,2015/2016,6,2015-08-23 00:00:00,1992077,10179,10192,1,3,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25961,25962,2015/2016,6,2015-08-23 00:00:00,1992078,10190,9956,0,2,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25962,25963,2015/2016,6,2015-08-23 00:00:00,1992079,10191,9824,1,0,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25963,25964,2015/2016,6,2015-08-22 00:00:00,1992080,10243,10199,2,5,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25964,25965,2015/2016,7,2015-08-29 00:00:00,1992081,7896,10199,0,1,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25965,25966,2015/2016,7,2015-08-29 00:00:00,1992082,9824,10190,1,0,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25966,25967,2015/2016,7,2015-08-30 00:00:00,1992083,10191,10179,0,2,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25967,25968,2015/2016,7,2015-08-30 00:00:00,1992084,9931,10243,3,1,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25968,25969,2015/2016,7,2015-08-30 00:00:00,1992085,9956,10192,3,2,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25969,25970,2015/2016,8,2015-09-12 00:00:00,1992086,9931,10190,2,1,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25970,25971,2015/2016,8,2015-09-12 00:00:00,1992087,10192,9824,4,0,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25971,25972,2015/2016,8,2015-09-13 00:00:00,1992088,10199,9956,3,3,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25972,25973,2015/2016,8,2015-09-13 00:00:00,1992089,10243,10191,3,3,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25973,25974,2015/2016,8,2015-09-13 00:00:00,1992090,10179,7896,3,0,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25974,25975,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,0,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25975,25976,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,2,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25976,25977,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,0,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25977,25978,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,0,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25978,25979,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,3,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
leagues.to_csv('database.sqlite', sep='|', index=False)
leagues_1

       id              League Names
0       1    Belgium Jupiler League
1    1729    England Premier League
2    4769            France Ligue 1
3    7809     Germany 1. Bundesliga
4   10257             Italy Serie A
5   13274    Netherlands Eredivisie
6   15722        Poland Ekstraklasa
7   17642  Portugal Liga ZON Sagres
8   19694   Scotland Premier League
9   21518           Spain LIGA BBVA
10  24558  Switzerland Super League

In [26]:
newDataSet.to_csv('database.sqlite', sep='|', index=False)
newDataSet

                        name     id  country_id
0     Belgium Jupiler League      1           1
1     England Premier League   1729        1729
2             France Ligue 1   4769        4769
3      Germany 1. Bundesliga   7809        7809
4              Italy Serie A  10257       10257
5     Netherlands Eredivisie  13274       13274
6         Poland Ekstraklasa  15722       15722
7   Portugal Liga ZON Sagres  17642       17642
8    Scotland Premier League  19694       19694
9            Spain LIGA BBVA  21518       21518
10  Switzerland Super League  24558       24558

In [27]:
newDataSet.to_csv('database.sqlite', sep='|', index=False)
newTeamsStats

,id,team_fifa_api_id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,...,chanceCreationShootingClass,chanceCreationPositioningClass,Defense Pressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass,New
0,1,434,9930,2010-02-22 00:00:00,60,Balanced,NaN,Little,50,Mixed,...,Normal,Organised,50,Medium,55,Press,45,Normal,Cover,NaN
1,2,434,9930,2014-09-19 00:00:00,52,Balanced,48.0,Normal,56,Mixed,...,Normal,Organised,47,Medium,44,Press,54,Normal,Cover,NaN
2,3,434,9930,2015-09-10 00:00:00,47,Balanced,41.0,Normal,54,Mixed,...,Normal,Organised,47,Medium,44,Press,54,Normal,Cover,NaN
3,4,77,8485,2010-02-22 00:00:00,70,Fast,NaN,Little,70,Long,...,Lots,Organised,60,Medium,70,Double,70,Wide,Cover,High Pressure at defense!!
4,5,77,8485,2011-02-22 00:00:00,47,Balanced,NaN,Little,52,Mixed,...,Normal,Organised,47,Medium,47,Press,52,Normal,Cover,NaN
5,6,77,8485,2012-02-22 00:00:00,58,Balanced,NaN,Little,62,Mixed,...,Normal,Organised,40,Medium,40,Press,60,Normal,Cover,NaN
6,7,77,8485,2013-09-20 00:00:00,62,Balanced,NaN,Little,45,Mixed,...,Normal,Organised,42,Medium,42,Press,60,Normal,Cover,NaN
7,8,77,8485,2014-09-19 00:00:00,58,Balanced,64.0,Normal,62,Mixed,...,Normal,Organised,41,Medium,42,Press,60,Normal,Cover,NaN
8,9,77,8485,2015-09-10 00:00:00,59,Balanced,64.0,Normal,53,Mixed,...,Normal,Free Form,49,Medium,45,Press,63,Normal,Cover,NaN
9,10,614,8576,2010-02-22 00:00:00,60,Balanced,NaN,Little,40,Mixed,...,Normal,Organised,30,Deep,70,Double,30,Narrow,Offside Trap,NaN
10,11,614,8576,2011-02-22 00:00:00,65,Balanced,NaN,Little,45,Mixed,...,Normal,Organised,45,Medium,45,Press,50,Normal,Cover,NaN
11,12,614,8576,2012-02-22 00:00:00,59,Balanced,NaN,Little,52,Mixed,...,Normal,Organised,38,Medium,47,Press,53,Normal,Cover,NaN
12,13,614,8576,2013-09-20 00:00:00,59,Balanced,NaN,Little,52,Mixed,...,Normal,Organised,38,Medium,47,Press,53,Normal,Cover,NaN
13,14,614,8576,2014-09-19 00:00:00,59,Balanced,57.0,Normal,52,Mixed,...,Normal,Organised,38,Medium,47,Press,53,Normal,Cover,NaN
14,15,614,8576,2015-09-10 00:00:00,59,Balanced,57.0,Normal,52,Mixed,...,Normal,Organised,38,Medium,47,Press,53,Normal,Cover,NaN
15,16,47,8564,2010-02-22 00:00:00,45,Balanced,NaN,Little,30,Short,...,Lots,Free Form,30,Deep,35,Press,60,Normal,Offside Trap,NaN
16,17,47,8564,2011-02-22 00:00:00,65,Balanced,NaN,Little,50,Mixed,...,Normal,Free Form,50,Medium,50,Press,50,Normal,Offside Trap,NaN
17,18,47,8564,2012-02-22 00:00:00,45,Balanced,NaN,Little,50,Mixed,...,Normal,Free Form,45,Medium,45,Press,50,Normal,Cover,NaN
18,19,47,8564,2013-09-20 00:00:00,48,Balanced,NaN,Little,54,Mixed,...,Normal,Free Form,48,Medium,49,Press,53,Normal,Cover,NaN
19,20,47,8564,2014-09-19 00:00:00,48,Balanced,70.0,Lots,52,Mixed,...,Lots,Organised,58,Medium,57,Press,49,Normal,Cover,High Pressure at defense!!
20,21,47,8564,2015-09-10 00:00:00,48,Balanced,70.0,Lots,52,Mixed,...,Lots,Organised,58,Medium,57,Press,49,Normal,Cover,High Pressure at defense!!
21,22,1901,10215,2010-02-22 00:00:00,30,Slow,NaN,Little,30,Short,...,Normal,Organised,30,Deep,30,Contain,30,Narrow,Offside Trap,NaN
22,23,1901,10215,2011-02-22 00:00:00,30,Slow,NaN,Little,50,Mixed,...,Normal,Organised,30,Deep,45,Press,65,Normal,Cover,NaN
23,24,1901,10215,2012-02-22 00:00:00,45,Balanced,NaN,Little,44,Mixed,...,Normal,Organised,52,Medium,38,Press,61,Normal,Cover,High Pressure at defense!!
24,25,1901,10215,2013-09-20 00:00:00,45,Balanced,NaN,Little,44,Mixed,...,Normal,Organised,52,Medium,38,Press,61,Normal,Cover,High Pressure at defense!!
25,26,1901,10215,2014-09-19 00:00:00,52,Balanced,53.0,Normal,44,Mixed,...,Normal,Organised,39,Medium,38,Press,61,Normal,Cover,NaN
26,27,1901,10215,2015-09-10 00:00:00,53,Balanced,53.0,Normal,44,Mixed,...,Normal,Organised,39,Medium,38,Press,61,Normal,Cover,NaN
27,28,650,10217,2010-02-22 00:00:00,30,Slow,NaN,Little,35,Mixed,...,Normal,Organised,30,Deep,30,Contain,30,Narrow,Cover,NaN
28,29,650,10217,2011-02-22 00:00:00,53,Balanced,NaN,Little,53,Mixed,...,Normal,Organised,46,Medium,62,Press,65,Normal,Cover,NaN
29,30,650,10217,2012-02-22 00:00:00,38,Balanced,NaN,Little,44,Mixed,...,Normal,Organised,50,Medium,58,Press,62,Normal,Cover,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1428,1429,435,7955,2012-02-22 00:00:00,49,Balanced,NaN,Little,50,Mixed,...,Normal,Organised,34,Medium,31,Contain,51,Normal,Cover,NaN
1429,1430,1742,9868,2010-02-22 00:00:00,30,Slow,NaN,Little,30,Short,...,Lots,Organised,45,Medium,50,Press,45,Normal,Cover,NaN
1430,1431,1742,9868,2011-02-22 00:00:00,40,Balanced,NaN,Little,58,Mixed,...,Normal,Organised,46,Medium,52,Press,67,Wide,Cover,NaN
1431,1432,1742,9868,2012-02-22 00:00:00,60,Balanced,NaN,Little,44,Mixed,...,Normal,Organised,49,Medium,54,Press,50,Normal,Cover,NaN
1432,1433,1742,9868,2013-09-20 00:00:00,60,Balanced,NaN,Little,44,Mixed,...,Normal,Organised,49,Medium,54,Press,50,Normal,Cover,NaN
1433,1434,900,10192,2010-02-22 00:00:00,55,Balanced,NaN,Little,55,Mixed,...,Normal,Organised,55,Medium,55,Press,60,Normal,Offside Trap,High Pressure at defense!!
1434,1435,900,10192,2011-02-22 00:00:00,60,Balanced,NaN,Little,57,Mixed,...,Lots,Organised,48,Medium,49,Press,61,Normal,Cover,NaN
1435,1436,900,10192,2012-02-22 00:00:00,52,Balanced,NaN,Little,69,Long,...,Normal,Organised,44,Medium,34,Press,50,Normal,Cover,NaN
1436,1437,900,10192,2013-09-20 00:00:00,52,Balanced,NaN,Little,69,Long,...,Normal,Organised,44,Medium,34,Press,50,Normal,Cover,NaN
1437,1438,900,10192,2014-09-19 00:00:00,52,Balanced,56.0,Normal,64,Mixed,...,Normal,Organised,44,Medium,34,Press,50,Normal,Cover,NaN
1438,1439,900,10192,2015-09-10 00:00:00,52,Balanced,56.0,Normal,64,Mixed,...,Normal,Organised,44,Medium,34,Press,50,Normal,Cover,NaN
1439,1440,110749,8021,2010-02-22 00:00:00,55,Balanced,NaN,Little,60,Mixed,...,Lots,Organised,70,High,70,Double,70,Wide,Cover,High Pressure at defense!!
1440,1441,110749,8021,2011-02-22 00:00:00,54,Balanced,NaN,Little,37,Mixed,...,Normal,Organised,47,Medium,58,Press,52,Normal,Cover,NaN
1441,1442,110749,8021,2012-02-22 00:00:00,33,Slow,NaN,Little,38,Mixed,...,Lots,Organised,58,Medium,47,Press,52,Normal,Cover,High Pressure at defense!!
1442,1443,110749,8021,2013-09-20 00:00:00,33,Slow,NaN,Little,38,Mixed,...,Normal,Organised,58,Medium,47,Press,52,Normal,Cover,High Pressure at defense!!
1443,1444,110749,8021,2014-09-19 00:00:00,33,Slow,49.0,Normal,51,Mixed,...,Normal,Organised,58,Medium,38,Press,52,Normal,Cover,High Pressure at defense!!
1444,1445,244,8394,2010-02-22 00:00:00,30,Slow,NaN,Little,30,Short,...,Lots,Organised,40,Medium,30,Contain,45,Normal,Offside Trap,NaN
1445,1446,244,8394,2011-02-22 00:00:00,43,Balanced,NaN,Little,40,Mixed,...,Normal,Organised,38,Medium,40,Press,53,Normal,Cover,NaN
1446,1447,244,8394,2012-02-22 00:00:00,34,Balanced,NaN,Little,23,Short,...,Normal,Organised,51,Medium,46,Press,61,Normal,Cover,High Pressure at defense!!
1447,1448,244,8394,2013-09-20 00:00:00,38,Balanced,NaN,Little,23,Short,...,Normal,Organised,51,Medium,46,Press,61,Normal,Cover,High Pressure at defense!!
1448,1449,244,8394,2014-09-19 00:00:00,38,Balanced,48.0,Normal,35,Mixed,...,Normal,Organised,51,Medium,46,Press,61,Normal,Cover,High Pressure at defense!!
1449,1450,244,8394,2015-09-10 00:00:00,52,Balanced,52.0,Normal,50,Mixed,...,Normal,Organised,48,Medium,43,Press,49,Normal,Cover,NaN
1450,1451,112512,8027,2014-09-19 00:00:00,54,Balanced,51.0,Normal,40,Mixed,...,Normal,Organised,44,Medium,47,Press,52,Normal,Cover,NaN
1451,1452,112512,8027,2015-09-10 00:00:00,54,Balanced,51.0,Normal,40,Mixed,...,Normal,Organised,44,Medium,47,Press,52,Normal,Cover,NaN
1452,1453,15005,10000,2010-02-22 00:00:00,65,Balanced,NaN,Little,60,Mixed,...,Normal,Organised,70,High,60,Press,70,Wide,Cover,High Pressure at defense!!
1453,1454,15005,10000,2011-02-22 00:00:00,52,Balanced,NaN,Little,52,Mixed,...,Normal,Organised,46,Medium,48,Press,53,Normal,Cover,NaN
1454,1455,15005,10000,2012-02-22 00:00:00,54,Balanced,NaN,Little,51,Mixed,...,Normal,Organised,44,Medium,55,Press,53,Normal,Cover,NaN
1455,1456,15005,10000,2013-09-20 00:00:00,54,Balanced,NaN,Little,51,Mixed,...,Little,Organised,44,Medium,58,Press,37,Normal,Cover,NaN
1456,1457,15005,10000,2014-09-19 00:00:00,54,Balanced,42.0,Normal,51,Mixed,...,Little,Organised,44,Medium,58,Press,37,Normal,Cover,NaN
1457,1458,15005,10000,2015-09-10 00:00:00,54,Balanced,42.0,Normal,51,Mixed,...,Little,Organised,44,Medium,58,Press,37,Normal,Cover,NaN